### ISSUE TITLE
Add support (might just be docs) for external DNS

### ISSUE THREAD

**Issue by richarddli** [emissary-ingress/emissary#1057]
https://github.com/kubernetes-incubator/external-dns

See https://github.com/datawire/ambassador/issues/1053#issuecomment-449118512 for some context

**Comment by jwhitlark** [comment]
This is a big problem for us, too.  I can't tell from the docs if it's possible, easy, or impossible.

On aws, we usually just add the annotation (to a service)
    external-dns.alpha.kubernetes.io/hostname: foo.example.com.

**Comment by seslattery** [comment]
I don't believe this issue should be closed.  There is no reference in the docs that I can find to reference if you support external-dns https://github.com/kubernetes-incubator/external-dns.  Would be useful to know if ambassador supports this.  Basically need to know if amabassador updates Ingress Status. As an example, traefik added support for this here: https://github.com/containous/traefik/pull/3324

**Comment by jwhitlark** [comment]
I agree with Sean.

**Comment by richarddli** [comment]
Yes, I think this was inadvertently closed. PRs for this are welcome!

**Comment by stefansedich** [comment]
+1 on this, would be great to be able to handle this in a simple way like you can for Ingress resources, my current workaround is to annotate my Ambassador service with all the domains I want to point to it and use host based mappings:

```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ...
    external-dns.alpha.kubernetes.io/hostname: >-
      foo.com,
      bah.com
```

While this works it just adds some duplication, and it would be nice to be able to define the DNS entries along with my individual services helm charts.

I came across this https://github.com/kubernetes-incubator/external-dns/blob/master/docs/contributing/crd-source.md but it looks like the DNSEndpoint targets are simply IPs and cannot map to a specific service.

**Comment by Eronarn** [comment]
+1 on this. We have a cluster that will have independent internal and internet-facing load balancers. We'd prefer not to have to run different DNS wildcards, different SSL certs, and so on. The in-progress Ingress support is a good start, but I'd like to see the same support for load balancer `statuss field updates on Services; and ideally, a roadmap to supporting external DNS for Mapping CRDs.

Also, documentation on all three approaches would be great. The references to DNS on the Ambassador homepage are about intra-cluster DNS.

**Comment by seh** [comment]
> I came across this https://github.com/kubernetes-incubator/external-dns/blob/master/docs/contributing/crd-source.md but it looks like the DNSEndpoint targets are simply IPs and cannot map to a specific service.

The `DNSEndpoint.Targets` field holds strings, and those strings can be DNS names, so long as the record type is [CNAME](https://sourcegraph.com/github.com/kubernetes-incubator/external-dns@cec75d7/-/blob/source/crd_test.go#L257-L261) or [SRV](https://sourcegraph.com/github.com/kubernetes-incubator/external-dns@cec75d7da4d39e2eba9c2ded733bd6b5831fd73e/-/blob/source/service_test.go#L1316). Does that help with the mapping you're trying to arrange?

**Comment by stefansedich** [comment]
This has now been resolved with the addition of Ingress support and should
cover my needs when 0.84.0 drops!

**Comment by seh** [comment]
Oh, Ambassador is going to read _Ingress_ objects? How will that interact with the _Mapping_ objects?

**Comment by seh** [comment]
Note, though, that External DNS would still need to be taught to watch your _Mapping_ objects. Note that for Contour, they had to add [a new "source"](https://github.com/kubernetes-incubator/external-dns/blob/9cb6a7838ec71eb5e164b81254ca78a6566f00af/source/ingressroute.go) to External DNS; they couldn't piggyback on the existing _Ingress_ source.

The Traefik project has waffled—in containous/traefik#4655—on which way to go here too.

**Comment by thejmazz** [comment]
> Note, though, that External DNS would still need to be taught to watch your Mapping objects

Yeah, I was hypothesizing that perhaps external-dns could instead use unstructured and then have a config something like

```yaml
watch:
- apiGroup: “getammbassador.io/v1”
  resources: “Mapping”
```

And then code within external-dns just grabs `status.loadBalancer.ingress` without knowing the resource kinds. Then external-dns would be able to use out-of-tree resources without requiring PRs. But anyways that’s just me taking a guess, it could very well not be possible that way. Thanks for linking the Traefik discussion. Seems external-dns approach to supporting out-of-tree is it’s DNSEndpoint CRD which I can see in the linked discussions has its own cons.

Personally, I think having to manage a new DNSEndpoint CRD and associated RBAC etc is worth it (I don’t consider it a great burden) and would be welcome to see Ambassador support this feature on Mappings by having the Mapping controller manager DNSEndpoint resources. See [gardener/external-dns-management - Why not using the community external-dns solution?](https://github.com/gardener/external-dns-management/blob/fd8c80d253b219d35bb88fdb59cdabb2a32c0cdd/README.md#why-not-using-the-community-external-dns-solution) for some arguments supporting managing DNS records via a CRD.

**Comment by concaf** [comment]
not stale

**Comment by phyllisstein** [comment]
I was facing similar uncertainties about integrating ExternalDNS and Ambassador. I wanted to take advantage of Ambassador's weighted mapping capabilities without losing the `Ingress` resource, which ExternalDNS can read out of the box. I found that defining an `Ingress` alongside richer Ambassador `Mapping`s worked about as expected.

Here's a test manifest that I tried in Minikube. When I `curl`ed it with the appropriate `Host` header, it routed to nginx most of the time but hit the echo resource some of the time. Definitely wasn't 50/50, in my testing.

```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: echo-nginx

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo
  namespace: echo-nginx
  labels:
    app.kubernetes.io/name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      containers:
        - name: echo
          image: electroma/ingress-demo-echosvc-amd64:0.1
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: echo-nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: echo
          image: nginx:1.17.9
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi

---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: echo-nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - name: http
      port: 8080
      targetPort: http

---
kind: Service
apiVersion: v1
metadata:
  name: echo
  namespace: echo-nginx
  labels:
    app.kubernetes.io/name: echo
spec:
  selector:
    app.kubernetes.io/name: echo
  ports:
    - name: http
      port: 8080
      targetPort: http

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: echo-nginx
  namespace: echo-nginx
  annotations:
    kubernetes.io/ingress.class: ambassador
  labels:
    app.kubernetes.io/name: echo-nginx
spec:
  rules:
    - host: dashboard.danielsh.here
      http:
        paths:
          - backend:
              serviceName: echo
              servicePort: http
          - backend:
              serviceName: nginx
              servicePort: http

---
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  name: echo
  namespace: echo-nginx
spec:
  prefix: /
  host: dashboard.danielsh.here
  service: echo:8080
  weight: 10

---
kind: Mapping
apiVersion: getambassador.io/v2
metadata:
  name: nginx
  namespace: echo-nginx
spec:
  prefix: /
  host: dashboard.danielsh.here
  service: nginx:8080
  weight: 90
```
