### ISSUE TITLE
Does ambassdor support 307 redirect?

### ISSUE THREAD

**Issue by yue-wen** [emissary-ingress/emissary#1295]
Environment: k8s
Version: ambassador:0.50.3
Is that possible to send 307 redirect?

by default ambassador send  301 ( Moved Permanently) .
I try follow setting to send 307 (Temporary Redirect) but still get 301 status code.
 
```
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  catch_and_redirect_if_no_match
      prefix: /
      rewrite: /
      add_response_headers:
        status: '307'
      host_redirect: true
      service: httpbin.org
```
So my question is: 
Does ambassador support this kind feature? 
Could someone please link me related source code for this. 
thank you.
