### ISSUE TITLE
Include x-forwarded-client-certificate header

### ISSUE THREAD

**Issue by juanjoku** [emissary-ingress/emissary#1543]
**Please describe your use case / problem.**

When client-certificate verification is used, the x-forwarded-client-certificate (XFCC) header is not being set (or any equivalent one), so the client app can't know the identity of the user making the request.
I think this is required for client certificate validation to be useful.

**Describe the solution you'd like**

In the TLSContext definition, add a property that enables setting the XFCC header.

```
  apiVersion: ambassador/v1
  kind: TLSContext
  name: myapp-tls-context
  hosts:
  - myapp.blabla.org
  secret: myapp-server-tls
  ca_secret: myapp-cacert
  cert_required: true / false
  xfcc: true / false  <<== for example
```
  
The configuration could go further, and allow mapping Envoy's "forward_client_cert_details" and "set_current_client_cert_details" properties.

https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.html?highlight=forward_client_cert_details#enum-config-filter-network-http-connection-manager-v2-httpconnectionmanager-forwardclientcertdetails

**Describe alternatives you've considered**

I couldn't find any.

**Additional context**

Nothing.

**Comment by sagibel** [comment]
I have encountered this issue as well, and cannot use Ambassador without a solution for this issue, as it's a requirement.

However I would like the client certificate to be forwarded to the AuthService, as that's where we would expect the client identity to be verified (e.g. from the `subject` field in the certificate).

**Comment by juanjoku** [comment]
This issue should not be closed, because is not yet been resolved !!

**Comment by albertdb** [comment]
Could you please give some priority to this?

**Comment by ovk** [comment]
This issue definitely needs more priority. It also currently prevents us from using Ambassador in production.

In a case when Ambassador does TLS termination it must be able to pass client certificate information somewhere, so that some service could extract identity from the certificate and perform necessary authentication steps. For example, see this documentation on Keycloak's [client cert auth configuration](https://www.keycloak.org/docs/latest/server_admin/index.html#client-certificate-lookup) behind a reverse proxy with TLS termination.

Passing client certificate information through is a trivial configuration for HAProxy, Apache, Nginx and Traefik, and I think is absolutely needed for Ambassador.

**Comment by ovk** [comment]
It looks like there is a possible workaround to add client certificate to headers.

I stumbled upon the following special field from Envoy:

https://github.com/envoyproxy/envoy/blob/92c085afaeeed138067f289fa9294d56afc91e25/source/common/router/header_formatter.cc#L261

that appear to work fine with Ambassador.

For example:

```yaml
  add_request_headers:
    x-forwarded-client-cert: "%DOWNSTREAM_PEER_CERT%"
```

**Comment by ovk** [comment]
Un-stale

**Comment by jwm** [comment]
not stale

**Comment by sagibel** [comment]
> It looks like there is a possible workaround to add client certificate to headers.
> 
> I stumbled upon the following special field from Envoy:
> 
> https://github.com/envoyproxy/envoy/blob/92c085afaeeed138067f289fa9294d56afc91e25/source/common/router/header_formatter.cc#L261
> 
> that appear to work fine with Ambassador.
> 
> For example:
> 
> ```yaml
>   add_request_headers:
>     x-forwarded-client-cert: "%DOWNSTREAM_PEER_CERT%"
> ```

Unfortunately it doesn't help if I want to forward the certificate to the `AuthService`, as it seems there is currently no way to add headers to the forwarded request.
I sincerely hope that [PR#2053](https://github.com/datawire/ambassador/pull/2053) takes this into consideration as well.

**Comment by nbkrause** [comment]
@sagibel Unfortunately it will not. Requests to the `AuthService` go through a different routing mechanism in Ambassador than requests to upstreams and so the `add_request_headers` headers are not added to requests to the `AuthService`.

It appears like this could be possible to add headers in `add_request_headers` to the request to an http `AuthService` from taking a brief look at [Envoy's docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2-authorizationrequest). We may need to do something like the workaround  mentioned [here](https://github.com/envoyproxy/envoy/issues/4054#issuecomment-411598309) to get it working with gRPC `AuthService`s.

**Comment by jwm** [comment]
not stale

**Comment by marecica2** [comment]
Hi everyone, 
Im struggling to forward `x-forwarded-client-cert` in the backend service how the full config should look like to enable it, 
i tried to follow example at https://www.getambassador.io/docs/latest/topics/running/tls/mtls/
I'm not using authservice i just need to pass the cert chain downstream to keycloak

This setup doesnt pass that header at all, i tried both tls termination and tls origination
Do i have to somehow enable %DOWNSTREAM_PEER_CERT%  first? The header is just not present.

```
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name: iam-service-mapping-smartcard
spec:
  prefix: /iam-service-smartcard/
  rewrite: ""
  timeout_ms: 10000
  add_request_headers:
    x-forwarded-client-cert: "%DOWNSTREAM_PEER_CERT%"
  tls: iam-service-tls-context-smartcard
  service: https://iam-service-smartcar-http:8443

---

apiVersion: v1
data:
  tls.crt: ...
kind: Secret
metadata:
  name: iam-service-ambassador-client-certs
type: Opaque

---

apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: iam-service-tls-context-smartcard
spec:
  hosts: ["some.host.org"]
  secret: ambassador-certs
  ca_secret: iam-service-ambassador-client-certs
  cert_required: true
```
