### ISSUE TITLE
Figure out how to integrate Pro Filters with Mapping resources

### ISSUE THREAD

**Issue by LukeShu** [emissary-ingress/emissary#1623]
**Please describe your use case / problem.**

It would be good to integrate the A/Pro `FilterPolicy` resource type with the A/OSS `Mapping` resource type.

An A/Pro `FilterPolicy` looks like:
```
---
apiVersion: getambassador.io/v1beta2
kind: FilterPolicy
metadata:
  name: httpbin-policy
spec:
  rules:
    - host: "*"
      path: /httpbin/
      filters:
        - name: auth_filter # this refers to an instance of a `Filter` resource
          arguments:
            scopes:
            - "scope1"
            - "scope2"
```
An A/OSS `Mapping` looks like:
```
---
apiVersion: getambassador.io/v1
kind:  Mapping
metadata:
  name:  httpbin-mapping
spec:
  prefix: /httpbin/
  service: http://httpbin
```
You end up having to specify the same routes twice all the time, once for OSS and once for Pro.

**Describe the solution you'd like**

It would make a lot of sense, from a user-perspective, to just add a Pro-only `filters` field to the `Mapping` resource type.

Figuring out a good implementation strategy for that is less obvious.
