### ISSUE TITLE
diag console's Weight column doesn't reflect Mapping weight attributes

### ISSUE THREAD

**Issue by jwm** [emissary-ingress/emissary#2142]
**Describe the bug**
The diag console's `Weight` column shows 100% for the `Mapping`s for that endpoint, even when one or more `Mapping`s specifies `weight: 0`. In fact, the `Weight` column for all our endpoints says `100.0%` in the diag console, even though half have `0` weight.

For example:
```
[jmorrissey@root-box.root:pts/0 :heart:/a-i/a-dev {git:master!}> kubectl -n orinoco-09f42b416-1578082250 get service frontend -o jsonpath='{.metadata.annotations.getambassador\.io/config}'
---
apiVersion: ambassador/v1
connect_timeout_ms: 15000
host: admin.dev.devoted.com
idle_timeout_ms: 70000
kind: Mapping
name: orinoco-09f42b416-1578082250_admin_dev_devoted_com
prefix: /
resolver: endpoint
rewrite: /
service: frontend.orinoco-09f42b416-1578082250:3000
timeout_ms: 60000
weight: 0
[jmorrissey@root-box.root:pts/0 :heart:/a-i/a-dev {git:master!}> kubectl -n orinoco-a922c5d8a-1578082940 get service frontend -o jsonpath='{.metadata.annotations.getambassador\.io/config}'
---
apiVersion: ambassador/v1
connect_timeout_ms: 15000
host: admin.dev.devoted.com
idle_timeout_ms: 70000
kind: Mapping
name: orinoco-a922c5d8a-1578082940_admin_dev_devoted_com
prefix: /
resolver: endpoint
rewrite: /
service: frontend.orinoco-a922c5d8a-1578082940:3000
timeout_ms: 60000
weight: 0
```

![Screen Shot 2020-01-03 at 3 42 54 PM](https://user-images.githubusercontent.com/37176/71748663-3f6bc200-2e41-11ea-9088-4679c183a99a.png)

**To Reproduce**
1. Configure two `Mapping`s, one with `weight: 0`, the other with `weight: 100`
2. View the diag console. All values in the `Weight` column will be `100.0%`.

**Expected behavior**
One `Mapping` should show 0 weight, the other 100, matching the respective `Mapping` `weight` attributes.

**Versions (please complete the following information):**
 - Ambassador: 1.0.0-ea9
 - Kubernetes environment: EKS
 - Version: 1.13

**Comment by jwm** [comment]
not stale

**Comment by jwm** [comment]
not stale

**Comment by jwm** [comment]
FWIW, I'm still seeing this with 1.5.3:

```
[jmorrissey@root-box.root:pts/4 :heart:/a-i/a-prod {git:master!} {1 job}> kubectl -n orinoco-9b9f24ec2-1592607338 get service graphql -o jsonpath='{.metadata.annotations.getambassador\.io/config}'
---
apiVersion: ambassador/v1
circuit_breakers:
- max_connections: 10000
  max_pending_requests: 10000
connect_timeout_ms: 15000
host: graphql.prod.devoted.com
kind: Mapping
name: orinoco-9b9f24ec2-1592607338_graphql_prod_devoted_com
prefix: /
resolver: endpoint
rewrite: /
service: graphql.orinoco-9b9f24ec2-1592607338:443
timeout_ms: 1800000                                                                                                                                                                      tls: backend-graphql-client
[jmorrissey@root-box.root:pts/4 :heart:/a-i/a-prod {git:master!} {1 job}> kubectl -n orinoco-c3652f2bd-1592603489 get service graphql -o jsonpath='{.metadata.annotations.getambassador\.io/config}'
---
apiVersion: ambassador/v1
circuit_breakers:
- max_connections: 10000
  max_pending_requests: 10000
connect_timeout_ms: 15000
host: graphql.prod.devoted.com
kind: Mapping
name: orinoco-c3652f2bd-1592603489_graphql_prod_devoted_com
prefix: /
resolver: endpoint
rewrite: /
service: graphql.orinoco-c3652f2bd-1592603489:443
timeout_ms: 1800000
tls: backend-graphql-client
weight: 0
```

![Screen Shot 2020-06-19 at 9 52 32 PM](https://user-images.githubusercontent.com/37176/85188776-2fbd2a00-b277-11ea-9d4b-b113b0eebe3d.png)

**Comment by jwm** [comment]
not stale

**Comment by jwm** [comment]
not stale

**Comment by jwm** [comment]
not stale

**Comment by iowillhoit** [comment]
not stale

**Comment by jkylling** [comment]
I have encountered the same when using shadow mappings.
My mappings are
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: api
  namespace: default
spec:
  add_response_headers:
    Strict-Transport-Security: max-age=31536000
  circuit_breakers:
  - max_retries: 1000
    priority: default
  cluster_tag: api
  labels:
    ambassador:
    - d0:
      - api
      - xratelimitid:
          header: X-Ratelimit-Id
          omit_if_not_present: true
  method: POST
  prefix: /api/projects/[^/]+/endpoint/?
  prefix_regex: true
  regex_rewrite:
    pattern: (/api/projects/[^/]+/endpoint)/?
    substitution: \1
  retry_policy:
    num_retries: 5
    retry_on: 5xx
  rewrite: ""
  service: https://api.default.svc:443
  timeout_ms: 90000
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: api-shadow
  namespace: default
spec:
  circuit_breakers:
  - max_retries: 1000
    priority: default
  cluster_tag: api
  labels:
    ambassador:
    - d0:
      - api
      - xratelimitid:
          header: X-Ratelimit-Id
          omit_if_not_present: true
  method: POST
  prefix: /api/projects/[^/]+/endpoint/?
  prefix_regex: true
  regex_rewrite:
    pattern: (/api/projects/[^/]+/endpoint)/?
    substitution: \1
  retry_policy:
    num_retries: 5
    retry_on: 5xx
  rewrite: ""
  service: https://api-shadow.default.svc
  shadow: true
  timeout_ms: 90000
  weight: 10
```
Here the shadow mapping has weight 10.
Yet in the admin panel at `http://localhost:8877/ambassador/v0/diag/` the weight for the shadow mapping is 100%
```
http://localhost:8877/my-endpoint?  api.default.svc:443                                100%
                                                               shadow: api-shadow.default.svc:443  100.0%
```
It looks like this is only an UI issue, as container metrics indicated that only 10% of the requests were forwarded to the shadow mapping.
```
ambassador --version
Ambassador 1.13.10-dev.26+g17c6bb2c7
Ambassador Scout version 1.13.10-dev.26+g17c6bb2c7
Ambassador Scout semver  1.13.10-dev.26+g17c6bb2c7
```
