### ISSUE TITLE
Unable to add different module configuration for Ambassador Edge Stack multi-setup

### ISSUE THREAD

**Issue by mrtnfchs** [emissary-ingress/emissary#2283]
I have a multi-setup of Ambassador Edge Stack (eg: ambassador-external and ambassador-internal) and both setups live in the same namespace so they can share CRD's, AuthService and RateLimitService. Using the ambassador_id  you should be able to apply object to a given (or both) setups. Unfortunately as far as I can tell, we're not able to create multiple Modules to apply different config for every setup

```
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador-external
spec:
  ambassador_id: [ "ambassador-external" ]
  config:
    server_name: ambassador-external
    diagnostics:
      enabled: false
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador-internal
spec:
  ambassador_id: [ "ambassador-internal" ]
  config:
    server_name: ambassador-internal
    diagnostics:
      enabled: true
```

It seems the above config is not picked up by any of the setups but when I use the module and specify the name **ambassador** it does

```
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
spec:
  ambassador_id: [ "ambassador-external", "ambassador-internal" ]
  config:
    server_name: ambassador
    diagnostics:
      enabled: true
```
I'm under the impression Ambassador only picks up/reads the module with a fixed **ambassador** name. Even if I would specify only one ambassador_id the config will only be applied to one setup. Unfortunately this prevents us from creating multiple modules as every module needs a unique name. Ideally we should be able to configure both setup module differently.

I'm using following versions:
- Ambassador Edge Stack helm chart v6.1.1
- Ambassador Edge Stack image v1.1.0
- AWS EKS with Kubernetes v1.14.8
