### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by shubhamsoni136** [emissary-ingress/emissary#2604]
**Describe the bug**
On setting up the ssl certificate using amazon certificate manager for ambassador service of type AWS classic loadbalancer, The host based routing is not working. Chrome is unable to load page giving error ERR_TOO_MANY_REDIRECTS 

The routing was working before setting up the ssl on http connection but after setting up the certificate it stopped working.

**To Reproduce**
1. Install Ambassador using helm
2. Edit the ambassador to support https connection using amazon certificate manager configuration file
```
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "< certificate arn >"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    getambassador.io/config: |
      ---
      apiVersion: getambassador.io/v2
      kind:  Module
      name:  ambassador1
      config:
        use_remote_address: false
        use_proxy_proto: true
spec: 
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 8443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/name: ambassador 
```
3. Create a service with hosnamet base routing.
4. Hit the the url 

**Expected behavior**
It should load the page, instead of thorwing error

**Versions (please complete the following information):**
 - Ambassador: 1.3.2
 - Kubernetes environment: Aws EKS
 - Version: 1.15

**Additional context**

**Comment by EvertonSA** [comment]
is anyone facing the same  issue?

**Comment by EvertonSA** [comment]
@shubhamsony I also noticed you did not change the routing for the service as described in the documentation:
```
  ports:
  - name: https
    port: 443
    targetPort: 8080
  - name: http
    port: 80
    targetPort: 8080
```

but setting the port to 8080 did not help me either
