### ISSUE TITLE
Automatic HTTPS not generating

### ISSUE THREAD

**Issue by nilesh93** [emissary-ingress/emissary#2664]
Ambassador Host resource doesn't generate a Certificate via ACME client

I followed the official documentation and created a host as the following
```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ambassador-host
spec:
  hostname: quote.svc.ambassador.dev.platformer.com
  acmeProvider:
    email: nilesh93.j@gmail.com
```

This is stuck in the following stage
```
NAME              HOSTNAME                                  STATE   PHASE COMPLETED   PHASE PENDING               AGE
ambassador-host   quote.svc.ambassador.dev.platformer.com   Error   DefaultsFilled    ACMEUserPrivateKeyCreated   3m6s
```

The AES console shows this as the error
```
Error (Operation cannot be fulfilled on secrets "https-3a-2f-2facme-2dv02.api.letsencrypt.org-2fdirectory--nilesh93.j-40gmail.com": StorageError: invalid object, Code: 4, Key: /registry/secrets/ambassador/https-3a-2f-2facme-2dv02.api.letsencrypt.org-2fdirectory--nilesh93.j-40gmail.com, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 28c1cf86-d9c1-445b-b0c6-369df2c52e79, UID in object meta: )
```

I'm using AES 1.4.2

**Comment by drekle** [comment]
If anyone runs into this I was able to resolve by shortening the automatically generated host spec field entry `.spec.acmeProvider.privateKeySecret.name`

```
  spec:
    acmeProvider:
      privateKeySecret:
        name: manual-short-secret-name
```

Seems like the super long URL encoded generated value has issues.
