### ISSUE TITLE
Diagnostic UI would not report Mappings error on tls

### ISSUE THREAD

**Issue by nicolasbelanger** [emissary-ingress/emissary#2686]
**Describe the bug**
Errors in the `.spec.tls` field of a mapping fails silently and are not reported in the UI diag.

**To Reproduce**
1. Have a TLSContext named `istio-upstream`
```yaml
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: istio-upstream
  namespace: ambassador
spec:
  ...
```
2. Have a Mapping with .spec.tls set to `upstream`
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: nginx-mapping
  namespace: nginx
spec:
  ...
  tls: upstream
```
3. No error reported in `/ambassador/v0/diag/`...

**Expected behavior**
A clear error that the `upstream` TLSContext does not exist.

**Versions (please complete the following information):**
 - Ambassador: 1.2.2
 - Kubernetes environment EKS 1.14
