### ISSUE TITLE
Ambassador + etcd: gRPC mappings are not behaving as expected

### ISSUE THREAD

**Issue by christian-roggia** [emissary-ingress/emissary#2704]
**Describe the bug**
I recently attempted to deploy Ambassador with an internal load balancer (GKE) on the perimeter of our cluster. Ambassador should act as the edge proxy and route traffic to our internal gRPC services (etcd and dgraph). So far I attempted to redirect traffic only for etcd but I have been unsuccessful with the configuration and I cannot reach the etcd server with a client external to the cluster.

I would like to point out that with etcdctl and ` kubectl port-forward` the connection is established successfully, while with Ambassador the following error is shown:

**Custom service running the official etcd client for Golang**
```
put etcd: failed with error - connection to etcd server failed: rpc error: code = Unknown desc = 
```

**etcdctl (with `--debug`)**
```
INFO: 2020/05/15 01:57:04 parsed scheme: "endpoint"
INFO: 2020/05/15 01:57:04 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:8080 0  <nil>}]
{"level":"warn","ts":"2020-05-15T01:57:05.598+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-430869ea-c97d-4dbd-a1ce-2b30bb518d20/127.0.0.1:8080","attempt":0,"error":"rpc error: code = Unknown desc = "}
Error: rpc error: code = Unknown desc = 
```

**This is what I am expecting for a healthy connection:**
```
INFO: 2020/05/15 01:57:57 parsed scheme: "endpoint"
INFO: 2020/05/15 01:57:57 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:2379 0  <nil>}]
INFO: 2020/05/15 01:57:58 transport: loopyWriter.run returning. connection error: desc = "transport is closing"
INFO: 2020/05/15 01:57:58 parsed scheme: "endpoint"
INFO: 2020/05/15 01:57:58 ccResolverWrapper: sending new addresses to cc: [{127.0.0.1:2379 0  <nil>}]
```

**To Reproduce**

1) Deploy Ambassador via Helm 3 https://github.com/datawire/ambassador-chart
2) Deploy etcd via Helm 3 https://github.com/bitnami/charts/tree/master/bitnami/etcd
3) Configure mappings for etcd
4) Attempt to connect to etcd via `etcdctl`

**values.yaml** (Ambassador)
```yaml
adminService:
  create: false

authService:
  create: false

createDevPortalMappings: false

env:
  AMBASSADOR_ID: "ambassador-internal"

licenseKey:
  value: "..."
  createSecret: true

replicaCount: 1

service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
```

**module.yaml** (Ambassador)
```yaml
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador-internal
spec:
  ambassador_id: [ "ambassador-internal" ]
  config:
    diagnostics:
      enabled: false
```

**values.yaml** (etcd)
```yaml
statefulset:
  replicaCount: 1

auth:
  rbac:
    enabled: true
    rootPassword: secretpassword

metrics:
  enabled: true
```

**mappings.yaml** (etcd)
```yaml
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  etcd-kv
spec:
  ambassador_id: [ "ambassador-internal" ]
  grpc: True
  prefix: /etcdserverpb.KV/
  rewrite: /etcdserverpb.KV/
  service: "etcd:2379"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  etcd-watch
spec:
  ambassador_id: [ "ambassador-internal" ]
  grpc: True
  prefix: /etcdserverpb.Watch/
  rewrite: /etcdserverpb.Watch/
  service: "etcd:2379"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  etcd-lease
spec:
  ambassador_id: [ "ambassador-internal" ]
  grpc: True
  prefix: /etcdserverpb.Lease/
  rewrite: /etcdserverpb.Lease/
  service: "etcd:2379"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  etcd-cluster
spec:
  ambassador_id: [ "ambassador-internal" ]
  grpc: True
  prefix: /etcdserverpb.Cluster/
  rewrite: /etcdserverpb.Cluster/
  service: "etcd:2379"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  etcd-maintenance
spec:
  ambassador_id: [ "ambassador-internal" ]
  grpc: True
  prefix: /etcdserverpb.Maintenance/
  rewrite: /etcdserverpb.Maintenance/
  service: "etcd:2379"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  etcd-auth
spec:
  ambassador_id: [ "ambassador-internal" ]
  grpc: True
  prefix: /etcdserverpb.Auth/
  rewrite: /etcdserverpb.Auth/
  service: "etcd:2379"
```

`kubectl port-forward etcd-0 2379:2379`

followed by

`./etcdctl --endpoints=127.0.0.1:2379 --user=root --password=secretpassword --debug user list`

**works properly**.

`kubectl port-forward $(kubectl get pod --selector="app.kubernetes.io/instance=ambassador,app.kubernetes.io/name=ambassador" --output jsonpath='{.items[0].metadata.name}') 8080:8080`

followed by

`./etcdctl --endpoints=127.0.0.1:8080 --user=root --password=secretpassword --debug user list`

**does not work**.

The request hits Ambassador but something goes wrong in the connection to etcd:
```
ACCESS [2020-05-14T19:21:15.824Z] "POST /etcdserverpb.Auth/Authenticate HTTP/2" 200 - 0 0 0 - "XXX.XXX.XXX.XXX" "grpc-go/1.21.0" "6865a1f6-7d17-4a16-af7c-f2767c19367f" "XXX.XXX.XXX.XXX" "-"
```

**Expected behavior**

**Versions (please complete the following information):**
 - Ambassador: `quay.io/datawire/aes:1.4.3`
 - etcd: `bitnami/etcd:3.4.7-debian-10-r41`
 - etcdctl: `3.4.7`
 - Kubernetes environment: `GKE 1.14.10-gke.36` (machine type `e2-standard-2`)

**Additional context**
None.
