### ISSUE TITLE
Ingress returns 504 for all requests

### ISSUE THREAD

**Issue by thiagolsfortunato** [emissary-ingress/emissary#2746]
**Describe the bug**
I follow [this](https://www.getambassador.io/docs/latest/topics/running/ambassador-with-gke/) tutorial and [this](https://blog.getambassador.io/deploying-java-apps-with-kubernetes-and-the-ambassador-api-gateway-c6e9d9618f1b) article to install Ambassador on my GKE cluster with an Ingress, but all requests sent to my Ingress returns `502 Server Error`. 

Reading logs, I found this warn, but I think this is not the problem: 
```
[2020-05-29 22:03:31.395][113][warning][misc] [bazel-out/k8-opt/bin/source/extensions/common/_virtual_includes/utility_lib/extensions/common/utility.h:65] Using deprecated extension name 'envoy.router' for 'envoy.filters.http.router'. This name will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details
``` 

**Expected behavior**

Installation works and sends traffic to web deployments configured using Mappings.

**Versions (please complete the following information):**
 - Ambassador: `1.5.0`
 - Kubernetes environment: `Google Kubernetes Engine`
 - Version: `1.16.8-gke-15`

**Additional context**

Configurartions files:

[ambassador-rbac.yaml](https://getambassador.io/yaml/ambassador/ambassador-rbac.yaml) was added also this section:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  ports:
    - name: ambassador
      port: 8080
      targetPort: 8080
  selector:
    service: ambassador
```

ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ambassador-ingress
spec:
  backend:
    serviceName: ambassador
    servicePort: 8080
```

web.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      run: web
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    run: web
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

---

apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: web
spec:
  prefix: /*
  service: web:8080
```

**Comment by admiralobvious** [comment]
Having the same problem on an existing cluster running 1.16.8-gke.15. It works on a newly created cluster just for that purpose though. I am thinking recreating the Ingress on my existing cluster will probably resolve the issue. It's a test cluster so I can do this at any time. Will report back.

**Comment by admiralobvious** [comment]
So recreating the Ingress on the existing cluster didn't fix the issue.

Describing my Ingress I see:
```
  hub.test.mydomain.co
                            /*   ambassador:8080 (<none>)
```

Although the backend is healthy:
```
"k8s-be-32067--b429978f36e45cd8":"HEALTHY"
```

Seems like it can't see the ambassadors? They're definitely running and I can `cURL` them from within the cluster.

```
NAME                             READY   STATUS    RESTARTS   AGE     IP           NODE                                          NOMINATED NODE   READINESS GATES
ambassador-5d7684c8f7-gglcv      1/1     Running   0          27m     10.7.11.13   gke-test-1-app-pool-93007a16-7c54             <none>           <none>
ambassador-5d7684c8f7-skrrd      1/1     Running   0          27m     10.7.11.14   gke-test-1-app-pool-93007a16-7c54             <none>           <none>
ambassador-5d7684c8f7-tnn49      1/1     Running   0          27m     10.7.11.12   gke-test-1-app-pool-93007a16-7c54             <none>           <none>
```

```
NAME                TYPE           CLUSTER-IP    EXTERNAL-IP      PORT(S)             AGE
ambassador          NodePort       10.7.7.136    <none>           8080:32067/TCP      42m
ambassador-admin    NodePort       10.7.6.144    <none>           8877:32105/TCP      44m
```

```
appuser@api-6d646bfdb-cflc7:~$ curl http://10.7.11.13:8877/ambassador/v0/check_ready
ambassador readiness check OK (3 seconds ago)
```

I correctly edited the health-check on `32067` to point to `32105` and `/ambassador/v0/check_ready` too as the backend is shown as `HEALTHY`.

**Comment by thiagolsfortunato** [comment]
> I correctly edited the health-check on 32067 to point to 32105 and /ambassador/v0/check_ready too as the backend is shown as HEALTHY.

I did the same!

But now, my problem is HTTP -> HTTPS
```
$ curl -LI 34.102.183.121
HTTP/1.1 301 Moved Permanently
location: https://34.102.183.121/
date: Mon, 01 Jun 2020 16:57:05 GMT
server: envoy
transfer-encoding: chunked
Via: 1.1 google

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 34.102.183.121:443
```

My adventure continues... 

I'm adding [Cert-Manager with Ambassador](https://www.getambassador.io/docs/latest/howtos/cert-manager/) to redirect traffic from [HTTP to HTTPS](https://www.getambassador.io/docs/latest/topics/running/tls/cleartext-redirection/#http-https-redirection)

**Comment by admiralobvious** [comment]
@thiagolsfortunato make sure you're following the instructions to the letter. You need to use a domain name as well. I got it to work on my dev cluster.

I also fixed the issue on the existing cluster, turns out the ambassador service I created myself had an extra `selector` added by my `kustomize` setup which off course the ambassador deployment doesn't have. And this is why you download manifests and check their config yourself.

**Comment by thiagolsfortunato** [comment]
@admiralobvious Yes, is everything works until before HTTP -> HTTPS, but the request no arrive at my services because of redirects (forced by ambassador). The same was happen when I add a domain name.

**Comment by thiagolsfortunato** [comment]
I fix my configs and now It's working. :tada:   

My suggestion is to update this [tutorial](https://www.getambassador.io/docs/latest/topics/running/ambassador-with-gke/#enabling-http---https), adding the section of the configuring Hosts. By default, Ambassador redirects all requests to HTTPS, but I believe this is not required on init configuration. To works do that we need to research and add more complexity to configuration, like add Cert Manager to generate a valid certificate, then add to Host to fix redirect 301.

Only adding this configuration about Host on the tutorial, It's enough.

```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: ambassador
spec:
  hostname: '*'
  acmeProvider:
    authority: none
  requestPolicy:
    insecure:
      action: Route
```
