### ISSUE TITLE
Users want a way to configure Mappings generated from K8s Ingress resources

### ISSUE THREAD

**Issue by dvianello** [emissary-ingress/emissary#2849]
**Describe the bug**
When using `Ingress` + `Mapping` annotation  together to
- get `ExternalDNS` to create the required DNS records
- set `grpc: True` to support `HTTP/2`-only upstreams

Ambassador sets up _two_ Envoy clusters for the given DNS record, effectively creating a 50/50 traffic split. This _breaks_ in our use-case as the Ingress-driven route isn't configured for `HTTP/2`-only upstream, causing 50% of the connections to fail.
Based on my reading of the [relevant docs](https://www.getambassador.io/docs/latest/topics/running/ingress-controller/#ambassador-ingress-support) it sounds like this scenario should be supported.

**To Reproduce**
1. Apply the following Ingress with Mapping annotation:
```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: test-browser
  namespace: test
  annotations:
    kubernetes.io/ingress.class: ambassador
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: test-browser
      service: http://test-browser.test:8000
      host: test-browser.foo.com
      grpc: True
      prefix: /
      rewrite: /
spec:
  rules:
    - host: test-browser.foo.com
      http:
        paths:
          - backend:
              serviceName: test-browser
              servicePort: 8000
```
2. Check that Ambassador sets up a 50/50 traffic split instead of merging Ingress and Mapping
4. Send traffic through, observe ~50% of traffic failing.

**Expected behavior**
Ambassador merges Ingress and Mapping definition into a _single_ Envoy cluster.

**Versions (please complete the following information):**
 - Ambassador: 1.5.5
 - Kubernetes environment: EKS
 - Version: 1.16.8

**Additional context**
We're currently using a work-around and annotating the Ambassador K8S service with the `external-dns.alpha.kubernetes.io/hostname:` key listing all the DNS names we want pointed to Ambassador, but this effectively means all the DNS configuration needs to be done at the Ambassador service level, which isn't sustainable long term.
