### ISSUE TITLE
HTTP 502 json: cannot unmarshal string into Go struct field .expires_in of type float64

### ISSUE THREAD

**Issue by FireDrunk** [emissary-ingress/emissary#2907]
**Describe the bug**
I'm trying to build a fairly simple demo environment with Azure AD. 

Config:

app:
```
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - name:  web
    port:  80
    targetPort:  80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

Filter + Policy:
```
---
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: azure-ad
  namespace: default
spec:
  OAuth2:
    authorizationURL: https://sts.windows.net/<tenant-id>/
    clientID: <clientid>
    secret: <password>
    protectedOrigins:
    - origin: "https://localhost/backend/"
---
---
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: nginx-policy
  namespace: default
spec:
  rules:
    - host: "*"
      path: /backend/
      filters:
        - name: azure-ad
```

When going to the url, i'm properly redirected to Azure AD, and redirected back. But I receive this response:
```time="2020-08-03 08:57:15" level=error msg="HTTP 502 json: cannot unmarshal string into Go struct field .expires_in of type float64" func=github.com/datawire/apro/cmd/amb-sidecar/filters/handler/middleware.errorResponse file="github.com/datawire/apro/cmd/amb-sidecar/filters/handler/middleware/errors.go:82" FILTER=azure-ad.default MAIN=http REQUEST_ID=16837556474841453502 SUB=http-handler```
Logs of the ambassador pod do not show anything else.

**To Reproduce**
1. Deploy files
2. Go to https://localhost/backend/
3. Login

**Expected behavior**
Backend response

**Versions (please complete the following information):**
 - Ambassador: 1.6.2
 - Kubernetes environment: Docker Desktop
 - Version 1.16
