### ISSUE TITLE
Ambassador seem to be ignoring add_response_headers attribute in Module but acknowledging it in Mapping 

### ISSUE THREAD

**Issue by so-sdhawan** [emissary-ingress/emissary#2909]
**Describe the bug**
When we add add_response_headers in a Mapping we see the added headers in response, but no headers are there in response when we add add_response_headers to Module

**To Reproduce**
1. Add add_response_headers attribute to Module
2. See the response of any API request passing through ambassador

**Expected behavior**
add_response_headers in Module should add the specified response headers to response of all API calls passing through ambassador

**Versions (please complete the following information):**
 - Ambassador: 1.3.2
 - Kubernetes environment: Azure
 - Version: 1.15.10

**Additional context**
https://www.getambassador.io/docs/latest/topics/using/headers/add_response_headers/

**Comment by kflynn** [comment]
Can you paste your `ambassador` `Module` that isn't working?

**Comment by so-sdhawan** [comment]
```
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ***
spec:
  ambassador_id: ***
  config:
    use_ambassador_namespace_for_service_resolution: true
    use_remote_address: true
    envoy_log_type: json
    gzip:
      enabled: true
    cors:
      origins: ***
      headers: ***
      methods: ***
      credentials: ***
    defaults:
      httpmapping:
        add_response_headers:
          Expires: "Sat, 01 Jan 2000 00:00:00 GMT"
          Pragma: no-cache
          Cache-control: no-store
    lua_scripts: |//we've also added lua scripts for adding response headers
```
