### ISSUE TITLE
TLSContext: putting in a value for both `hosts` and `sni` causes Ambassador to crash (envoy is unable to reconfigure)

### ISSUE THREAD

**Issue by cakuros** [emissary-ingress/emissary#2921]
## Background/Summary

Specifying both `sni` and `hosts` in a `TLSContext` results in Envoy not being able to validate its config and results in an Ambassador crash.  "could not validate the envoy configuration above after 5 retries, failed with error 
[2020-08-10 19:47:26.137][215][critical][main] [source/server/config_validation/server.cc:59] error initializing configuration '/ambassador/snapshots/econf-tmp.json': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[2].listener_filters[0]) config: Cannot find field.) has unknown fields"

## Issue/Request

Ambassador should reject this config via both `kubeapi` and internally.  Additionally, some clarification on what `TLSContext` can and can't do when both terminating and reoriginating TLS would be good as well.

## Replicator
 - Ambassador: 1.6.2 via Helm
 - Kubernetes environment: GKE 1.17

1. Install AES
2. Create `TLSContext`
  ```yaml
  ---
  apiVersion: getambassador.io/v2
  kind: TLSContext
  metadata:
    name: test-context-origin
  spec:
    ambassador_id: default
    hosts:
    - application.com
    sni: application.com
    secret: fallback-self-signed-cert.ambassador
    secret_namespacing: true
  ```
3.  `kubectl rollout restart -n ambassador ambassador`
