### ISSUE TITLE
Support global and per-filterpolicy configurations in plugin filters

### ISSUE THREAD

**Issue by yanickbelanger** [emissary-ingress/emissary#2932]
**Please describe your use case / problem.**
Current plugin filters have no way to receive configurations. There are workarounds for global configurations (mounting a configmap, which has many drawbacks), but no way to have arguments/configurations per FilterPolicy. That reduces greatly the usefulness of plugin filters.

An example of use-case: in the context of user auth, we'd like to develop a `group-authorization-filter` that does the following: check if a JWT tokens with a specific group/role claims contains a specific group, and return a 401 or a redirection otherwise. That would enable us to easily authorize users of a specific group to access the internal app, without changing the code of the said app.

There are multiple use-cases where parameterization is required.

**Describe the solution you'd like**
Ambassador should provide a way to pass configurations/arguments to plugin filters, per Filter, and per FilterPolicy (that may override the global configurations). For example:

Per filter:
```
[...]
spec:
  Plugin:
    name: group-authorization-filter
    arguments:
      - name: group-claims-key
         value: roles
[...]
```

Per filter policy:
```
spec:
  rules:
    - host: blah.domain.com
      path: '*'
      filters:
        - name: group-authorization-filter
          arguments:
            - name: authorized-groups
              value: admin,owner,manager
```

Not sure how the plugin would consume the config, maybe as a context passed in the `func PluginMain(w http.ResponseWriter, r *http.Request)`.

**Describe alternatives you've considered**
Without this, we have to duplicate our plugin filters, hardcoding the config in the code. But that is cumbersome, doesn't scale well and sometimes is just not a solution.
