### ISSUE TITLE
Add watch on volumes for TLSContext

### ISSUE THREAD

**Issue by cakuros** [emissary-ingress/emissary#2936]
## Background/Summary

The `TLSContext` allows for specifying the cert-chain, the ca-cert-chain, and the key for TLS.  It only does this, however, when it is first initialized and does not update when the volumes change.  This is most evident with Istio's worker certificate rotation, where the `/etc/istio-certs` volume is updated, but the `TLSContext` is not.

## Issue/Request

`TLSContext` needs to update whenever the volumes it's pointing at are changed.

## Replicator

Kubernetes Cluster: Kubeception 1.17
Ambassador Version: 1.6.2 via Helm
1. Follow the [Istio how-to](https://www.getambassador.io/docs/latest/howtos/istio/) (excluding Prometheus and Distributed Tracing), but in the environment variables of the `istio-proxy` container, add
  ```
  - name: SECRET_TTL
    value: "0h5m0s"
  ```

1. wait 5 mins to see `2020-08-24T16:13:24.532920Z     info    sds     resource:default pushed key/cert pair to proxy` in `kubectl logs -n ambassador {{AMBASSADOR_POD}} -c istio-proxy`.

1. try to get to a backend service in the mesh:
`curl -v https://{{AMBASSADOR_HOST}}/backend/`
```
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Mon, 24 Aug 2020 16:14:35 GMT
< server: envoy
< 
* Connection #0 to host {{AMBASSADOR_HOST}} left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure* Closing connection 0
```

1. Restart the pod `kubectl rollout restart deploy -n ambassador ambassador`

1. Try again `curl -v https://{{AMBASSADOR_HOST}}/backend/`
```
< HTTP/1.1 200 OK
< content-type: application/json
< date: Mon, 24 Aug 2020 17:05:58 GMT
< content-length: 168
< x-envoy-upstream-service-time: 4
< server: envoy
< x-envoy-decorator-operation: quote.default.svc.cluster.local:80/*
< 
{
    "server": "quintessential-passionfruit-t11jxcdt",
    "quote": "A principal idea is omnipresent, much like candy.",
    "time": "2020-08-24T17:05:58.616336259Z"
* Connection #0 to host {{AMBASSADOR_HOST}} left intact
}* Closing connection 0
```

See also #2692 and #2587

**Comment by nicolasbelanger** [comment]
FYI, so far, I've tested 1m and 5m rotation without downtime.

@cakuros About the 24h rotation and your recent slack comment:
```
Hi @nicolasbelanger, We did some testing by trying to accelerate the cert rotation to 1 hour, which appears to have worked (as described here: https://www.getambassador.io/docs/latest/howtos/istio/#how-to-test-istio-certificate-rotation), but are in the process of testing the 24 hour case which it's possible has a different behavior from what we were expecting.
```
 why would the behaviour be any different?

**Comment by puneetloya** [comment]
I have pingdom alert set for the ambassador mapped endpoints. 
I have set "SECRET_TTL: 1h", in between it has down times for about a minute. Its like the delta time before the tls context updates with the latest cert I think.

**Comment by anyname2** [comment]
I am facing the same issue. The certificate is renewed by Istio, but is not picked up by Ambassador.

- Kubernetes 1.18
- Istio 1.7.3
- Ambassador 1.8.1

I have tried setting `SECRET_TTL` to 5m and 24h (default), both fail until ambassador is restarted.

By default Istio rotates certificates at half-time, but at most once every 5 minutes (all configurable).

- With TTL of 24h the certificates are rotated every 12h but are valid for 24h. (app becomes unavailable after 24h)
- With TTL of 5m, certificates are rotated every 5min and are valid for 5 min. (app becomes unavailable after 5min)

**Comment by valeneiko** [comment]
I am not sure - it's been a while. This was one of the reasons we have switched to using Istio Ingress Gateway, so I won't be of much help with this. But we had Istio and Ambassador working togehter for a while so I think it was solved.

Here is the diff I have found from that time, that might have solved the problem:
```diff
diff --git a/Deployment.yaml b/Deployment.yaml
index 87fc1a3..5f908cd 100644
--- a/Deployment.yaml
+++ b/Deployment.yaml
@@ -45,6 +45,8 @@ spec:
           value: "1"
         - name: AMBASSADOR_DISABLE_FEATURES
           value: "true"
+        - name: AMBASSADOR_ISTIO_SECRET_DIR
+          value: /etc/istio-certs
         image: docker.io/datawire/ambassador:1.10.0
         livenessProbe:
           httpGet:
diff --git a/TlsContext.yaml b/TlsContext.yaml
index b4396a2..a868a29 100644
--- a/TlsContext.yaml
+++ b/TlsContext.yaml
@@ -6,6 +6,4 @@ metadata:
 spec:
   alpn_protocols: istio
   ambassador_id: default
-  cacert_chain_file: /etc/istio-certs/root-cert.pem
-  cert_chain_file: /etc/istio-certs/cert-chain.pem
-  private_key_file: /etc/istio-certs/key.pem
+  secret: istio-certs
```

<details>
<summary>Here is my Deployment for Ambassador that seemed to have worked:</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: getambassador.io
    service: ambassador
  name: ambassador
  namespace: ambassador-private
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      service: ambassador
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-certs
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium": "Memory"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/includeOutboundIPRanges: ""
      labels:
        service: ambassador
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                service: ambassador
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMBASSADOR_ID
          value: default
        - name: AMBASSADOR_ENVOY_BASE_ID
          value: "1"
        - name: AMBASSADOR_DISABLE_FEATURES
          value: "true"
        - name: AMBASSADOR_ISTIO_SECRET_DIR
          value: /etc/istio-certs
        image: docker.io/datawire/ambassador:1.13.5
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        name: ambassador
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 8877
          name: admin
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: 600m
            memory: 800Mi
          requests:
            cpu: 300m
            memory: 450Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /ambassador
          name: ambassador
        - mountPath: /tmp
          name: tmp
        - mountPath: /tmp/ambassador-pod-info
          name: ambassador-pod-info
        - mountPath: /etc/istio-certs
          name: istio-certs
      restartPolicy: Always
      securityContext:
        fsGroup: 1337
        runAsGroup: 1337
        runAsUser: 1337
      serviceAccountName: ambassador
      volumes:
      - emptyDir: {}
        name: ambassador
      - emptyDir: {}
        name: tmp
      - emptyDir:
          medium: Memory
        name: istio-certs
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
        name: ambassador-pod-info
```
</details>

<details>
<summary>And the TLSContext:</summary>

```yaml
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: istio-upstream
  namespace: ambassador-private
spec:
  alpn_protocols: istio
  ambassador_id: default
  secret: istio-certs
```
</details>

**Comment by Arttii** [comment]
Thanks for the response! I tried that as well, but the istio-certs secret never seems to get created by ambassador.

**Comment by valeneiko** [comment]
I don't think `istio-certs` secret is created (not sure), it's just a trick we use to make Ambassador work, but in reality it's just files injected by an Istio Sidecar.

If you look at the full `deployment.yaml` in the previous comment. This pod annotation for injecting istio sidecar is pretty important:
```yaml
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            OUTPUT_CERTS: /etc/istio-certs
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium": "Memory"}}]'
        sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
        traffic.sidecar.istio.io/includeInboundPorts: ""
        traffic.sidecar.istio.io/includeOutboundIPRanges: ""
```

And we mount this `istio-certs` volume into Ambassador:
```yaml
        volumeMounts:
        ...
        - mountPath: /etc/istio-certs
          name: istio-certs
```

And also Ambassador might need to run as `1337` to be able to access the files created by Istio (at least with distroless Istio images that we are using, not sure about the other ones):
```yaml
      securityContext:
        fsGroup: 1337
        runAsGroup: 1337
        runAsUser: 1337
```
