### ISSUE TITLE
grpc & grpc-web in one mapping with host

### ISSUE THREAD

**Issue by jackielii** [emissary-ingress/emissary#2939]
**Describe the bug**

I want to proxy grpc & grpc-web through one port with host mapping

**To Reproduce**
1. create mapping like so:

```
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  df-catalog
  namespace: df
spec:
  grpc: true
  host: df.meera.tech
  prefix: /tes.df
  rewrite: /tes.df
  service: df:9111
```

2. access df.meera.tech with grpc-web protocol works

3. access df.meera.tech with grpc fails with method not defined which means it didn't match this mapping

**Expected behavior**

access grpc works.

**Versions (please complete the following information):**
 - Ambassador: [e.g. 1.6.2]
 - Kubernetes environment: microk8s enable ambassador
 - Version [e.g. v1.18.8-33+c9c9e3f85f05f9]

**Additional context**
the effective envoy match is:

```
              - match:
                  case_sensitive: true
                  headers:
                  - exact_match: df.meera.tech
                    name: ":authority"
                  - exact_match: https
                    name: x-forwarded-proto
                  prefix: "/tes.df"
                  runtime_fraction:
                    default_value:
                      denominator: HUNDRED
                      numerator: 100
                    runtime_key: routing.traffic_shift.cluster_df_df_9111_df
                route:
                  cluster: cluster_df_df_9111_df
                  prefix_rewrite: "/tes.df"
                  priority: 
                  timeout: 3.000s
```
