### ISSUE TITLE
devportal is not able to scrape API documentations

### ISSUE THREAD

**Issue by chris-ng-scmp** [emissary-ingress/emissary#2956]
**Describe the bug**

My AES installation with a Mapping as following, the API accessible via the host `masked.abc` with the prefix `masked.abc`

Also the API documentation accessible via `https://masked.abc/.ambassador-internal/openapi-docs` too

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: uat-app-cwh-assets-v2
spec:
  ambassador_id: ambassador-aes-uat
  host: masked.abc
  method: GET|PUT|POST|DELETE|PATCH|OPTIONS
  method_regex: true
  prefix: /nexus-news-items/v2/
  retry_policy:
    num_retries: 5
    retry_on: 5xx
  service: uat-app-cwh-assets-v2
  timeout_ms: 120000
```

Meanwhile, the pod of the ambassador deployment returning following 404 error related to the scrapping log 
```
1961:time="2020-09-01 04:10:03" level=error msg="HTTP error 404 from https://127.0.0.1:8443/nexus-news-items/v2/.ambassador-internal/openapi-docs" func=github.com/datawire/apro/cmd/amb-sidecar/devportal/server.HTTPGet file="github.com/datawire/apro/cmd/amb-sidecar/devportal/server/fetcher.go:202" subsystem=fetcher url="https://127.0.0.1:8443/nexus-news-items/v2/.ambassador-internal/openapi-docs"
1990:{"start_time": "2020-09-01T04:10:03.426Z","method": "GET","path": "/nexus-news-items/v2/.ambassador-internal/openapi-docs","protocol": "HTTP/1.1","response_code": "404","response_flags": "UAEX","bytes_received": "0","bytes_sent": "9","duration": "0","upstream_service_time": "-","x_forwarded_for": "10.200.4.105","user_agent": "Go-http-client/1.1","correlation_id": "-","authority": "uat-api.scmp.work","upstream_host": "-","upstream_cluster": "-","upstream_local_address": "-","downstream_local_address": "127.0.0.1:8443","downstream_remote_address": "127.0.0.1:42114","requested_server_name": "-","istio_policy_status": "-","upstream_transport_failure_reason": "-"}
```

So I guess the 404 caused by requesting the endpoint without `host` header `host: masked.abc` to match with mapping above, so I created another mapping without host property as following

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: uat-app-cwh-assets-v2-local
spec:
  ambassador_id: ambassador-aes-uat
  method: GET|PUT|POST|DELETE|PATCH|OPTIONS
  method_regex: true
  prefix: /nexus-news-items/v2-local/
  retry_policy:
    num_retries: 5
    retry_on: 5xx
  service: uat-app-cwh-assets-v2
  timeout_ms: 120000
```

With the mapping, I can get the API document via

```
kubectl exec -it deploy/ambassador-aes-uat -- curl -L "https://127.0.0.1:8443/nexus-news-items/v2-local/.ambassador-internal/openapi-docs" -k
```

But this is very strange the fetcher.go still getting 404 with the same URL under the pod...meanwhile the pod logged code 200 for my above curl command

```
2031:time="2020-09-01 03:55:03" level=error msg="HTTP error 404 from https://127.0.0.1:8443/nexus-news-items/v2-local/.ambassador-internal/openapi-docs" func=github.com/datawire/apro/cmd/amb-sidecar/devportal/server.HTTPGet file="github.com/datawire/apro/cmd/amb-sidecar/devportal/server/fetcher.go:202" subsystem=fetcher url="https://127.0.0.1:8443/nexus-news-items/v2-local/.ambassador-internal/openapi-docs"
2068:{"start_time": "2020-09-01T03:55:03.512Z","method": "GET","path": "/nexus-news-items/v2-local/.ambassador-internal/openapi-docs","protocol": "HTTP/1.1","response_code": "404","response_flags": "UAEX","bytes_received": "0","bytes_sent": "9","duration": "2","upstream_service_time": "-","x_forwarded_for": "10.200.4.105","user_agent": "Go-http-client/1.1","correlation_id": "-","authority": "127.0.0.1:8443","upstream_host": "-","upstream_cluster": "-","upstream_local_address": "-","downstream_local_address": "127.0.0.1:8443","downstream_remote_address": "127.0.0.1:42440","requested_server_name": "-","istio_policy_status": "-","upstream_transport_failure_reason": "-"}
2111:{"start_time": "2020-09-01T03:55:24.620Z","method": "GET","path": "/nexus-news-items/v2-local/.ambassador-internal/openapi-docs","protocol": "HTTP/1.1","response_code": "200","response_flags": "-","bytes_received": "0","bytes_sent": "87932","duration": "3","upstream_service_time": "1","x_forwarded_for": "10.200.4.105","user_agent": "curl/7.66.0","correlation_id": "-","authority": "127.0.0.1:8443","upstream_host": "10.200.132.179:80","upstream_cluster": "cluster_uat_app_cwh_assets_v2_technology_newsroom_system","upstream_local_address": "10.200.4.105:34856","downstream_local_address": "127.0.0.1:8443","downstream_remote_address": "127.0.0.1:43890","requested_server_name": "-","istio_policy_status": "-","upstream_transport_failure_reason": "-"}
```

**Expected behavior**
devportal backend should able to curl the API doucment with the host header or should able to scrape it via `127.0.0.1:8443` (at the meantime curl is working inside the pod)

**Versions (please complete the following information):**
 - Ambassador: 1.7.0
 - Kubernetes environment: Alicloud 
 - Version: 1.16
