### ISSUE TITLE
TCPMapping traffic not behaving as expected

### ISSUE THREAD

**Issue by xlanor** [emissary-ingress/emissary#3003]
I'm following the documentation provided [here](https://www.getambassador.io/docs/latest/topics/using/tcpmappings/), but I'm still not able to get this to work correctly.

Ambassador version: `v1.7.0`
Kubernetes environment: `EC2, deployed via Rancher Kubernetes Engine`
Kubernetes version: `1.18.6`

I've configured Ambassador as such 
```
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: ambassador
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <ARN CERT ID>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: https
    port: 443
    targetPort: 8080
  selector:
    service: ambassador
```

I've checked and the port is open in the provisioned AWS ELB.

```
---
apiVersion: getambassador.io/v2
kind: TCPMapping
metadata:
  name: logstash-tcp-mapping
  namespace: ambassador
spec:
  port: 5000
  service: logstash.monitoring:5000
```

From within the ambassador pod, I was able to ensure that ambassador was listening on the port
```
bash-5.0$ netstat -anp | grep 5000
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      113/envoy
```

Looking at `envoy/envoy.json`, I do see a mapping avaliable for port 5000
```
  {
                "address": {
                    "socket_address": {
                        "address": "0.0.0.0",
                        "port_value": 5000,
                        "protocol": "TCP"
                    }
                },
                "filter_chains": [
                    {
                        "filters": [
                            {
                                "config": {
                                    "stat_prefix": "ingress_tcp_5000",
                                    "weighted_clusters": {
                                        "clusters": [
                                            {
                                                "name": "cluster_logstash_monitoring_5000_ambassador",
                                                "weight": 100
                                            }
                                        ]
                                    }
                                },
                                "name": "envoy.tcp_proxy"
                            }
                        ]
                    }
                ],
                "name": "listener-0.0.0.0-5000"
            }
```
However, even though I'm able to telnet to the port - the data never arrives at the logstash service. 
When executing `kubectl logs` on the ambassador pod, even when the request is made, I do not see any logs.
I've double checked the logstash service by doing a kubectl proxy, and I was able to send logs to the logstash pods.

Is there something I am missing from the documentation?
