### ISSUE TITLE
AES console page does not load when auth-filter and FilterPolicy set

### ISSUE THREAD

**Issue by vsimon** [emissary-ingress/emissary#3032]
**Describe the bug**

The AES console page not load if you set an auth-filter and FilterPolicy

Example of a Filter Policy:

```
apiVersion: getambassador.io/v2
kind: FilterPolicy
metadata:
  name: auth-policy
  namespace: ambassador
spec:
  rules:
  - filters:
    - arguments:
        scopes:
        - openid
      name: auth-filter
    host: <hostname>
    path: '*'
```

**To Reproduce**
1. Attempt to access the console page url
2. Ambassador asks to auth
3. Do auth
4. Ambassador continues to the usual console page asking you to `edgectl login...`
5. Do `edgectl login ...`
6. Ambassador still shows a console page asking you to `edgectl login...`

**Expected behavior**
Ambassador goes into the AES console page.

**Versions (please complete the following information):**
 - Ambassador: 1.8.1
 - Kubernetes environment- EKS
 - Version 1.17

**Additional context**
