### ISSUE TITLE
ACME chalange fails with 403 error 

### ISSUE THREAD

**Issue by igoratencompass** [emissary-ingress/emissary#3042]
**Describe the bug**

I have Abassador AES with our own authentication service. I face a problem where Ambassador is asking for authentication for the `/.well-known/acme-challenge/` ACME challenge prefix which fails with `403` error in `Host` description:

```
acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://my.domain.com/.well-known/acme-challenge/OZt4pqvq4mALT8ZU5kcGri0sE
```
and can see this in the ambassador pod log:

```
2020/10/30 04:41:10 [INFO] Unable to deactivate the authorization: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/142931324
```

**Expected behavior**

Ambassador provisions TLS cert for my.domain.com from LE, the `/.well-known/` prefix to be excluded from the auth/autnz workflow.

**Versions (please complete the following information):**
 - Ambassador: aes v1.7.4
 - Kubernetes environment: Kops in AWS
 - Version: 1.18.10

**Additional context**

My `Host` definition:

```
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: my.domain.com
  namespace: ambassador
spec:
  hostname: "my.domain.com"
  acmeProvider:
    #authority: https://acme-v02.api.letsencrypt.org/directory
    authority: https://acme-staging-v02.api.letsencrypt.org/directory
    email: my@email.com
    privateKeySecret:
      name: tls-aes
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
```
Tried to bypass the authorization via Mapping:
```
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: acme-challenge
  namespace: ambassador
spec:
  prefix: /.well-known/acme-challenge/
  bypass_auth: true
  rewrite: ""
  host: my.domain.com
  service: 127.0.0.1:8080
```
to no avail.
