### ISSUE TITLE
Automatic renewal with HTTP-01 & Lets Encrypt not working

### ISSUE THREAD

**Issue by henrikengelbrink** [emissary-ingress/emissary#3070]
**Describe the bug**
We've configured Ambassador to issue certs from Lets Encrypt via the HTTP-01 challenge and I expected that these certs will be renewed automatically.

**To Reproduce**
- Install Ambassador in DigitalOcean Managed Kubernetes (DOKS) via Helm Chart
- Setup any deployment with service to receive traffic
- Configure `Host`, `TLSContext`, `Mapping`:

```yaml
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: api-example-de-host
spec:
  hostname: api.example.de
  acmeProvider:
    authority: 'https://acme-v02.api.letsencrypt.org/directory'
    email: henrik@example.de
  tlsSecret:
    name: api-example-de-tls
  requestPolicy:
    insecure:
      action: Redirect
      additionalPort: 8080
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: api-example-de-host-context
spec:
  hosts:
    - api.example.de
  secret: api-example-de-tls
  min_tls_version: v1.2
  cipher_suites:
    - "[TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]"
    - "[TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256]"
    - "[TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]"
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  api-example-de-mapping
spec:
  prefix: /
  host: api.example.de
  service: conversation-service.default:8081
  add_response_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  cors:
    origins: "*"
    methods: POST, GET, PUT, OPTIONS, PATCH, DELETE
    headers:
      - Content-Type
      - Authorization
    credentials: true
    max_age: "86400"

```

**Expected behavior**
Lets Encrypt certificates are valid for 90 days and I expected that Ambassador will renew them before they expire (Usually this is done after 60 days). My certificates will expires next week on Wednesday and I think the automatic renewal is not working at the moment.

**Versions (please complete the following information):**
 - Ambassador: Helm chart v.6.5.0, Image: 1.6.0
 - Kubernetes environment DigitalOcean Managed Kubernetes (DOKS)
 - Version 1.8.6.do.0
