### ISSUE TITLE
Can't add mapping name to logs with %ROUTE_NAME%

### ISSUE THREAD

**Issue by yoka791** [emissary-ingress/emissary#3145]
**Describe the bug**
We tried to use %ROUTE_NAME% parameter in the ambassador logging parameters (in envoy_log_format) and it didn't work despite the documentation here:
https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage.

**To Reproduce**
1. Create Ambassador module (inside k8s annotations):
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Module
      name: ambassador
      config:
        envoy_log_format: '"routeName":"%ROUTE_NAME%"'
      ---
```
2. Create mapping (inside k8s annotations):
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: cars_service_liveness_mapping
      prefix: /cars/health/live
      service: cars-svc:80
      rewrite: "/health/live"
      timeout_ms: 10000
      connect_timeout_ms: 10000
      bypass_auth: true
      ---
```

**Expected behavior**
The log that should be printed:
`"routeName":"cars_service_liveness_mapping"`

**Actual behavior**
The log that actually printed:
`"routeName":"-"`

**Versions (please complete the following information):**
 - Ambassador: 1.8.0
 - Kubernetes environment: EKS

**Additional context**
Note - we are using annotations for Ambassador configuration instead of CRDs.
