### ISSUE TITLE
TLS Context requires wildcard host

### ISSUE THREAD

**Issue by blhagadorn** [emissary-ingress/emissary#3171]
**Describe the bug**
Similar to this issue (the comments at the end): https://github.com/datawire/ambassador/issues/2252 
When setting up a gRPC client speaking to an upstream gRPC server, and using the upstream TLS configuration (as specified in the gRPC getting started guide: https://www.getambassador.io/docs/latest/howtos/grpc/), envoy  
configuration doesn't show the correct cluster.  When TLS Context is set to '*', things work correctly:
I would expect this to work:
```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: upstream
spec:
  alpn_protocols: h2
  ambassador_id:
  - "public"
  hosts:
  - 'grpc-example.example.com:443'
  secret: grpc-example-self-signed-cert
```
However, only this works:
```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: upstream
spec:
  alpn_protocols: h2
  ambassador_id:
  - "public"
  hosts:
  - '*'
  secret: grpc-example-self-signed-cert
```

**To Reproduce**
1. Create gRPC client and server with TLS Context specified
**Expected behavior**
That the first TLS Context works.

**Versions (please complete the following information):**
 - Ambassador: 1.8.1
 - Kubernetes environment : EKS
 - Version: 1.17

**Additional context**
The Diagnostics UI complains about this setup, even though it works (since the hosts don't match).
Maybe related, however we only have one TLS Context in the cluster: https://github.com/datawire/ambassador/issues/2403
