### ISSUE TITLE
Supporting AWS proxy protocol

### ISSUE THREAD

**Issue by shaneutt** [emissary-ingress/emissary#3300]
It would appear that in order to support proxy protocol integration with AWS using Ambassador one would need to create a `Module` configuration which will enable it in the Ambassador control plane:

```yaml
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  config:
    use_proxy_proto: true
```

And decorate the service with relevant annotations, this for classic ELB:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: kubeaddons
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
```

This all according to my review of your documentation:

* https://www.getambassador.io/docs/latest/topics/running/ambassador/#allow-proxy-protocol-use_proxy_proto
* https://www.getambassador.io/docs/pre-release/topics/running/ambassador-with-aws/#ambassador-edge-stack-on-aws

There may be more to it than that (I'll need to continue to review the documentation) but the purpose of this issue is **specific to the helm chart**:

I haven't seen any reference to the use of `proxy_proto` throughout the chart except for a single reference to a configuration override, so it seems you can do this by providing annotation overrides and configuration overrides in the values, but I don't see a higher level configuration available to enable proxy protocol on specific cloud providers.

The purpose of this issue is to request a high level configuration option for the chart to deploy a `proxy_protocol` ready and enabled service configuration, preferably something like this:

```shell
$ helm install --create-namespace --namespace ambassador --set cloudproviders.aws.proxyprotocol.enabled=true ambassador ambassador
```

Thank you!
