### ISSUE TITLE
Could not parse host

### ISSUE THREAD

**Issue by TLmaK0** [emissary-ingress/emissary#3341]
**Describe the bug**
Using a regex in host gives a warning `Could not parse host '^api(|\\.pre)\\.(domain1|domain2)\\.com$' in Mapping 'mymapping-service': using empty host" but the host mapping works as expected

**To Reproduce**
1. Create a mapping with a regex host `"^api(|\\.pre)\\.(domain1|domain2)\\.com$"`: 
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: erp-api
spec:
  host: "^api(|\\.pre)\\.(domain1|domain2)\\.com$"
  host_regex: true
  prefix: /api/
  rewrite: /api/
```
2. Get the ambassador logs: `kubectl logs -f -l service=ambassador -n ambassador`

**Expected behavior**
No warnigs in logs

**Versions (please complete the following information):**
 - Ambassador: quay.io/datawire/aes:1.12.2
 - Kubernetes environment: minikube
 - Version  v1.16.2

**Additional context**
```
time="2021-04-15 11:17:33" level=warning msg="Could not parse host '^api(|\\.pre)\\.(domain1|domain2)\\.com$' in Mapping 'myservice': using empty host" func=github.com/datawire/apro/cmd/amb-sidecar/devportal/server.NewMappingFromJSON file="github.com/datawire/apro/cmd/amb-sidecar/devportal/server/mappings.go:96" CMD=amb-sidecar PID=19 THREAD=/devportal_fetcher subsystem=fetcher
```
