### ISSUE TITLE
Unable to use v2 Mapping CRD as resources outside kubernetes context (in standalone docker)

### ISSUE THREAD

**Issue by ulrikjohansson** [emissary-ingress/emissary#3407]
**Describe the bug**
When using getambassador.io/v2 Mappings in a docker context (no cluster), ambassador complains that the mapping is missing a "name".
For "ambassador/v1" mappings everything works, but I want to be able to use the same mappings we have in our cluster in a standalone docker context for testing/dev purposes.

In order to get ambassador (1.13.4) running in docker I have to set both of these env vars:
* AMBASSADOR_NO_KUBEWATCH
* AMBASSADOR_LEGACY_MODE
The last one to stop ambassador from panic crashing on startup.
Is the legacy mode flag interfering with the reading of v2 Mappings somehow?

**To Reproduce**
1. Setup a docker container with ambassador running. Example docker-compose file
```yaml
services:
  ambassador:
    container_name: ambassador
    image: docker.io/datawire/ambassador:1.13.1
    ports:
      - 8080:8080
      - 8877:8877
    volumes:
      - ./config:/ambassador/ambassador-config
    environment:
      - AMBASSADOR_NO_KUBEWATCH=true
      - AMBASSADOR_LEGACY_MODE=true
```
2. Add a v2 Mapping
```
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  httpbin-mapping
spec:
  prefix: /httpbin/
  service: http://httpbin.org
```
3. Start ambassador w. docker-compose up -d
4. check logs: docker-compose logs ambassador
I get this error
```
error  ACResource: Mapping requires name ({'metadata': {'name': 'httpbin-mapping'}, 'spec': {'prefix': '/httpbin/', 'service': 'http://httpbin.org'}})
```

**Expected behavior**
I expected ambassador to be able to read valid Mapping CRDs

**Versions (please complete the following information):**
 - Ambassador: 1.13.4
 - Kubernetes environment: None (standalone docker)
