### ISSUE TITLE
Duplicate app.kubernetes.io/instance labels keys breaks kustomize

### ISSUE THREAD

**Issue by vikas027** [emissary-ingress/emissary#3471]
**Describe the bug**
There is a duplicate label key `app.kubernetes.io/instance: ambassador` in the `ambassador-agent` deployment which breaks kustomize.

**Remove the duplicate keys**
![2021-05-31_15-12-59](https://user-images.githubusercontent.com/6998650/120143264-22e4dc80-c223-11eb-8369-9fdf52fc6995.png)

**Comment by acookin** [comment]
Yes, it seems we template out a duplicate instance label when using helm as the deployment tool.
Helm and kubectl treat this as valid config, and since we don't officially support kustomize, this never came up.
#3486 should fix this and we'll get it out in the next helm release.

**Comment by acookin** [comment]
The fix for this went out in chart [6.7.11](https://github.com/emissary-ingress/emissary/releases/tag/chart-v6.7.11)

**Comment by vikas027** [comment]
Hey @acookin ,

This is the new emissary chart as well, again the fix is to just comment the line :)

```yaml
---
# Source: emissary-ingress/templates/ambassador-agent.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-emissary-ingress-agent
  namespace: ambassador
  labels:
    app.kubernetes.io/name: ambassador-emissary-ingress-agent
    # app.kubernetes.io/instance: ambassador
    app.kubernetes.io/part-of: ambassador
    helm.sh/chart: emissary-ingress-0.0.1
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Helm
    product: aes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ambassador-emissary-ingress-agent
      app.kubernetes.io/instance: ambassador
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ambassador-emissary-ingress-agent
        # app.kubernetes.io/instance: ambassador
        app.kubernetes.io/part-of: ambassador
        helm.sh/chart: emissary-ingress-0.0.1
        app.kubernetes.io/instance: ambassador
        product: aes
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: ambassador-emissary-ingress-agent
      containers:
      - name: agent
        image: docker.io/datawire/ambassador:1.13.3
        imagePullPolicy: IfNotPresent
        command: [ "agent" ]
        env:
        - name: AGENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AGENT_CONFIG_RESOURCE_NAME
          value: ambassador-emissary-ingress-agent-cloud-token
        - name: RPC_CONNECTION_ADDRESS
          value: https://app.getambassador.io/
        - name: AES_SNAPSHOT_URL
          value: "http://ambassador-emissary-ingress-admin.ambassador:8005/snapshot-external"
```
