### ISSUE TITLE
remove_response_headers doesn't work in module

### ISSUE THREAD

**Issue by cortopy** [emissary-ingress/emissary#3624]
**Describe the bug**
I'm following the docs in order to remove the `x-envoy-upstream-service-time` header from responses.

In a mapping, this works:

```yaml
kind: Mapping
metadata:
  name: my-mapping
spec:
...
  remove_response_headers:
    - x-envoy-upstream-service-time
```

but if I try to configure instead globally with a module like:

```yaml
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: global-config
spec:
  config:
    defaults:
      httpmapping:
        remove_response_headers:
          - x-envoy-upstream-service-time
```

the header is still present

**To Reproduce**
1. Create a module like in the docs with a defaults key
2. Test with `curl -I hhtps://hostname` and the `x-envoy-upstream-service-time` will be there

**Expected behavior**
headers get removed

**Versions (please complete the following information):**
 - Ambassador: 1.13.9
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]: rancher 
 - Version [e.g. 1.8.1]: 1.20
