### ISSUE TITLE
active health check with canary release support for multiple upstreams.

### ISSUE THREAD

**Issue by elvis-cai** [emissary-ingress/emissary#3761]
**Describe the bug**
Applogise if this is not the best place to describe my issue.
We are looking at using emissary as api gateway in our k8s cluster, the requreiment is:
-  when hitting ${AMBASSADOR_LB_ENDPOINT} with `/backend`, the request will go to two backend services according to `weight` we configured, it works perfectly, 
- if one of the backend service is unhealthy,  emissary will failover request to the healthy upstream only.

currently, can not find any doc on how to configure it, when one of upstreams is unhealthy, request will still be forwarded to it.
```
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.17.7</center>
</body>
</html>
banana
banana
banana
```

**To Reproduce**
apply the yaml file and test hitting `curl -Lk https://$AMBASSADOR_LB_ENDPOINT/backend/`.
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: banana-backend
spec:
  prefix: /backend/
  service: http://banana.internal.com
  host_rewrite: banana.internal.com
  weight: 50
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: apple-backend
spec:
  prefix: /backend/
  service: http://apple.internal.com
  host_rewrite: apple.internal.com
  weight: 50
```

**Expected behavior**
when apple is scaled down, request will go to banana only.

**Versions (please complete the following information):**
 - Ambassador:  Ambassador 1.14.1-dev.13085+g2a572423e
 - Kubernetes environment: GKE 
 - Version: v1.19.10-gke.1600

**Additional context**
install with helm chart version 6.9.1
```# Add the Repo:
helm repo add datawire https://www.getambassador.io
 
helm install ambassador datawire/ambassador --set enableAES=false && \
kubectl wait --for condition=available --timeout=90s deploy -lproduct=aes
```
