### ISSUE TITLE
docs for isntalling via K8s YAML are incorrect

### ISSUE THREAD

**Issue by irl-segfault** [emissary-ingress/emissary#3855]
the [instructions to install emissary-ingress via k8s yaml](https://www.getambassador.io/docs/emissary/latest/topics/install/yaml-install/) are

```
kubectl apply -f https://www.getambassador.io/yaml/ambassador/ambassador-crds.yaml && \
kubectl apply -f https://www.getambassador.io/yaml/ambassador/ambassador-rbac.yaml && \
kubectl apply -f - <<EOF
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: ambassador 
spec:
  type: LoadBalancer 
  externalTrafficPolicy: Local 
  ports:
  - port: 80 
    targetPort: 8080
  selector: 
    service: ambassador 
EOF
```

This does not install any emissary ingress deployments/pods.  In general I've noticed this kind of issue pervasive throughout most docs on Emissary/Ambassador that I've encountered.
