### ISSUE TITLE
emissary-ingress 2.0.4 not creating envoy listeners

### ISSUE THREAD

**Issue by vjdhama** [emissary-ingress/emissary#3894]
**Describe the bug**
On installing `emissary-ingress` through Helm chart(version `7.1.9`), which installs emissary-ingress versioned `2.0.4`, the listeners are not getting created on envoy.

**To Reproduce**
1. Install emissary-ingress using Helm chart(version `7.1.9`)
2. Using following Helm values override : 

  ```
  values:
    service:
      type: LoadBalancer
      externalTrafficPolicy: Cluster
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    agent:
      enabled: false
    crds:
      enabled: true
      create: true
    createDefaultListeners: true
  ```

**Expected behavior**
Two listeners on Envoys to be created.

**Versions (please complete the following information):**
 - Ambassador: [2.0.4]
 - Kubernetes environment [EKS]
 - Version [1.19]

**Additional context**
The default listeners are getting created as CRD objects.

```
➜ kubectl get listeners.getambassador.io -A
NAMESPACE        NAME                              PORT   PROTOCOL   STACK   STATSPREFIX   SECURITY   L7DEPTH
ambassador     emissary-ingress-http-listener    8080   HTTP                             XFP
ambassador     emissary-ingress-https-listener   8443   HTTPS                            XFP
```

The generated Envoy config file.

```
➜ kubectl exec -it emissary-ingress-74cb74f84b-5h2kr -- cat envoy/envoy.json
{
  "@type": "/envoy.config.bootstrap.v3.Bootstrap",
  "layered_runtime": {
    "layers": [
      {
        "name": "static_layer",
        "static_layer": {
          "envoy.reloadable_features.enable_deprecated_v2_api": true,
          "re2.max_program_size.error_level": 200
        }
      }
    ]
  },
  "static_resources": {
    "clusters": [
      {
        "alt_stat_name": "127_0_0_1_8877",
        "connect_timeout": "3.000s",
        "dns_lookup_family": "V4_ONLY",
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
          "cluster_name": "cluster_127_0_0_1_8877_infrastructure",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "127.0.0.1",
                        "port_value": 8877,
                        "protocol": "TCP"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        "name": "cluster_127_0_0_1_8877_infrastructure",
        "type": "STRICT_DNS"
      }
    ],
    "listeners": []
  }
}
```
