### ISSUE TITLE
Deploying Emissary Ingress with ArgoCD and Helm causes clobbering on ClusterRole rules 

### ISSUE THREAD

**Issue by Selin-PDQ** [emissary-ingress/emissary#3933]
**Describe the bug**
Deploying Emissary Ingress with ArgoCD and Helm causes clobbering on ClusterRole rules. There's some entity outside of the helm chart that's editing ClusterRoles to provision the rules. Ideally these rules should be defined in the helm deployment instead of being seeded with rules post installation.

**To Reproduce**
1. Deploy this application to a cluster with ArgoCD installed in it
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ambassador
  namespace: argocd
spec:
  destination:
    name: prod
    namespace: ambassador
  source:
    repoURL: "https://app.getambassador.io"
    targetRevision: 7.1.10
    chart: edge-stack
    helm:
      values: ""
      valueFiles: []
      parameters:
      releaseName: ambassador
  project: core-utilities
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

```
2. Enable self-healing and autosync
3. View the application in ArgoCD's UI
4. The application will go into a loop with ArgoCD editing the ClusterRoles to not include the rules, and Emissary Ingress will edit the rules back in.

**Expected behavior**
A default installation of Emissary Ingress without any special parameters should be deployable in ArgoCD without whitelisting any paths.

**Versions (please complete the following information):**
 - Ambassador: 7.1.10
 - Kubernetes environment: GKE
 - Version 1.21

**Additional context**
You can whitelist this path in ArgoCD with an `ignoreDifferences` rule like so:
```
spec:
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: ambassador-agent
      jsonPointers:
        - /rules
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: ambassador
      jsonPointers:
        - /rules
```
