### ISSUE TITLE
Envoy isn't listening on 8443

### ISSUE THREAD

**Issue by rdeusser** [emissary-ingress/emissary#3943]
**Describe the bug**
Envoy isn't listening on 8443 after creating a `Host` CR:

```
bash-5.0# netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9696          0.0.0.0:*               LISTEN      1/busyambassador
tcp        0      0 127.0.0.1:8001          0.0.0.0:*               LISTEN      34/envoy
tcp        0      0 127.0.0.1:8003          0.0.0.0:*               LISTEN      1/busyambassador
tcp        0      0 0.0.0.0:8004            0.0.0.0:*               LISTEN      17/python
tcp        0      0 0.0.0.0:8877            0.0.0.0:*               LISTEN      1/busyambassador
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      34/envoy
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      34/envoy
tcp        0      0 :::8005                 :::*                    LISTEN      1/busyambassador
```

Host yaml:

```yaml
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert
  selector:
    matchLabels:
      hostname: wildcard-host
```

**To Reproduce**
1. Deploy Ambassador 1.14.1 to Docker for Desktop
2. Apply the Host yaml I pasted above
3. Shell into the Ambassador container
4. Run `netstat -tulnp` and look to see if Envoy is listening on port 8443

**Expected behavior**
I expect to see Envoy listening on port 8443 when a `Host` or `TLSContext` is applied.

**Versions (please complete the following information):**
 - Ambassador: 1.14.1
 - Kubernetes environment: Docker for Desktop (mac)
 - Version: 3.6.0

**Additional context**
None at the moment.
