### ISSUE TITLE
Missing entry in the envoy.json configuaration when TCPMapping is used and TLS origination is enabled

### ISSUE THREAD

**Issue by bemipefe** [emissary-ingress/emissary#3944]
**### Description:**

When the communication between a client and the application running on the pod needs to be encrypted end-to-end you need to enable both TLS termination and TLS origination. In my case I need TLS origination but no specific certificate need to be provided to the application to authenticate. Additionally the application use a protocol different than HTTP (but in some cases also HTTP is used)

In order to do that you need to create a TLSContext and TCPMapping objects. However when the `/envoy/envoy.json` file is generated in the ambassador pod, there is one line missing which prevent the communication from working correctly.

This is a snippet of the **envoy.json** generated with ambassador `1.14.2 `
```

            "filter_chain_match": {
              "server_names": [
                "my.app.on.cloud"
              ]
            },
            "filters": [
              {
                "name": "envoy.filters.network.tcp_proxy",
                "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",

```
Note that "**my.app.on.cloud**" is the FQDN used to reach the application from internet.
The **envoy.json** generated with ambassador `2.0.4` is almost the same but one line: `"transport_protocol": "tls"`
 
```
            "filter_chain_match": {
              "server_names": [
                "my.app.on.cloud"
              ],
              "transport_protocol": "tls"
            },
            "filters": [
              {
                "name": "envoy.filters.network.tcp_proxy",
                "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",

```

Without this additional line I can only validate the handshake with the following command:

`openssl s_client -connect X.X.X.X:443 -servername "my.app.on.cloud"
`

The correct certificate is picked up and the handshake is successful however any attempt to reach the application is failing and the ambassador log reports errors like this:

`"- - HTTP/1.1" 400 DPE 0 11 0 - "-" "-" "-" "-" "-"`

It seems like the protocol is wrongly detected as HTTP.
However even if I specify in the TCPMapping the HTTPS application service port and I run this command:

` curl -Lki -H "Host: my.app.on.cloud" https://X.X.X.X/myapp`

I still get an error:

`GET /myapp HTTP/1.1" 404 NR 0 0 0 - "10.72.1.1" "curl/7.55.1" "xxx" "my.app.on.cloud" "-"`

**### Workaround:**

To let it working I performed these steps:

1) Enter the ambassador pod (the replica is set to 1 so there is only one pod)
2) Manually edit the file envoy.json and add the missing line
3) Restart the envoy process with this command: `kill $(pidof envoy) && envoy -c /ambassador/bootstrap-ads.json --base-id 0 --drain-time-s 600 -l error --bootstrap-version 3`

This allow both HTTP and non-HTTP communications to work correctly.
However once the pod restart the edited configuration is lost and the previous one is restored.

Is there a way to force the edited version permanently ?

**### Steps to reproduce the behavior:**

1) Deploy ambassador 1.14.2
2) Deploy and application myapp which only support TLS encrypted traffic on its port
3) Create the following objects:
```

apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: ambassador-host-tls
  namespace: myns
spec:
  ambassador_id: [ "ambassador1" ]
  hosts:
   - my.app.on.cloud
  secret: ambassador-tls
  min_tls_version: v1.2
---
apiVersion: getambassador.io/v2
kind: TCPMapping
metadata:
  name:  ambassador-mapping
  namespace: myns
  spec:
  ambassador_id: [ "ambassador1" ]
  port: 8443
  host: my.app.on.cloud
  host_regex: false
  service: myapp-test-deploy-service:8443
  tls: true

```
****

**### Versions:**

 - Ambassador: 1.14.2
 - Kubernetes environment: Google Kubernetes Engine
 - Version : not sure how I can figure out the GKE version

**NOTE:** I can't use ambassador 2.0.4 because there are already other 1.x.x ambassador versions deployed in the cluster and as stated in the documentation the CRD are incompatible with each other and can't be created for both versions.
