### ISSUE TITLE
Rate Limit won't work if domain is not set to "ambassador"

### ISSUE THREAD

**Issue by tobernguyen** [emissary-ingress/emissary#3958]
**Describe the bug**
The Rate Limit won't work if the domain is different than `ambassador

**To Reproduce**
Consider following configurations
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-longn-sandbox
spec:
  hostname: redacted
  acmeProvider:
    email: redacted
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  quote-mapping
spec:
  hostname: redacted
  prefix: /
  service: quote.default
  cors:
    origins:
    - "https://myxml.in"
  labels:
    api:
      - request_label_group:
        - remote_address:
            key: remote_address # Create label key from Client IP Address
---
apiVersion: getambassador.io/v3alpha1
kind: RateLimit
metadata:
  name: api-rate-limit
spec:
  domain: api
  limits:
  - pattern:
    - remote_address: "*"
    rate: 5
    unit: second
```
The rate limit won't work at all. I can send as many request as I want.

But if I change the domain to `ambassador`, it works as expected
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-longn-sandbox
spec:
  hostname: redacted
  acmeProvider:
    email: redacted
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  quote-mapping
spec:
  hostname: redacted
  prefix: /
  service: quote.default
  cors:
    origins:
    - "https://myxml.in"
  labels:
    ambassador:
      - request_label_group:
        - remote_address:
            key: remote_address # Create label key from Client IP Address
---
apiVersion: getambassador.io/v3alpha1
kind: RateLimit
metadata:
  name: api-rate-limit
spec:
  domain: ambassador
  limits:
  - pattern:
    - remote_address: "*"
    rate: 5
    unit: second
```

**Expected behavior**
It should work with the value of domain different than ambassador.

**Versions (please complete the following information):**
 - Ambassador: 2.0.5 (Edge Stack)
 - Kubernetes environment EKS + NLB
 - Version 1.18

**Additional context**
