### ISSUE TITLE
Method-based Routing not work

### ISSUE THREAD

**Issue by lou-lan** [emissary-ingress/emissary#4011]
**Describe the bug**
Method-based Routing not work.

**To Reproduce**
Apply this yaml context:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ambassdor-method-get
  labels:
    app: test-ambassdor-method-get
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ambassdor-method-get
  template:
    metadata:
      labels:
        app: test-ambassdor-method-get
    spec:
      containers:
      - name: app
        image: registry.cn-shanghai.aliyuncs.com/loulan-public/ambassdor-method:v2
        ports:
        - containerPort: 8080
        command: ["/workspace/app"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ambassdor-method-post
  labels:
    app: test-ambassdor-method-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ambassdor-method-post
  template:
    metadata:
      labels:
        app: test-ambassdor-method-post
    spec:
      containers:
      - name: app
        image: registry.cn-shanghai.aliyuncs.com/loulan-public/ambassdor-method:v2
        ports:
        - containerPort: 8080
        command: ["/workspace/app"]
---
apiVersion: v1
kind: Service
metadata:
  name: test-ambassdor-method-get
spec:
  selector:
    app: test-ambassdor-method-get
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-ambassdor-method-post
spec:
  selector:
    app: test-ambassdor-method-post
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
#apiVersion: getambassador.io/v2.  I am try v2 version, but it also do not work.
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: test-ambassdor-method-get
spec:
  prefix: /ambassdor-method
  service: test-ambassdor-method-get.default
  method: GET
  host_redirect: true
  method_regex: true
  hostname: "*"
---
#apiVersion: getambassador.io/v2
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: test-ambassdor-method-post
spec:
  prefix: /ambassdor-method
  hostname: "*"
  service: test-ambassdor-method-post.default
  method: POST
  host_redirect: true
  method_regex: true
```
Run this command;
```bash
[root@cluster1-master mapping]# curl  -X POST LB-IP/ambassdor-method
{"message":"This is GET server, from test-ambassdor-method-get-5d659c9fcf-sgbrh"}
```

**Expected behavior**

```bash
[root@cluster1-master mapping]# curl  -X POST LB-IP/ambassdor-method
{"message":"This is POST server, from test-ambassdor-method-post-5d659c9fcf-sgbrh"}
```

**Versions (please complete the following information):**
 - Ambassador: 7.2.0
 - Helm chart: 2.1.0
 - K8s Version: 
 ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
