### ISSUE TITLE
Altering/Dropping The Selective Query Params At The Ambassador Gateway

### ISSUE THREAD

**Issue by gr8Adakron** [emissary-ingress/emissary#4036]
**Please describe your use case / problem.**

The feature I am looking for is to drop out certain params from the url after authentication is completed. For example, I have bucket as dns which is like this 
```
<bucket_name>.example.com
```

The signed url generated for this bucket is something 
```
<bucket_name>.example.com?query_params1=something&query_params2=something
```

Here application add certain custom params as well which becomes 
```
<bucket_name>.example.com?query_params1=something&query_params2=something&custom_params=token_id
```

However S3 doesn't recognize the `custom_params` - as only gateway(auth service) does. So when custom param are directly forwarded to s3 for accessing an object - returns error. 

The feature request I have is if somehow I can drop the custom params at the ambassador layer itself - would be quiet cool as no development/application support would be required. 

I tried something like, which didn't worked out:

```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: <bucket>-pg-storage
  namespace: storage-gateway
spec:
  ambassador_id: storage-gateway
  host: <bucket>.example.com
  prefix: /
  bypass_auth: true
  remove_response_headers:
  - x-envoy-upstream-service-time
  # rewrite: /
  regex_rewrite:
    pattern: '/(.*)/&custom_param.*'
    substitution: '/\1'
  service: storage-ext-svc.internal-services
  timeout_ms: 30000
  tls: true
```

**Describe the solution you'd like**
Somewhere in the mapping - if we can `query_param_rewrite` substitution kind of structure - or drop option
```yaml
service: storage-ext-svc.internal-services
timeout_ms: 30000
tls: true
drop_query_param:
  - custom_param1
  - custom_param2

```

**Describe alternatives you've considered**
None Found

**Additional context**
None

- Thanks for such an awesome product.
