### ISSUE TITLE
"Can't do overview before configuration"

### ISSUE THREAD

**Issue by gajus** [emissary-ingress/emissary#4043]
**Describe the bug**

Getting error "Can't do overview before configuration"

**To Reproduce**
1. Go to http://127.0.0.1:8877/ambassador/v0/diag/

**Expected behavior**
Expecting to see the admin portal.

**Versions (please complete the following information):**
 - Emissay-ingress: 7.2.0
 - Kubernetes environment: minikube
 - Version: v1.23.1

**Additional context**

- Running using `minikube`
- All pods appear to be running fine
- Main deployment logs 500 error:
> 2022-01-24 18:36:40 diagd 2.1.0 [P1008TThreadPoolExecutor-0_0] ERROR: CC1AF3D1-4754-4984-868E-61BE2936F15E: 127.0.0.1 "GET /ambassador/v0/diag/" 1ms 500 failure
- Helm values:
```yaml
createNamespace: true
agent:
  enabled: false
createDefaultListeners: false
scope:
  singleNamespace: false
rbac:
  create: true
adminService:
  create: true
```
