### ISSUE TITLE
Randomly getting failing CORS validation

### ISSUE THREAD

**Issue by ShurikAg** [emissary-ingress/emissary#4049]
After building the environment on Kubernetes we tried migrating our backend to it.
As a result, **sometimes**, CORS check is failing.  

![image](https://user-images.githubusercontent.com/916432/151085200-2cf6cfd7-aac1-4c08-a81e-9dca4d1a3a25.png)

As per [Ambassador docs](https://www.getambassador.io/docs/edge-stack/latest/topics/using/cors/) we added CORS config to the mapping:

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: priz-api
  namespace: ambassador
spec:
  prefix: /
  host: api.priz.guru
  service: priz-api.backend
  cors:
    origins: https://app.priz.guru
    methods: GET, POST, PUT, PATCH, OPTIONS, DELETE
    headers: "*"
    exposed_headers: "*"
    max_age: "86400"
```

Also tried this config:
```
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: priz-api
  namespace: ambassador
spec:
  prefix: /
  host: api.priz.guru
  service: priz-api.backend
  cors:
    origins: https://app.priz.guru
    methods: GET, POST, PUT, PATCH, OPTIONS, DELETE
    headers: Content-Type
    credentials: true
    exposed_headers: "*"
    max_age: "86400"
```
Same result:

![image](https://user-images.githubusercontent.com/916432/151086250-069d0a24-4421-4099-b687-56707c28b910.png)

Nothing changed. The most interesting part is that if I completely remove the cors config, the first time the request fails, but initiate the same request again (create a resource), it works!?!?!?

What am I doing wrong? 

Also, the backend API is supporting CORS and it works for years through a regular LB.
What is the best approach here?
