### ISSUE TITLE
add_request_headers fails validation for key value pairs on version 2.1.2

### ISSUE THREAD

**Issue by cliveseldon** [emissary-ingress/emissary#4061]
**Describe the bug**
`add_request_headers` fails validation for key values pairs

**To Reproduce**

install [emissary](https://www.getambassador.io/docs/emissary/latest/tutorials/getting-started/) (2.1.2)

Create Mapping like

```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name:	test
spec:
  hostname: "*"
  prefix: /path/
  service: foo
  add_request_headers:
    foo: bar
```

apply via kubectl.

```
error: error validating "tt.yaml": error validating data: ValidationError(Mapping.spec.add_request_headers.foo): invalid type for io.getambassador.v3alpha1.Mapping.spec.add_request_headers: got "string", expected "map"; if you choose to ignore these errors, turn validation off with --validate=false
```

**Expected behavior**
Works as described in [docs](https://www.getambassador.io/docs/emissary/latest/topics/using/headers/add_request_headers/)

**Versions (please complete the following information):**
 - Ambassador: [2.1.2]
 - Kubernetes environment [Kind 1.21.1]
