### ISSUE TITLE
Weight ignored with add_request_headers and same service

### ISSUE THREAD

**Issue by cliveseldon** [emissary-ingress/emissary#4062]
**Describe the bug**
`weight` and `add_request_headers` in a single service do not play well. Just the second mapping is used irrespective of weight.
It seems the request headers are always merged together from both mappings?

**To Reproduce**
Install 2.1.2

create mapping of form 

```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: http1
spec:
  hostname: "*"
  prefix: /
  service: mysvc
  add_request_headers:
    foo:
      value: "v1"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: http2
spec:
  hostname: "*"
  prefix: /
  service: mysvc
  weight: 50
  add_request_headers:
    foo:
      value: "v2"
```

**Expected behavior**
Works as described in [docs](https://www.getambassador.io/docs/edge-stack/latest/topics/using/canary/)

**Versions (please complete the following information):**
 - Ambassador: [2.1.2]
 - Kubernetes environment Kind 1.21.1]

Related to https://github.com/emissary-ingress/emissary/issues/1288
