### ISSUE TITLE
`emissary-apiext` pod runs as `root`

### ISSUE THREAD

**Issue by phlawski** [emissary-ingress/emissary#4083]
**Please describe your use case / problem.**

`emissary-apiext` pods in the `emissary-system` namespace are running as privileged, basically using a `root` user. On production systems in our case it is not acceptable by the cluster policy. 
 
**Describe the solution you'd like**
I'd like to either:

- the `yaml` file which bootstraps `emissary-system` (https://app.getambassador.io/yaml/emissary/2.1.0/emissary-crds.yaml) would have `securityContext` set in the `Deployment` by default:
```
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 8888
```
- or two files to choose from, one with `securityContext` *on* and one with `securityContext` *off*

**Describe alternatives you've considered**
For now we have copied content of the file and we have added mentioned `securityContext`

Actually the best future approach would be to completely separate CRDs and Roles stuff from the Deployment of `emissary-apiext`, I'd see the latter as a regular `helm` Chart.
