### ISSUE TITLE
json access log fields should be numbers, not strings

### ISSUE THREAD

**Issue by Mladen-Karadimov** [emissary-ingress/emissary#4103]
**Describe the bug**

I want to get the numeric json logs fields as numbers, not as strings.

I am sending my logs to elastic search through fluent-bit. I needed them in json format in order this to work - so i did it.
I have started setting up dashboards and i wasn't able to work properly with `duration` and `upstream_service_time` fields, because they both are sting formats, because they are printed like strings in the json output of the logs:

```json
{
  "path": "/some/service",
  "duration": "5",
  "upstream_service_time": "3"
}
```

So i have checked how to change my json logs in order to print the number values as numbers, not as strings.
I have found this default configuration - https://github.com/emissary-ingress/emissary/blob/master/python/ambassador/envoy/v3/v3listener.py#L316
and decided to just remove the quotes.

Looks like that:
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    use_proxy_proto: false
    envoy_log_type: json
    envoy_log_format:
      {
        "start_time": "%START_TIME%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "response_code": %RESPONSE_CODE%,
        "response_flags": "%RESPONSE_FLAGS%",
        "bytes_received": %BYTES_RECEIVED%,
        "bytes_sent": %BYTES_SENT%,
        "duration": %DURATION%,
        "upstream_service_time": %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%,
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "user_agent": "%REQ(USER-AGENT)%",
        "request_id": "%REQ(X-REQUEST-ID)%",
        "authority": "%REQ(:AUTHORITY)%",
        "upstream_host": "%UPSTREAM_HOST%",
        "upstream_cluster": "%UPSTREAM_CLUSTER%",
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
        "requested_server_name": "%REQUESTED_SERVER_NAME%",
        "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
      }
```
^ like that the deployment fails because of `%`

I have tried to add
```yaml
    envoy_log_format: |
```
or
```yaml
    envoy_log_format: |-
```
or
```yaml
    envoy_log_format: >-
```

But it doesn't accept my json then. Following error happens:
```
2022-02-09 14:27:51 diagd 2.1.2 [P22TAEW] INFO: error ambassador.eu-shared-api-gateway.1 envoy_log_type 'json' requires a dictionary in envoy_log_format: {
  "start_time": "%START_TIME%",
  "method": "%REQ(:METHOD)%",
  "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
  "protocol": "%PROTOCOL%",
  "response_code": %RESPONSE_CODE%,
  "response_flags": "%RESPONSE_FLAGS%",
  "bytes_received": %BYTES_RECEIVED%,
  "bytes_sent": %BYTES_SENT%,
  "duration": %DURATION%,
  "upstream_service_time": %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%,
  "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
  "user_agent": "%REQ(USER-AGENT)%",
  "request_id": "%REQ(X-REQUEST-ID)%",
  "authority": "%REQ(:AUTHORITY)%",
  "upstream_host": "%UPSTREAM_HOST%",
  "upstream_cluster": "%UPSTREAM_CLUSTER%",
  "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",
  "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",
  "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",
  "requested_server_name": "%REQUESTED_SERVER_NAME%",
  "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",
  "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
}
```

**To Reproduce**
^ explained above.

**Expected behavior**

Expected behaviour for me would be, this to be working out of the box, which would mean the standard json output to be without quotes for number.
If this is not possible, please tell me how can i achieve this trough adding custom log_format.

**Versions (please complete the following information):**
 - Ambassador: 2.1.2
 - Kubernetes environment : AWS EKS
 - Version: 7.1.2 (helm chart)
^ i am using latest software

**Additional context**

**Comment by Mladen-Karadimov** [comment]
I have found a working solution - stopping the json format and setting it up manually, like that:

```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    use_proxy_proto: false
    # envoy_log_type: json
    envoy_log_format: >-
      {"start_time": "%START_TIME%","method": "%REQ(:METHOD)%","path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%","protocol": "%PROTOCOL%","response_code": %RESPONSE_CODE%,"response_flags": "%RESPONSE_FLAGS%","bytes_received": %BYTES_RECEIVED%,"bytes_sent": %BYTES_SENT%,"duration": %DURATION%,"upstream_service_time": %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%,"x_forwarded_for": "%REQ(X-FORWARDED-FOR)%","user_agent": "%REQ(USER-AGENT)%","request_id": "%REQ(X-REQUEST-ID)%","authority": "%REQ(:AUTHORITY)%","upstream_host": "%UPSTREAM_HOST%","upstream_cluster": "%UPSTREAM_CLUSTER%","upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%","downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%","downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%","requested_server_name": "%REQUESTED_SERVER_NAME%","istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%","upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%"}
```
