### ISSUE TITLE
Ambassador - Istio integration istio-certs not getting created

### ISSUE THREAD

**Issue by Arttii** [emissary-ingress/emissary#4123]
I am facing a setup issue with istio for an older version of Ambassador. Following the guide https://www.getambassador.io/docs/emissary/latest/howtos/istio/ lets me generate all the necessary certs, but the `istio-certs` secrets never gets created. I do not see any logs about this in the ambassador pod, istio pod or the k8s events. I only see Ambassador logs for detecting the new istio certs and nothing for actually creating it.

Any tips for debugging this would be greatly appreciated.

***Version***
  Kubernetes 1.21(Openshift 4.8.28)
  Istio v2.0
  Ambassador 1.14.1

**Comment by cindymullins-dw** [comment]
Istio integration has changed a lot with Ambassador 2.0+.  The link you posted above points to v2.2 so there might be discrepancies if you’re following those instructions. Can you try these instructions instead or confirm which you're using: https://www.getambassador.io/docs/emissary/1.14/howtos/istio/

**Comment by Arttii** [comment]
I am using a very similiar deployment to the one in 1.14 guide, just that I am auto-injecting the istio-sidecar. I am not sure what can influence the `istio-certs` secret not being created. The only difference and I can easily spot is me not having `AMBASSADOR_INTERNAL_URL`, but I am not sure why this would influence anything. Do you have any ideas?
``` yaml
kind: Pod
apiVersion: v1
metadata:
  annotations:
    openshift.io/scc: restricted
    sidecar.istio.io/interceptionMode: REDIRECT
    k8s.v1.cni.cncf.io/networks: v2-0-istio-cni
    traffic.sidecar.istio.io/excludeInboundPorts: '15090,15021'
  namespace: sgoku
  labels:
    maistra.io/expose-route: 'true'
    security.istio.io/tlsMode: istio
    app.kubernetes.io/part-of: ambassador
    app.kubernetes.io/instance: ambassador
    service.istio.io/canonical-revision: latest
    kapp.k14s.io/app: '1632952546737341741'
    kapp.k14s.io/association: v1.0b9b650f164b6cc8c7df7ffb23fc6712
    product: aes
    app.kubernetes.io/managed-by: Helm
    service.istio.io/canonical-name: ambassador
    istio.io/rev: istio
    app.kubernetes.io/name: ambassador
    pod-template-hash: b7fdd7f
spec:
  restartPolicy: Always
  serviceAccountName: ambassador
  imagePullSecrets:
    - name: artifactory-secrets
  securityContext:
    seLinuxOptions:
      level: 's0:c27,c14'
    runAsUser: 1000730000
    runAsGroup: 1000730000
    fsGroup: 1000730000
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: 3Gi
        requests:
          cpu: 500m
          memory: 1Gi
      readinessProbe:
        httpGet:
          path: /app-health/ambassador/readyz
          port: 15020
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      name: ambassador
      livenessProbe:
        httpGet:
          path: /app-health/ambassador/livez
          port: 15020
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: REDIS_URL
          value: 'ambassador-redis-master.sgoku:6379'
        - name: AMBASSADOR_NAMESPACE
          value: sgoku
        - name: AES_LOG_LEVEL
          value: DEBUG
        - name: AMBASSADOR_CONFIG_BASE_DIR
          value: /tmp
        - name: AMBASSADOR_ENVOY_BASE_ID
          value: '1'
        - name: AMBASSADOR_ID
          value: sgoku-ambassador
        - name: AMBASSADOR_ISTIO_SECRET_DIR
          value: /tmp/istio-certs
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ambassador-redis
              key: redis-password
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        allowPrivilegeEscalation: false
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: admin
          containerPort: 8877
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: ambassador-pod-info
          readOnly: true
          mountPath: /tmp/ambassador-pod-info
        - name: ambassador-edge-stack-secrets
          readOnly: true
          mountPath: /.config/ambassador
        - name: istio-certs
          mountPath: /tmp/istio-certs/
        - name: kube-api-access-9ffkr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        aes:v1.14.2
    - resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 15021
          scheme: HTTP
        initialDelaySeconds: 1
        timeoutSeconds: 1
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 30
      terminationMessagePath: /dev/termination-log
      name: istio-proxy
      env:
        - name: JWT_POLICY
          value: first-party-jwt
        - name: PILOT_CERT_PROVIDER
          value: istiod
        - name: CA_ADDR
          value: 'istiod-istio.dapcb-istio.svc:15012'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INSTANCE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: CANONICAL_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.labels[''service.istio.io/canonical-name'']'
        - name: CANONICAL_REVISION
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.labels[''service.istio.io/canonical-revision'']'
        - name: PROXY_CONFIG
          value: >
            {"discoveryAddress":"istiod-istio.dapcb-istio.svc:15012","tracing":{"zipkin":{"address":"zipkin.dapcb-istio:9411"},"tlsSettings":{"subjectAltNames":[]}},"proxyMetadata":{"OUTPUT_CERTS":"/tmp/istio-certs"}}
        - name: ISTIO_META_POD_PORTS
          value: |-
            [
                {"name":"http","containerPort":8080,"protocol":"TCP"}
                ,{"name":"https","containerPort":8443,"protocol":"TCP"}
                ,{"name":"admin","containerPort":8877,"protocol":"TCP"}
            ]
        - name: ISTIO_META_APP_CONTAINERS
          value: ambassador
        - name: ISTIO_META_CLUSTER_ID
          value: Kubernetes
        - name: ISTIO_META_INTERCEPTION_MODE
          value: REDIRECT
        - name: ISTIO_METAJSON_ANNOTATIONS
          value: >
            {"checksum/config":"01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b","openshift.io/scc":"restricted","proxy.istio.io/config":"proxyMetadata:\n 
            OUTPUT_CERTS:
            /tmp/istio-certs\n","sidecar.istio.io/inject":"true","sidecar.istio.io/userVolume":"[{\"name\":
            \"istio-certs\", \"emptyDir\": {\"medium\":
            \"Memory\"}}]","sidecar.istio.io/userVolumeMount":"[{\"name\":
            \"istio-certs\", \"mountPath\":
            \"/tmp/istio-certs\"}]","traffic.sidecar.istio.io/includeInboundPorts":"","traffic.sidecar.istio.io/includeOutboundIPRanges":""}
        - name: ISTIO_META_WORKLOAD_NAME
          value: ambassador
        - name: ISTIO_META_OWNER
          value: 'kubernetes://apis/apps/v1/namespaces/sgoku/deployments/ambassador'
        - name: ISTIO_META_MESH_ID
          value: cluster.local
        - name: OUTPUT_CERTS
          value: /tmp/istio-certs
        - name: ISTIO_KUBE_APP_PROBERS
          value: >-
            {"/app-health/ambassador/livez":{"httpGet":{"path":"/ambassador/v0/check_alive","port":8877,"scheme":"HTTP"},"timeoutSeconds":1},"/app-health/ambassador/readyz":{"httpGet":{"path":"/ambassador/v0/check_ready","port":8877,"scheme":"HTTP"},"timeoutSeconds":1}}
      securityContext:
        capabilities:
          drop:
            - ALL
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        privileged: false
        runAsUser: 1000730001
        runAsGroup: 1000730001
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      ports:
        - name: http-envoy-prom
          containerPort: 15090
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: istiod-ca-cert
          mountPath: /var/run/secrets/istio
        - name: istio-data
          mountPath: /var/lib/istio/data
        - name: istio-envoy
          mountPath: /etc/istio/proxy
        - name: istio-podinfo
          mountPath: /etc/istio/pod
        - name: istio-certs
          mountPath: /tmp/istio-certs
        - name: kube-api-access-9ffkr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:03ba7a4bed6122c842ac0aeca626be7e6f3ec2106acee2ffda017c8cbf36e41b
      args:
        - proxy
        - sidecar
        - '--domain'
        - $(POD_NAMESPACE).svc.cluster.local
        - '--serviceCluster'
        - ambassador.sgoku
        - '--proxyLogLevel=warning'
        - '--proxyComponentLogLevel=misc:error'
        - '--trust-domain=cluster.local'
        - '--concurrency'
        - '2'
  serviceAccount: ambassador
  volumes:
    - name: ambassador-pod-info
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
        defaultMode: 420
    - name: ambassador-edge-stack-secrets
      secret:
        secretName: ambassador-edge-stack
        defaultMode: 420
    - name: kube-api-access-9ffkr
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
    - name: istio-envoy
      emptyDir:
        medium: Memory
    - name: istio-data
      emptyDir: {}
    - name: istio-podinfo
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
        defaultMode: 420
    - name: istiod-ca-cert
      configMap:
        name: istio-ca-root-cert
        defaultMode: 420
    - name: istio-certs
      emptyDir:
        medium: Memory
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule


```

**Comment by cindymullins-dw** [comment]
The issue is likely auto-injecting the Istio sidecar, which has to be added manually with v1.14.  For 2.x (2.2+ is recommended), auto-injecting the sidecar is supported.  The guide at https://www.getambassador.io/docs/emissary/1.14/howtos/istio/ will walk you thru changing the Ambassador deployment and add the Istio sidecar.  You'll need to set the podAnnotation in the deployment spec to
sidecar.istio.io/inject: 'false'.

**Comment by AliceProxy** [comment]
I'm closing this issue since we have an explanation for the behavior and a solution provided. If you encounter any further difficulties please don't hesitate to re-open the issue or reach out. Thanks :)

**Comment by szdonat** [comment]
At last I solved my problem. I added the following line to my Host object:
```
  tlsSecret:
    name: istio-certs
```
The whole object:

```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: hehe
spec:
  hostname: "*"
  tlsSecret:
    name: istio-certs
```
