### ISSUE TITLE
Regex query parameters  key & value pair can be used in substitution in regex_redirect (complex regex based on query params)

### ISSUE THREAD

**Issue by Anishmourya** [emissary-ingress/emissary#4132]
**I am trying to use the regex_query_parameters rule in ambassador Mapping rules. It has successfully worked in order to use the redirect URL but want to use query params value further in substitution like use with pattern & substitution in regex_redirect & regex_rewrite.**

I also checked in Mapping struct definition in the code to use multiple host mapping rules to solve this but still doesn't work for me.
see this 

```
type RegexMap struct {
	Pattern      string `json:"pattern,omitempty"`
	Substitution string `json:"substitution,omitempty"`
}
```
[](https://github.com/emissary-ingress/emissary/blob/6257a419c94a3c1cf4facd381a1baf386cd363e9/pkg/api/getambassador.io/v3alpha1/crd_mapping.go#L56
)
RegexQueryParameters is just Query params of dict 	RegexQueryParameters map[string]string `json:"regex_query_parameters,omitempty"` while RegexRedirect *RegexMap `json:"regex_redirect,omitempty"` and 	RegexRewrite                 *RegexMap            `json:"regex_rewrite,omitempty"` both mapped to call RegexMap struct.

I am trying with this sample Mapping URL.

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: test-parcelid-redirect-mapping
spec:
  host: domain_origin_address
  host_redirect: true
  prefix: "/track/"
  redirect_response_code: 302
  service: domain_redirect_address
  regex_redirect:
    pattern: "/track/?parcel-id=X(.*)(/|$)(.*)"
    substitution: "/order?OrderReference="
  regex_query_parameters:
    parcel-id: "^X(.*)(/|$)(.*)"
```

**I want to redirect from https://domain_origin_address/track/?parcel-id=X23232-1234 to https://domain_redirect_address/order?OrderReference=X23232-1234** 

I have tried regex_redirect also but that is not picking "?" in the URL. It's taking the entire value after the / like "parcel-id=X23232-1234" if I remove "?" in the rule. also, no other way to remove the parcel-id query params in the substitution section. 

Feature Request:-
**I want to use query params based on regex matching (which is already working)and must be a way where can use the query params key & value pairs further in the substitution URL to write complex rules of regex redirect in ambassador Mapping**
