### ISSUE TITLE
Mappings with the same prefix associated with different hosts via mappingSelector are lost except the last one

### ISSUE THREAD

**Issue by antonu17** [emissary-ingress/emissary#4152]
**Describe the bug**

Mapping and Host Association is broken. There's a situation when Mapping doesn't configure Envoy proxy as expected.

When several `mappings`, associated with different hosts using `mappingSelector`, have the same prefix only the last mapping gets rendered into envoy configuration.

**To Reproduce**

I need to expose 2 websites as shown in the human-friendly form below:

```yaml
# Human-friendly configuration
# sites:
#   site-1:
#     hosts:
#       - first.com
#     mappings:
#       - prefix: /
#         service: http://httpbin.org

#   site-2:
#     hosts:
#       - second.com
#     mappings:
#       - prefix: /
#         service: http://httpbin.org
```

I want to use use a [`mappingSelector` approach][1], where the `Host` specifies a `mappingSelector` that matches the `Mapping`'s Kubernetes labels.

Translated to CRDs:

```yaml
# Hosts for site-1
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: site-1-first-com
spec:
  hostname: first.com
  mappingSelector:
    matchLabels:
      site: site-1
  requestPolicy:
    insecure:
      action: Route

# Mappings for site-1
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  site-1-root
  labels:
    site: site-1
spec:
  prefix: /
  service: http://httpbin.org

# Hosts for site-2
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: site-2-second-com
spec:
  hostname: second.com
  mappingSelector:
    matchLabels:
      site: site-2
  requestPolicy:
    insecure:
      action: Route

# Mappings for site-2
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  site-2-root
  labels:
    site: site-2
spec:
  prefix: /
  service: http://httpbin.org
```

Install emissary-ingress and configuration above

```bash
# Add the Repo:
helm repo add datawire https://app.getambassador.io
helm repo update

# Create Namespace and Install:
kubectl create namespace emissary && \
kubectl apply -f https://app.getambassador.io/yaml/emissary/2.2.2/emissary-crds.yaml
kubectl wait --timeout=90s --for=condition=available deployment emissary-apiext -n emissary-system
helm upgrade --install emissary-ingress --namespace emissary datawire/emissary-ingress --set=agent.enabled=false --set=createDefaultListeners=true --set=replicaCount=1 && \
kubectl -n emissary wait --for condition=available --timeout=90s deploy -lapp.kubernetes.io/instance=emissary-ingress

# Apply the above resources (hosts and mappings)
kubectl apply -f sites-resources.yaml
sudo kubectl port-forward --namespace emissary service/emissary-ingress 80:80

# Test first.com requests
curl http://first.com/ --resolve first.com:80:127.0.0.1 -v
HTTP/1.1 404 Not Found
## Access logs
ACCESS [2022-03-03T18:22:47.796Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "10.244.0.18" "curl/7.77.0" "d53088ac-06ae-433f-8713-d37e80de928c" "first.com" "-"

# Test second.com requests
curl http://second.com/ --resolve second.com:80:127.0.0.1 -v
HTTP/1.1 200 OK
## Access logs
ACCESS [2022-03-03T18:31:28.377Z] "GET / HTTP/1.1" 200 - 0 9593 237 236 "10.244.0.18" "curl/7.77.0" "010dd7a3-d28e-44f0-a4ba-133964ab3b30" "second.com" "3.209.99.235:80"
```

As seen in the testing results `site-1-root` Mapping configuration is "lost" and envoy-proxy doesn't know about it (response flags NR means "No Route").
When I add the third mapping, the first two get lost and only the last one made it into the envoy configuration.

## Additional information

A snippet of the `econf.json`

```json
"route_config": {
    "virtual_hosts": [
      {
        "domains": [
          "first.com"
        ],
        "name": "edge-stack-testing-http-first.com",
        "routes": [
          // "default" routes like /ambassador/v0/check_ready are stripped
        ]
      },
      {
        "domains": [
          "second.com"
        ],
        "name": "edge-stack-testing-http-second.com",
        "routes": [
          // "default" routes like /ambassador/v0/check_ready are stripped
          {
            "match": {
              "case_sensitive": true,
              "prefix": "/",
               // the rest is stripped
            },
            "route": {
              "cluster": "cluster_http___httpbin_org_edge_stack_testing",
              "prefix_rewrite": "/",
              "priority": null,
              "timeout": "3.000s"
            }
          }
        ]
      }
    ]
  }
```

**Expected behavior**

Both hosts are working

**Versions (please complete the following information):**
 - Ambassador: 2.2.2
 - Kubernetes environment: KIND
 - Version: 1.21.1

**Additional context**

Seems like this is only the case for Host-Mapping associations via `mappingSelector`. When I checked with `hostname` type of association - both mappings works correctly.

I need to use `mappingSelector` because for my real use case a single "website" has multiple domain names. In other words I need a single `Mapping` associated with multiple `Host`s. So `hostname` type of association doesn't work because it is "one-to-one". Here is a human-friendly config for what I actually need:

```yaml
# sites:
#   site-1:
#     hosts:
#       - first.com
#       - erste.de
#     mappings:
#       - prefix: /
#         service: http://httpbin.org

#   site-2:
#     hosts:
#       - second.com
#       - zweite.de
#     mappings:
#       - prefix: /
#         service: http://httpbin.org
```

[1]: https://www.getambassador.io/docs/edge-stack/latest/topics/running/host-crd/#controlling-association-with-mappings
