### ISSUE TITLE
stats_name is not respected when multiple Mappings route to the same backend Service

### ISSUE THREAD

**Issue by lsolovey** [emissary-ingress/emissary#4173]
**Describe the bug**
`stats_name` from Mapping CRDs is not respected when multiple Mappings route to the same backend Service.

**To Reproduce**
1. I have a simple Kubernetes app exposing two gRPC services.
2. I'd like to see Ambassador stats reported separately for each gRPC service.
3. So I created two Mapping CRDs, with different `prefix` and  `stats_name`. Both Mappings  routing to the same backend `Service` resource of my app.

```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mapping-1
spec:
  stats_name: foo
  grpc: true
  host: myhost.mycompany.com
  prefix: /mycompany.grpc.Service1/
  rewrite: ""
  service: my-grpc-service:8082
  timeout_ms: 5000
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mapping-1
spec:
  stats_name: bar
  grpc: true
  host: myhost.mycompany.com
  prefix: /mycompany.grpc.Service2/
  rewrite: ""
  service: my-grpc-service:8082
  timeout_ms: 5000
```

4. Sent one request to `mycompany.grpc.Service1` and `mycompany.grpc.Service2` grpc services at `myhost.mycompany.com` address.
5. Both requests succeeded.
6. Observe results at Ambassador `/metrics` endpoint. Both requests are counted under `stats_name` of the 1st Mapping (`foo`).

```
# TYPE envoy_cluster_upstream_rq counter
envoy_cluster_upstream_rq{envoy_response_code="200",envoy_cluster_name="127_0_0_1_8500"} 319
envoy_cluster_upstream_rq{envoy_response_code="200",envoy_cluster_name="foo"} 2
envoy_cluster_upstream_rq{envoy_response_code="200",envoy_cluster_name="xds_cluster"} 1
```

**Expected behavior**
Requests should be counted under `stats_name` of the appropriate Mapping CRD.

**Versions:**
 - Ambassador: 2.2.2
 - Kubernetes environment: Docker Desktop Kubernetes
 - Version 1.21.5
