### ISSUE TITLE
prefix_regex and regex_rewrite not working together

### ISSUE THREAD

**Issue by sidgujrathi** [emissary-ingress/emissary#4180]
**Describe the bug**
I am using v2 API and I want to allow resources that will be in form of `/anything-here/anyWord/api/auth/.*` for this I have the following mapping:

```
spec:
  labels:
    ambassador:
    - request_label_group:
      - xyz-api-rate-limit
  prefix: "/[A-Za-z0-9]+-[A-Za-z0-9]+/[A-Za-z0-9]+/api/auth/.*"
  prefix_regex: true
  regex_rewrite:
    pattern: "/[A-Za-z0-9]+-[A-Za-z0-9]+/[A-Za-z0-9]+/api/auth/(.*)"
    substitution: '/api/\1'
  service: auth.xyz-shared
  timeout_ms: 30000

```

The above mapping doesn't work. But if I replace `rewrite_regex` with only rewrite like `rewrite: /api/` it is working fine but in this case then I am losing the remainder after `api/auth/` which I need to pass on to service with the prefix `/api/`

Example: 
if resource  `/anything-here/anyWord/api/auth/roles` is requested I need to rewrite it as `/api/roles`
