### ISSUE TITLE
unable to configure host mapping

### ISSUE THREAD

**Issue by arunvc** [emissary-ingress/emissary#4185]
**Describe the bug**
error: no kind "Mapping" is registered for version "getambassador.io/v2" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"

**To Reproduce**
Install version 2.2.2 
https://www.getambassador.io/docs/emissary/latest/topics/install/helm/

listener, host mapping
```
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
  namespace: myns
spec:
  port: 80
  protocol: HTTP
  securityModel: XFP
  l7Depth: 1
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: myhost
  namespace: myns
spec:
  hostname: my.host.com
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: myhost-mapping
  namespace: myns
spec:
  host: my.host.com
  prefix: /
  service: service:8080
```

`kubectl logs mapping/myhost-mapping`
```
error: no kind "Mapping" is registered for version "getambassador.io/v2" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```
`kubectl logs host/myhost`
```
error: no kind "Host" is registered for version "getambassador.io/v2" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```
`kubectl logs listener.getambassador.io/http-listener`
```
error: no kind "Listener" is registered for version "getambassador.io/v3alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

**Expected behavior**
No error in log

**Versions (please complete the following information):**
 - Emissary-ingress : [2.2.2]
 - Kubernetes environment [Azure AKS]
 - Version [1.21.9]
