### ISSUE TITLE
L7 Load Balancing for gRPC does not seem to work correctly

### ISSUE THREAD

**Issue by ShellyWEI** [emissary-ingress/emissary#4197]
**Describe the bug**
My company has ambassador installed in our prod cluster for a while but this is the first time we tried to migrate to gRPC service. As a experiment I deploy the ambassador under a separate namespace along with the server/service/mapping/resolver those resources. During the testing, gRPC connection was able to go through but the load balancing is not properly performed. The gRPC request will always go to one pod instead balanced across two pods.

**To Reproduce**
The configs that I used:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: staging
spec:
  selector:
    app: my-service
  ports:
  - port: 80
    targetPort: grpc-api
    name: grpc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  namespace: staging
  labels:
    app: my-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: <my_image>
        ports:
        - containerPort: 50051
          name: grpc-api
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  namespace: staging
spec:
  ports:
  - name: http
    nodePort: 30053
    port: 80
    targetPort: 8080
  - name: https
    nodePort: 30051
    port: 443
    targetPort: 8443
  selector:
    app: ambassador
  type: NodePort
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: wildcard-host
  namespace: staging
spec:
  acmeProvider:
    authority: none
  hostname: '*'
  mappingSelector:
    matchLabels:
      host: my-service
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: my-service-mapping
  namespace: staging
  labels:
    host: my-service
spec:
  hostname: "*"
  grpc: true
  prefix: /hello.MyService/
  rewrite: /hello.MyService/
  service: my-service
  resolver: endpoint
  load_balancer:
    policy: round_robin
---
apiVersion: getambassador.io/v2
kind: KubernetesEndpointResolver
metadata:
  name: endpoint
  namespace: staging
```
Due to company restriction, the pod is only accessible from certain hosts, so I use a ssh tunnel for testing:
```
ssh -nNT -L 50053:<k8s_endpoint>:30053 <jump_host>
```
Then make the client call:
```
val channel = ManagedChannelBuilder
      .forAddress(host, port)
      .usePlaintext
      .build
val stub = MyServiceGrpc.blockingStub(channel)
for (n <- 1 to 20) {
      stub.sayHello()
 }
```

**Expected behavior**
All those 20 requests should be balanced evenly. But I can only see one pod is getting the request coming.
Only if I do client side load balancing like changing the channelBuilder to have .defaultLoadBalancingPolicy("round_robin") will do the trick. However I don't think it is a proper L7 load balancing behavior.

**Versions (please complete the following information):**
 - Ambassador: 1.13.1
 - Kubernetes environment: bare-metal
 - Version: v1.18.9

**Additional context**
I tried to use module for setup as well.
```
apiVersion: getambassador.io/v2
kind:  Module
metadata:
  name:  my-resolver
  namespace: staging
spec:
  config:
    resolver: endpoint
    load_balancer:
      policy: round_robin
```
Not working.

Some core envoy config generated by ambassador:
```
"clusters":
        "connect_timeout": "3.000s",
        "dns_lookup_family": "V4_ONLY",
        "http2_protocol_options": {},
        "lb_policy": "ROUND_ROBIN",
        "load_assignment": {
          "cluster_name": "cluster_my_service_staging",
          "endpoints": [
            {
              "lb_endpoints": [
                {
                  "endpoint": {
                    "address": {
                      "socket_address": {
                        "address": "my-service",
                        "port_value": 80,
                        "protocol": "TCP"
                      }
              ]
            }
          ]
        },
        "name": "cluster_my_service_staging",
        "type": "STRICT_DNS"
      },
"listeners": [
      {
        "address": {
          "socket_address": {
            "address": "0.0.0.0",
            "port_value": 8080,
            "protocol": "TCP"
          }
        },
        "filter_chains": [
          {
            "filter_chain_match": {},
            "filters": [
              {
                "name": "envoy.filters.network.http_connection_manager",
                "typed_config": {
                  "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager",
                  "http_filters": [
                    {
                      "name": "envoy.filters.http.cors"
                    },
                    {
                      "name": "envoy.filters.http.router"
                    }
                  ],
                  "http_protocol_options": {
                    "accept_http_10": false
                  },
                  "normalize_path": true,
                  "preserve_external_request_id": false,
                  "route_config": {
                    "virtual_hosts": [
                      {
                        "domains": [
                          "*"
                        ],
                        "name": "ambassador-listener-8080-*",
                        "routes": [
                          {
                            "match": {
                              "case_sensitive": true,
                              "headers": [
                                {
                                  "exact_match": "https",
                                  "name": "x-forwarded-proto"
                                }
                              ],
                              "prefix": "/hello.MyService/",
                              "runtime_fraction": {
                                "default_value": {
                                  "denominator": "HUNDRED",
                                  "numerator": 50
                                },
                                "runtime_key": "routing.traffic_shift.cluster_my_service_staging"
                              }
                            },
                            "route": {
                              "cluster": "cluster_my_service_staging",
                              "prefix_rewrite": "/hello.MyService/",
                              "priority": null,
                              "timeout": "3.000s"
                            }
                          },
                          {
                            "match": {
                              "case_sensitive": true,
                              "prefix": "/hello.MyService/",
                              "runtime_fraction": {
                                "default_value": {
                                  "denominator": "HUNDRED",
                                  "numerator": 50
                                },
                                "runtime_key": "routing.traffic_shift.cluster_my_service_staging"
                              }
                            },
                            "route": {
                              "cluster": "cluster_my_service_staging",
                              "prefix_rewrite": "/hello.MyService/",
                              "priority": null,
                              "timeout": "3.000s"
                            }
                          }
                        ]
                      }
                    ]
                  },
                  "server_name": "envoy",
                  "stat_prefix": "ingress_http",
                  "use_remote_address": true,
                  "xff_num_trusted_hops": 0
                }
              }
            ]
          }
        ],
        "listener_filters": [],
        "name": "ambassador-listener-8080",
        "traffic_direction": "UNSPECIFIED"
      }
```

Not sure if this is a related bug, but if I change the lb policy to `least_request` I can't find it in envoy either.

Please help us understand the reason and if possible provide the debugging guide on your website about L7 load balancing too.
Much appreciated!
