### ISSUE TITLE
helm chart - createDefaultListeners does not set ambassador_id for listeners when AMBASSADOR_ID env is set

### ISSUE THREAD

**Issue by ServerNinja** [emissary-ingress/emissary#4198]
**Describe the bug**
The helm chart does not include the 'ambassador_id' in the default set of listeners when 'createDefaultListeners' is set as 'true' and 'AMBASSADOR_ID' exists in the environment variables. NOTE: the "module" deployed does include 'ambassador_id' as expected.

**To Reproduce**
1. Configure AMBASSADOR_ID in helm chart values
```
env:
  AMBASSADOR_ID: "two"
```
2. Install chart
3. Result: ambassador_id is missing from spec, thus the listeners are essentially not configured properly (and not working)
Example objects created:
```
apiVersion: v1
items:
- apiVersion: getambassador.io/v3alpha1
  kind: Listener
  metadata:
    annotations:
      meta.helm.sh/release-name: emissary-ingress-two
      meta.helm.sh/release-namespace: emissary-ingress-two
    labels:
      app.kubernetes.io/managed-by: Helm
    name: emissary-ingress-two-http-listener
    namespace: emissary-ingress-two
  spec:
    hostBinding:
      namespace:
        from: ALL
    port: 8080
    protocol: HTTP
    securityModel: XFP
- apiVersion: getambassador.io/v3alpha1
  kind: Listener
  metadata:
    annotations:
      meta.helm.sh/release-name: emissary-ingress-two
      meta.helm.sh/release-namespace: emissary-ingress-two
    labels:
      app.kubernetes.io/managed-by: Helm
    name: emissary-ingress-two-https-listener
    namespace: emissary-ingress-two
  spec:
    hostBinding:
      namespace:
        from: ALL
    port: 8443
    protocol: HTTPS
    securityModel: XFP
kind: List
```

**Expected behavior**
Should include 'ambassador_id' in spec of each of the two listeners deployed

```
apiVersion: v1
items:
- apiVersion: getambassador.io/v3alpha1
  kind: Listener
  metadata:
    annotations:
      meta.helm.sh/release-name: emissary-ingress-two
      meta.helm.sh/release-namespace: emissary-ingress-two
    labels:
      app.kubernetes.io/managed-by: Helm
    name: emissary-ingress-two-http-listener
    namespace: emissary-ingress-two
  spec:
    ambassador_id:
    - two
    hostBinding:
      namespace:
        from: ALL
    port: 8080
    protocol: HTTP
    securityModel: XFP
- apiVersion: getambassador.io/v3alpha1
  kind: Listener
  metadata:
    annotations:
      meta.helm.sh/release-name: emissary-ingress-two
      meta.helm.sh/release-namespace: emissary-ingress-two
    labels:
      app.kubernetes.io/managed-by: Helm
    name: emissary-ingress-two-https-listener
    namespace: emissary-ingress-two
  spec:
    ambassador_id:
    - two
    hostBinding:
      namespace:
        from: ALL
    port: 8443
    protocol: HTTPS
    securityModel: XFP
kind: List
```

**Versions (please complete the following information):**
 - Ambassador: 2.3.0
 - Kubernetes environment: EKS  v1.21
 - Chart version: 7.3.2
