### ISSUE TITLE
Unable to set `timeout_ms` for Knative Revisions due to deprecated field.

### ISSUE THREAD

**Issue by treethought** [emissary-ingress/emissary#4214]
When using emissary ingress as the Knative ingress class, there is no way set the `timeout_ms` field for the envoy route.

The emissary code that generates the Mapping [here](https://github.com/emissary-ingress/emissary/blob/master/python/ambassador/fetch/knative.py#L80) is attempting to use `Timeout` field from the `networking.internal.knative.dev/v1/alpha1/ingresses` kubernetes object but this field has been [deprecated](https://github.com/knative/serving/blob/release-0.22/vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go#L246) and now [no longer exists](https://github.com/knative/serving/blob/main/vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go#L199).

As a result, the `timout_ms` field is always set to 15s causing the connection to be killed when a responding after the envoy timeout despite the Revision timeout being 5 minutes.

**To Reproduce**
1. Setup knative using emissary ingress
2. leave the default timeout values in knative `config-defaults` configmap (5 minute default, 10 minute max)
3. Deploy a knative service that responds after 15 seconds
4. Notice the `x-envoy-expected-req-timeout-ms` is 15000 instead 300000
5. Request fails due to context cancelled
6. The request times out, with queue-proxy logging "context cancelled" error
7. Request fails with 504, "upstream request timeout"

**Expected behavior**

When setting the knative `revision-timeout-ms` to a value above 15000:
- the generated Mapping's timeout_ms should be set to the same value
- the `x-envoy-expected-req-timeout-ms` should be set to the same value
-  the request is not killed at 15s
- When service responds before the timeout value, the response should be returned with proper status
- no queue-proxy error

**Versions **
 - Ambassador: 2.0.2-ea
 - Kubernetes environment: minikube, baremetal, Amazon EKS
 - Helm Chart: 7.12-ea
 - Knative: 0.22.2

**Comment by treethought** [comment]
Some more details on setup and config. Note that the knative deployments receive traffic fine using emissary-ingress, it's just that the timeout set on the revision or in knative config-defaults has no effect.

Using a relatively simple emissary-ingress helm install
```shell
helm repo add datawire https://www.getambassador.io
helm repo update
helm -n ambassador upgrade --install emissary-ingress \
  --devel datawire/emissary-ingress \
  --set image.repository=docker.io/datawire/emissary \
  --set image.tag=2.0.2-ea --set service.externalTrafficPolicy=Local \
  --set-string podAnnotations.'prometheus\.io/scrape'=true \
  --set-string podLabels.'app\.kubernetes\.io/team'="my-team" \
  --set-string podLabels.'app\.kubernetes\.io/repository'="my-repo" \
  --set enableAES=false --set env.AMBASSADOR_ID=ed-209 --set daemonSet="true" \
  --set resources.requests.cpu="$cpu_request" --set resources.limits.cpu="$cpu_limit" \
  --set resources.requests.memory="$memory_request" --set resources.limits.memory="$memory_limit" \
  --set env.AMBASSADOR_ID=ed-209 --set metrics.serviceMonitor.enabled="$service_mon" \
  --set adminService.create="nil" \
  --set metrics.serviceMonitor.selector.'app'="clusterprom" \
  --set metrics.serviceMonitor.selector.'release'="clusterprom" \
  --version="7.1.2-ea"
```
We then configure the integration with the existing knative installtion

```shell
# set env for knative support
kubectl set env --namespace ambassador daemonset/emissary-ingress AMBASSADOR_KNATIVE_SUPPORT=true

kubectl patch svc emissary-ingress --namespace ambassador --patch "{\"spec\": { \"loadBalancerIP\": \"${MY_GATEWAY_IP}\" }}"

# set ingress class and knative domain

kubectl patch configmap/config-network \
    --namespace knative-serving \
    --type merge \
    --patch '{"data":{"ingress.class":"ambassador.ingress.networking.knative.dev"}}'

# patch knative with domain
kubectl patch configmap/config-domain \
    --namespace knative-serving \
    --type merge \
    --patch "{\"data\":{\"${MY_DOMAIN}\":\"\"}}"
```

Then, aside from the Mappings we create for non-knative services, we have the following listeners:
```yaml
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorListener
metadata:
  name: my-https-listener
  namespace: my-ns
spec:
  ambassador_id: ed-209
  port: 8443
  protocol: HTTPS
  securityModel: SECURE
  l7Depth: 1
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorListener
metadata:
  name: my-http-listener
  namespace: my-ns
spec:
  ambassador_id: ed-209
  port: 8080
  protocol: HTTP
  securityModel: INSECURE
  l7Depth: 1
  hostBinding:
    namespace:
      from: ALL

```

The following Module
```yaml
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  name: ambassador
  namespace: ambassador
spec:
  ambassador_id: ed-209
  config:
    gzip:
      enabled: true
    use_remote_address: true
    xff_num_trusted_hops: 1
    server_name: "ec"
    error_response_overrides:
      - on_status_code: 404
        body:
          text_format: "not found"
      - on_status_code: 500
        body:
          json_format:
            error: "error"
            status: "%RESPONSE_CODE%"
            cluster: "%UPSTREAM_CLUSTER%"
    load_balancer:
      policy: least_request
```

The following Host:
```yaml
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorHost
metadata:
  name: my-host
  namespace: my-ns
spec:
  ambassador_id: ed-209
  hostname: "*.my-domain.com"
  acmeProvider:
    authority: none
  tlsSecret:
    name: my-domain-com-tls
  tlsContext:
    name: my-tls-context
  requestPolicy:
    insecure:
      action: Redirect

```

With the following TLSContext
```yaml
---
apiVersion: getambassador.io/v2
kind:  TLSContext
metadata:
  name:  my-tls-context
  namespace: my-ns
spec:
  ambassador_id: ed-209
  secret: my-domain-com-tls
  hosts: ["*my-domain.com"]
  min_tls_version: v1.2
```
