### ISSUE TITLE
Edgissary's anti affinity configuration is broken

### ISSUE THREAD

**Issue by rhs** [emissary-ingress/emissary#4237]
The antiaffinity portion of the manifests reference the old labeling scheme and therefore don't actually have the desired impact. This is a regression and presumably has been so since the labeling scheme was changed. Note the `service: ambassador` label used:

```
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  service: ambassador
              topologyKey: kubernetes.io/hostname
            weight: 100
```
