### ISSUE TITLE
DevPortal cannot fetch the API documentation

### ISSUE THREAD

**Issue by tolik93** [emissary-ingress/emissary#4260]
**Describe the bug**
Since migration from Ambassador Edge 1.14 to 2.2.2 Mapping docs cannot be fetched by the DevPortal. 
I followed instructions by [Quick Start](https://www.getambassador.io/docs/edge-stack/latest/tutorials/getting-started/)
In addition, I use self-signed certificates created by CertManager. Everything works fine and I am able to get the response from the quote service via https://{HOSTNAME}/backend/
But the problem is that the docs cannot be fetched. I see that Ambassador pods are logging the following errors:
`level=error msg="Get \"https://127.0.0.1:8443/backend/.ambassador-internal/openapi-docs\": http: server gave HTTP response to HTTPS client" func="github.com/datawire/a │
│ pro/v2/cmd/amb-sidecar/devportal/server.(*DevPortalHTTPClient).Get" file="github.com/datawire/apro/v2/cmd/amb-sidecar/devportal/server/http.go:82" CMD=amb-sidecar PID=15 THREAD=/devportal_fetcher URL │
│ ="https://127.0.0.1:8443/backend/.ambassador-internal/openapi-docs" clusterName=cluster_quote_ambassador component=devportal mapping=quote-backend.ambassador mhost="*" subsystem=fetcher url="https:// │
│ 127.0.0.1:8443/backend/.ambassador-internal/openapi-docs"`

There is also the Istio integration configured followed by the [documentation](https://www.getambassador.io/docs/emissary/latest/howtos/istio/#istio-integration)

**Expected behavior**
Documentation should be fetched and showed on the /docs/ endpoint

**Versions (please complete the following information):**
 - Ambassador: [2.2.2]
 - Kubernetes environment [AWS EKS 1.22]
 - Helm chart version: [7.3.2]

**Additional context**
istio-integration.yaml
```yaml
# Listeners are required in Emissary-ingress 2.0.
# This will create the two default Listeners for HTTP on port 8080 and HTTPS on port 8443.
createDefaultListeners: false

emissary-ingress:
  # These are annotations that will be added to the Emissary-ingress pods.
  podAnnotations:
    # These first two annotations tell Istio not to try to do port management for the
    # Emissary-ingress pod itself. Though these annotations are placed on the Emissary-ingress
    # pods, they are interpreted by Istio.
    traffic.sidecar.istio.io/includeInboundPorts: ""      # do not intercept any inbound ports
    traffic.sidecar.istio.io/includeOutboundIPRanges: ""  # do not intercept any outbound traffic

    # We use proxy.istio.io/config to tell the Istio proxy to write newly-generated mTLS certificates
    # into /etc/istio-certs, which will be mounted below. Though this annotation is placed on the
    # Emissary-ingress pods, it is interpreted by Istio.
    proxy.istio.io/config: |
      proxyMetadata:
        OUTPUT_CERTS: /etc/istio-certs

    # We use sidecar.istio.io/userVolumeMount to tell the Istio sidecars to mount the istio-certs
    # volume at /etc/istio-certs, allowing the sidecars to see the generated certificates. Though
    # this annotation is placed on the Emissary-ingress pods, it is interpreted by Istio.
    sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'

  # We define a single storage volume called "istio-certs". It starts out empty, and Istio
  # uses it to communicate mTLS certs between the Istio proxy and the Istio sidecars (see the
  # annotations above).
  volumes:
    - emptyDir:
        medium: Memory
      name: istio-certs

  # We also tell Emissary-ingress to mount the "istio-certs" volume at /etc/istio-certs in the
  # Emissary-ingress pod. This gives Emissary-ingress access to the mTLS certificates, too.
  volumeMounts:
    - name: istio-certs
      mountPath: /etc/istio-certs/
      readOnly: true

  # Finally, we need to set some environment variables for Emissary-ingress.
  env:
    # AMBASSADOR_ISTIO_SECRET_DIR tells Emissary-ingress to look for Istio mTLS certs, and to
    # make them available as a secret named "istio-certs".
    AMBASSADOR_ISTIO_SECRET_DIR: "/etc/istio-certs"

    # AMBASSADOR_ENVOY_BASE_ID is set to prevent collisions with the Istio sidecar's Envoy,
    # which runs with base-id 0.
    AMBASSADOR_ENVOY_BASE_ID: "1"
  scope:
    singleNamespace: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role/edge
            operator: In
            values:
            - "true"
  tolerations:
  - key: node-role/edge
    operator: Equal
    value: "true"
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: ManagedBy=Kubernetes
      service.beta.kubernetes.io/aws-load-balancer-target-node-labels: node-role/edge=true
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

```
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: play
  namespace: ambassador
spec:
  hostname: quote.example.com # my domain
  tlsSecret:
    name: quote-tls
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: http-listener
  namespace: ambassador
spec:
  port: 8080
  protocol: HTTPS  # NOT A TYPO, see below
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF   # See below
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: https-listener
  namespace: ambassador
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF   # See below
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  hostname: quote.example.com # my domain
  prefix: /backend/
  service: https://quote:80      # Be explicit about port 80. THIS IS IMPORTANT: see below
  tls: istio-upstream 
  docs:
    path: /.ambassador-internal/openapi-docs
    #url: http://quote:80/.ambassador-internal/openapi-docs
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: istio-upstream
  namespace: ambassador
spec:
  secret: istio-certs     # This Secret name cannot currently be changed.
  alpn_protocols: istio   # This is required for Istio.

```

**Comment by alexgervais** [comment]
Hi @tolik93, thanks for opening this issue.
At this time, our support team will try to replicate this issue and validate if this can be addressed with a configuration and documentation change, or if there's an underlying regression causing this issue.

**Comment by tolik93** [comment]
Hi @alexgervais, do you have any news about this issue? I am still unable to load DevPortal documentation. 
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: istio-certs
  requestPolicy:
    insecure:
      action: Redirect
```
There was a hint in some Documentation or Slack Thread, where the wildcard Host should be set. After that I don't see Mapping Resources in DevPortal. 

![image](https://user-images.githubusercontent.com/17907942/179504962-e85964aa-ba7c-46e2-9e75-e86f08450361.png)

Without wildcard Host I see that docs cannot be loaded but I still can request it via HTTP call.
![image](https://user-images.githubusercontent.com/17907942/179505459-bb0e20d4-770c-41da-ba9b-cc5d339f293c.png)
