### ISSUE TITLE
Creating ELB on AWS not passing health check on EKS instances in ASG

### ISSUE THREAD

**Issue by alexbowers** [emissary-ingress/emissary#4273]
**Describe the bug**
We have a (classic) ELB being created in AWS successfully, however, the health check is not passing for any of the instances, so the load balancer does not pass any traffic to EKS.

The instances are part of an Autoscaling Group, however, when I go to the ASG (and EC2 instances itself), they are listed as "Healthy".

![CleanShot 2022-06-09 at 17 45 46@2x](https://user-images.githubusercontent.com/842974/172900566-2b7f558f-2fc4-4d8f-8102-e83e2951cc87.png)
![CleanShot 2022-06-09 at 17 46 01@2x](https://user-images.githubusercontent.com/842974/172900608-adfbe1df-bc43-4005-8e0a-df6af35fda73.png)

The ASG has "EC2 & ELB" Health Checks enabled.

![CleanShot 2022-06-09 at 17 46 31@2x](https://user-images.githubusercontent.com/842974/172900711-e3076075-72e0-42e6-841f-94146185422a.png)

And you can see that they're all listed as "InService" and "Healthy" in the ASG Instance Management tab.

![CleanShot 2022-06-09 at 17 46 46@2x](https://user-images.githubusercontent.com/842974/172900817-bb7b79da-11b6-4158-bbfc-b2bd510fd519.png)

The configuration for the Health Check is as the Emissary CRDs configured it.

![CleanShot 2022-06-09 at 17 47 27@2x](https://user-images.githubusercontent.com/842974/172900898-cc46111e-ff7b-4d6c-9cfb-936461a803b9.png)

However you can see that none of the instances are listed as "InService" 

![CleanShot 2022-06-09 at 17 47 34@2x](https://user-images.githubusercontent.com/842974/172900952-4804af7d-97df-4ac0-ae10-261de4c48cbd.png)

---

I am using the Default Listeners, as well as 1 additional Listener, Host and Mapping.

These are the Defaults:

```
NAME                              PORT   PROTOCOL   STACK   STATSPREFIX   SECURITY   L7DEPTH
emissary-ingress-http-listener    8080   HTTP                             XFP
emissary-ingress-https-listener   8443   HTTPS                            XFP
```

The services they produced:

```
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP                                                                PORT(S)                      AGE
emissary-ingress         LoadBalancer   172.20.66.102   xxx-xxx.eu-north-1.elb.amazonaws.com   80:31042/TCP,443:32030/TCP   6h7m
emissary-ingress-admin   ClusterIP      172.20.66.215   <none>                                                                     8877/TCP,8005/TCP            6h7m
emissary-ingress-agent   ClusterIP      172.20.193.30   <none>                                                                     80/TCP                       6h7m
```

This is my own listener:

```
NAME                     PORT   PROTOCOL   STACK   STATSPREFIX        SECURITY   L7DEPTH
code-test-cakery-http    8080   HTTPS              code-test-cakery   XFP        0
code-test-cakery-https   8443   HTTPS              code-test-cakery   XFP        0
```

Created by the following config:

```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: {{ .Chart.Name }}-host
  labels:
    labels.getambassador.io/hostname: {{ .Values.ingress.host }}
spec:
  hostname: {{ .Values.ingress.host }}
  tlsSecret:
    name: {{ .Values.ingress.host }}-tls
  requestPolicy:
    insecure:
      action: Redirect
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ .Chart.Name }}-http
  labels:
    labels.getambassador.io/listener: {{ .Values.ingress.host }}-80
spec:
  port: 8080
  protocol: HTTPS
  securityModel: XFP
  statsPrefix: {{ .Chart.Name }}
  l7Depth: 0
  hostBinding:
    namespace:
      from: SELF
    selector:
      matchLabels:
        labels.getambassador.io/hostname: {{ .Values.ingress.host }}
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ .Chart.Name }}-https
  labels:
    labels.getambassador.io/listener: {{ .Values.ingress.host }}-443
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  statsPrefix: {{ .Chart.Name }}
  l7Depth: 0
  hostBinding:
    namespace:
      from: SELF
    selector:
      matchLabels:
        labels.getambassador.io/hostname: {{ .Values.ingress.host }}
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  {{ .Chart.Name }}-mapping
spec:
  service: {{ .Chart.Name }}.{{ .Chart.Name }}:80
  timeout_ms: 3000
  connect_timeout_ms: 3000
  retry_policy:
    retry_on: 5xx
    num_retries: 1
    per_try_timeout: 0.150s
  hostname: {{ .Values.ingress.host }}
  prefix: "/"
```

**Versions (please complete the following information):**
 - Emissary Ingress: 2.3.0 (Helm Chart 7.4.0)
 - Kubernetes environment: EKS
 - Kubernetes Version: 1.21
