### ISSUE TITLE
Extending --demo mode with a new official --dev mode

### ISSUE THREAD

**Issue by Reris** [emissary-ingress/emissary#4278]
**Please describe your use case / problem.**
My main reason of using emissary - starting with ambassador a few years ago - was because it was able to develop pure local docker container with docker-compose and full visual studio support.

In the early days it was easy to create a docker-compose.yaml with ambassador gateway api just by defining an environment with all the mappings, certificates etc and develop a full (1-replica) microservice environment without minikube, kind, etc.
Starting with ambassador 1.11.2 there was a minor CRD fix which made this harder. But still possible with AMBASSADOR_NO_KUBE environment var. (Didnt test it due to a lack of time, I kept stuck with v0.43).

But now, with emissary-ingress, i got it running again with 2.3.1 using --demo mode and it works pretty good using a docker-compose like:
```
  emissary-ingress:
    container_name: emissary-ingress
    image: docker.io/emissaryingress/emissary:2.3.1
    command:
      - --demo
    restart: always
    ports:
      # Look at https://localhost:18453/ambassador/v0/diag/
      - "18453:8443"
    volumes:
      - ./ambassador-config:/ambassador/ambassador-demo-config
```
with a local folder "ambassador-config" which contains Host, Listener AND "/default/secrets/tls-secret.yaml" to support TLS-termination. **Nice!** 😀

This way I get:
- a pure local docker desktop development environment
- TLS Termination
- quite the same mappings like those i use in the production environment (K8s)
- Full IDE support
- No container registries needed

**BUT**
Its a hack. 🪳
And i would like to have it supported by this project, because it makes life so much easier.
I think this would be a feature for other developers too, like described in a stackoverflow question not asked by me:
https://stackoverflow.com/questions/65249193/run-ambassador-in-local-dev-environment-without-kubernetes

**Describe the solution you'd like**
❤️ Make alternative "--dev" command line argument which behaves just like --demo but:
- without starting any qotm/... services
- reads the config from "ambassador/ambassador-config" or "ambassador/ambassador-dev-config"

**Describe alternatives you've considered**
I've got 2 alternatives:
1. Keep --demo mode but be afraid of every update :)
2. Use kind to build a local K8s with lots of additional dependencies
