### ISSUE TITLE
Mapping matches more Hosts than it should with mapping selector

### ISSUE THREAD

**Issue by f-herceg** [emissary-ingress/emissary#4316]
**Describe the bug**
If I leave `host` field empty in my Mapping then instead of Mapping not matching any Hosts, it matches all of the Hosts.

**To Reproduce**
Create any mapping without setting `host` field.
Create multiple Host resources.
Mapping is available on all hostnames.

**Expected behavior**
Mapping unavailable on any hostname.

**Versions (please complete the following information):**
 - Kubernetes environment: kOps cluster
 - Emissary-ingress: 3.0.0 and also 2.3.1

**Additional context**
MappingSelector, also doesn't seem to work. 
This documentation seems completely wrong https://www.getambassador.io/docs/emissary/latest/topics/running/host-crd/#controlling-association-with-mappings since not setting `host` field in Mapping will match any Host there is in cluster regardless of mappingSelector.

My Mapping:
```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app: test-nginx
  name: test-nginx
  namespace: test-nginx
spec:
  host: ""
  prefix: /test/
  service: test-nginx
```
My Host1 which should route to Mapping:
```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: test-nginx-fh-correct
  namespace: emissary
spec:
  hostname: test.something.io
  mappingSelector:
    matchLabels:
      app: test-nginx
  requestPolicy:
    insecure:
      action: Route
status: {}
```
My Host2 which shouldn't route to Mapping but it does.
```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: test-nginx-fh-wrong
  namespace: emissary
spec:
  hostname: wrong.something.io
  mappingSelector:
    matchLabels:
      app: definitely-dont-match-this
  requestPolicy:
    insecure:
      action: Route
status: {}
```
