### ISSUE TITLE
upstream request timeout with ingress v1 when specifying backend.service.port.name

### ISSUE THREAD

**Issue by m-yosefpor** [emissary-ingress/emissary#4322]
**Describe the bug**

When specifiying ` backend.service.port.name` instead of ` backend.service.port.number`, emissary ingress will not function:

```
HTTP/1.1 504 Gateway Timeout
content-length: 24
content-type: text/plain
date: Fri, 08 Jul 2022 01:45:49 GMT
server: envoy

upstream request timeout
```

**To Reproduce**

1. create a simple pod/service/ingress.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test
spec:
  ingressClassName: ambassador
  rules:
  - host: test.example.com
    http:
      paths:
      - backend:
          service:
            name: my-service
            port:
              number: 8080 <<<<<< here
        path: /
        pathType: Prefix
```

This will work fine. Now change the `port.number` and use `port.name` in the service instead. emissary ingress will no longer work for that ingress.

**Expected behavior**

Service backends should work with either `port.number` and `port.name`.

**Versions (please complete the following information):**
 - Ambassador: 3.0.0
 - Kubernetes environment: openshift v4.10
 - Version k8s version 1.23

**Additional context**

I found a TODO here(https://github.com/emissary-ingress/emissary/blob/master/pkg/kates/k8s_resource_types/ingress.go#L20), not sure if it is causing this problem.

As k8s v1.23+ has deprecated and dropped support of ingress v1beta, supporting ingress v1 is essential.
