### ISSUE TITLE
Set-cookie header and custom headers are being passed down to upstream services when using emissary authservice.

### ISSUE THREAD

**Issue by alfrye** [emissary-ingress/emissary#4381]
**Describe the bug**
When emissary has the authservice module enabled for external authentication, any cookie 
or header that I set in my authservice does not make to the upstream service.

**To Reproduce**
1. Create an auth service server(installed in the kubernetes cluster) and in the authservice set cookie headers
2. add the following emissary configuration.

```
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: authentication
  namespace: api-gateway
spec:
  auth_service: "http://auth-service.blueframe:9000"
   path_prefix: "/bfauth"
  allowed_request_headers:
   - x-myheader
  allowed_authorization_headers:
   - set-cookie
   - x-myheader
```
  

4. use http navigate to upsteam service
5. inspect request headers 

**Expected behavior**
I would expect that the headers and cookie that I set in the auth service code will be included in the 
request set to the upstream service. 

**Versions (please complete the following information):**
 - Ambassador: emissary ingress 3.1.0
 - Kubernetes environment k3s
 - Version: 1.21.4

**Comment by alfrye** [comment]
From inside my cluster, I was able to bypass emissary by accessing the authentication endpoint using curl and was to see the headers being set.


```
Host: auth-service.blueframe:9000
> User-Agent: curl/7.55.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Set-Cookie: BLUEFRAME_SESSION=test+data+; Path=/; Max-Age=86400; HttpOnly; Secure
< X-Myheader: test
< Date: Fri, 05 Aug 2022 03:02:21 GMT
< Content-Length: 0
```

**Comment by alfrye** [comment]
Updated:
I enabled trace logs with in envoy and ran test again. I am able to see the set cookie in the envoy logs but in the browser 

`set-cookie', 'BLUEFRAME_SESSION=%7B%0A++++%22TokenResponse%22%3A+%7B%0A++++++++%22access_token%22%3A+%22eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzY2cyM21BRHlXeVpUVzdWcy00VWJaNS13TEtsSEI4UlhaU25oU0NYekhvIn0.eyJleHAiOjE2NTk3MTg5MDQsImlhdCI6MTY1OTcxODYwNCwiYXV0aF90aW1lIjoxNjU5NzE4NjA0LCJqdGkiOiJiYTM2NGY5MC00OWQ0LTRjYjYtOWQ1OS1mY2YwNzJhMDYzYTAiLCJpc3MiOiJodHRwczovLzEwLjM5LjgzLjI1My9hdXRoL3JlYWxtcy9ibHVlZnJhbWUiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiYjVmMTUwMjktZDMwYi00NmRhLThlNjEtNGM3NWZlM2Y5NjNmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiZGVtb2FwcCIsInNlc3Npb25fc3RhdGUiOiI5YjJlNWU5ZC1mYzEwLTRiNWMtOTUzZS0zODcyMmRlYTY3YTMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vMTAuMzkuODMuMjUzIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLWJsdWVmcmFtZSIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwic2lkIjoiOWIyZTVlOWQtZmMxMC00YjVjLTk1M2UtMzg3MjJkZWE2N2EzIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJBbGFuIEZyeWUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGFuIiwiZ2l2ZW5fbmFtZSI6IkFsYW4iLCJmYW1pbHlfbmFtZSI6IkZyeWUiLCJlbWFpbCI6ImFsYW5fZnJ5ZUBzZWxpbmMuY29tIn0.BP6LB_P27z5m4xByQuUNUdPUudu178XisYj-cbP6FXuKFPGD2mvlX8yNu-OOxUAVDoWq-6fDTnhqBhHHTFZlN5fZSGBKkNcoGlwxnOFpOPDFSjGHPgwxgjpyM__4D9Dwpp_QjwzuHdaSzGU--eQ9HwY3v-b1YwrNMPdtFpBgc5RAbKhXBqfEM3J0fm4_-HYuRlWp-cQjv4FEBw-u7l9Eg88LSuJKXCReMcdj-6jCzfK9hV-aU3pvtDHn0P9VBkqJZl_o5QGwhrPo2syMJd_xPaZHxLNXyQtAXZ6P4NpiIk7ffgY3Urd7VSJ_i6PmG5DJST2M6t8NibJV3ZrKT_nsdw%22%2C%0A++++++++%22token_type%22%3A+%22Bearer%22%2C%0A++++++++%22refresh_token%22%3A+%22eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI1OWY0Nzc0My1kYmIwLTQ5MTUtOGNiMS1lMGFlYjUxMzk3MGMifQ.eyJleHAiOjE2NTk3MjA0MDQsImlhdCI6MTY1OTcxODYwNCwianRpIjoiNzRlODVhMGYtZjA3Ny00Mjg1LTgwMmMtNjViZDE2MzA0ODFjIiwiaXNzIjoiaHR0cHM6Ly8xMC4zOS44My4yNTMvYXV0aC9yZWFsbXMvYmx1ZWZyYW1lIiwiYXVkIjoiaHR0cHM6Ly8xMC4zOS44My4yNTMvYXV0aC9yZWFsbXMvYmx1ZWZyYW1lIiwic3ViIjoiYjVmMTUwMjktZDMwYi00NmRhLThlNjEtNGM3NWZlM2Y5NjNmIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImRlbW9hcHAiLCJzZXNzaW9uX3N0YXRlIjoiOWIyZTVlOWQtZmMxMC00YjVjLTk1M2UtMzg3MjJkZWE2N2EzIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjliMmU1ZTlkLWZjMTAtNGI1Yy05NTNlLTM4NzIyZGVhNjdhMyJ9.3mo7h-OdBGYP6NPIIWnw_umLsnuY620Wr1oLDYk5PGY%22%2C%0A++++++++%22expiry%22%3A+%222022-08-05T17%3A01%3A44.550335699Z%22%0A++++%7D%2C%0A++++%22IDToken%22%3A+%7B%0A++++++++%22exp%22%3A+1659718904%2C%0A++++++++%22iat%22%3A+1659718604%2C%0A++++++++%22auth_time%22%3A+1659718604%2C%0A++++++++%22jti%22%3A+%2200ee64d0-4ac1-4320-aab6-bac44dd65829%22%2C%0A++++++++%22iss%22%3A+%22https%3A%2F%2F10.39.83.253%2Fauth%2Frealms%2Fblueframe%22%2C%0A++++++++%22aud%22%3A+%22demoapp%22%2C%0A++++++++%22sub%22%3A+%22b5f15029-d30b-46da-8e61-4c75fe3f963f%22%2C%0A++++++++%22typ%22%3A+%22ID%22%2C%0A++++++++%22azp%22%3A+%22demoapp%22%2C%0A++++++++%22session_state%22%3A+%229b2e5e9d-fc10-4b5c-953e-38722dea67a3%22%2C%0A++++++++%22at_hash%22%3A+%22U-p0-bLr2nV7sZBtoi98WQ%22%2C%0A++++++++%22acr%22%3A+%221%22%2C%0A++++++++%22sid%22%3A+%229b2e5e9d-fc10-4b5c-953e-38722dea67a3%22%2C%0A++++++++%22email_verified%22%3A+true%2C%0A++++++++%22name%22%3A+%22Alan+Frye%22%2C%0A++++++++%22preferred_username%22%3A+%22alan%22%2C%0A++++++++%22given_name%22%3A+%22Alan%22%2C%0A++++++++%22family_name%22%3A+%22Frye%22%2C%0A++++++++%22email%22%3A+%22alan_frye%40selinc.com%22%0A++++%7D%0A%7D; Path=/; Max-Age=86400; HttpOnly; Secure'`

**Comment by cindymullins-dw** [comment]
@alfrye, in the Module config can you try including `exposed_headers` (example below) in addition to `allowed_headers`?  For use with set_cookie it looks like you’ll need both of these in your Module.

```
cors:
        credentials: true
        exposed_headers:
        - Set-Cookie
        headers:
        - Set-Cookie

```
It also seems that set_cookie is very particular and that you may need to add some CORS/set_cookie logit to your application as well.  Please see [this link ](https://www.mezhenskyi.dev/blog/post/CORS%20Policy%20%26%20Set-Cookie%20Explained)for more context.

**Comment by alfrye** [comment]
After adding cors config, I am still not getting the cookie header. my update mapping looks like this 

```
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: demoapp-mapping
  namespace: demo
spec:
  prefix: /demoapp/status/
  rewrite: /status
  cors:
    origins: https://10.39.83.253
    methods: POST, GET, OPTIONS
    headers:
    - set-cookie
    credentials: true
    exposed_headers:
    - X-Custom-Header
    - set-cookie
    - x-myheader
    max_age: "86400"
  service: http://demoapp.demo:8585
  #bypass_auth: true

```
Next Step:
I am going put together a sample code setup that I can share in order for us to troubleshoot this further.
