### ISSUE TITLE
After upgrading Ambassador 1.14.3 > 2.3.2 calls that go via an external Nginx proxy fail with 502

### ISSUE THREAD

**Issue by santrada** [emissary-ingress/emissary#4422]
**Describe the bug**
After upgrading Ambassador 1.14.3 > 2.3.2 requests that go via an Nginx proxy return 502

**To Reproduce**
- Installed 1.14.3
- Upgraded to 2.3.2 via the docs
- Configured HTTPS listener as follows

```
- apiVersion: getambassador.io/v3alpha1
  kind: Listener
  metadata:
    name: ambassador-https-listener
    namespace: ambassador
  spec:
    hostBinding:
      namespace:
        from: ALL
    port: 8443
    protocolStack:
    - PROXY
    - TLS
    - HTTP
    - TCP
    securityModel: XFP
```

**Expected behavior**
The requests should go through with 200 status code

**Versions:**
 - Ambassador: 2.3.2
 - Kubernetes environment AWS EKS
 - Version 1.21

**Additional context**
Th proxy lives in a different EKS Cluster, so the network flow is
Proxy Ambassador NLB > Ambassador 1.14.3 > Nginx proxy > Upgraded Emissary Ingress NLB > Emissary Ingress 2.3.2

Nginx logs show the following:
```
2022/08/18 18:55:45 [error] 7#7: *28151 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: <someclient>, server: , request: "GET /<somepath> HTTP/1.1", upstream: "https://<somepath>", host: "<somehost>", referrer: "<somereferrer>"
```

Appreciate your help 🙏
