### ISSUE TITLE
apiext force-downgrading my Module resource

### ISSUE THREAD

**Issue by jamesloosli** [emissary-ingress/emissary#4467]
**Describe the bug**
I'm attempting to configure emissary with an ambassador_id, but when I push a manifest containing that key with the version `v3alpha1`, the api extension downgrades my manifest version and puts the following in place instead;

```yaml
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--emissary
```

**To Reproduce**
1. Install v3.1.0 CRDs + Api Extension from https://app.getambassador.io/yaml/emissary/3.1.0/emissary-crds.yaml
2. Wait for api extensions to start
3. Apply a Module manifest containing `ambassador_id`
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  labels:
    app.kubernetes.io/component: emissary-ingress-ratelimit
    app.kubernetes.io/instance: emissary-ingress
    app.kubernetes.io/name: emissary-ingress
    app.kubernetes.io/part-of: emissary-ingress
    product: aes
  name: ambassador
  namespace: emissary
spec:
  ambassador_id:
  - emissary
```
5. Describe the module, wail in dispair
```
❯ k --context nonprod-us-west-2 -n emissary describe module ambassador
Name:         ambassador
Namespace:    emissary
Labels:       app.kubernetes.io/component=emissary-ingress-ratelimit
              app.kubernetes.io/instance=emissary-ingress
              app.kubernetes.io/name=emissary-ingress
              app.kubernetes.io/part-of=emissary-ingress
              kustomize.toolkit.fluxcd.io/name=emissary
              kustomize.toolkit.fluxcd.io/namespace=flux-system
              product=aes
Annotations:  <none>
API Version:  getambassador.io/v2
Kind:         Module
Metadata:
  Creation Timestamp:  2022-08-27T00:11:24Z
  Generation:          1
  Managed Fields:
    API Version:  getambassador.io/v3alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:app.kubernetes.io/component:
          f:app.kubernetes.io/instance:
          f:app.kubernetes.io/name:
          f:app.kubernetes.io/part-of:
          f:kustomize.toolkit.fluxcd.io/name:
          f:kustomize.toolkit.fluxcd.io/namespace:
          f:product:
      f:spec:
        f:ambassador_id:
        f:config:
          f:cors:
          f:enable_grpc_web:
          f:envoy_log_format:
          f:timeout_ms:
          f:use_proxy_proto:
          f:use_remote_address:
    Manager:         kustomize-controller
    Operation:       Apply
    Time:            2022-08-27T00:11:24Z
  Resource Version:  263373010
  UID:               a3ea041b-acd9-4fbf-970a-be760378b724
Spec:
  ambassador_id:
    --apiVersion-v3alpha1-only--emissary
Events:                  <none>
```

**Expected behavior**
I'm not getting any traffic at all to emissary because of this. I'm in a big of a compromised situation because we have another older ambassador install running (1.13.9), so I have to use ambassador_id to force traffic for the new mappings/hosts/tracingservice resources to the new emissary pods. I expected the documentation found here to work; https://www.getambassador.io/docs/emissary/latest/topics/running/running/#ambassador_id

**Versions (please complete the following information):**
 - Emissary 3.1.0
 - EKS 1.22.10

**Additional context**
