### ISSUE TITLE
Mappings in same path matched by different mapping selector in Host doesn't work

### ISSUE THREAD

**Issue by f-herceg** [emissary-ingress/emissary#4468]
This might not be a bug but I'm not sure.

**Describe the bug**
When using a mapping selector in Host resource it's not possible to have Mappings with the same path even if they match different hosts.

When specifying hostname in mapping then it works as expected.

**To Reproduce**
1. Create 2 identical namespaces. Same deployment, same service, mappings with the same paths but different labels and 2 different hosts with mapping selector.
Namespace 1:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emissary-debug
  namespace: emissary-debug-ns-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emissary-debug
  template:
    metadata:
      labels:
        app: emissary-debug
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: emissary-debug
  namespace: emissary-debug-ns-1
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: emissary-debug
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    key: value1
  name: emissary-debug
  namespace: emissary-debug-ns-1
spec:
  prefix: /hello/
  rewrite: /
  service: emissary-debug.emissary-debug-ns-1
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: host-one
  namespace: emissary
spec:
  hostname: one.hostname.com
  requestPolicy:
    insecure:
      action: Route
  selector:
    matchLabels:
      key: value1
```
Namespace 2:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emissary-debug
  namespace: emissary-debug-ns-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emissary-debug
  template:
    metadata:
      labels:
        app: emissary-debug
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: emissary-debug
  namespace: emissary-debug-ns-2
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: emissary-debug
  type: ClusterIP
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    key: value2
  name: emissary-debug
  namespace: emissary-debug-ns-2
spec:
  prefix: /hello/
  rewrite: /
  service: emissary-debug.emissary-debug-ns-2
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: host-two
  namespace: emissary
spec:
  hostname: two.hostname.com
  requestPolicy:
    insecure:
      action: Route
  selector:
    matchLabels:
      key: value2
```

**Expected behavior**
Both routes are created and querying `one.hostname.com/hello/` and `two.hostname.com/hello/` both return responses.

**Observed behavior**
One mapping works but other doesn't. I'd say this is a bug because when I set hostnames in mapping resources then they are both routed as I would expect so this behavior isn't consistent between 2 different features.

**Versions (please complete the following information):**
 - Emissary Ingress: v3.0.0
 - Kubernetes environment: kOps cluster on AWS 
 - Kubernetes Version: 1.24.x

**Additional context**
I've tried multiple combinations of resources by setting different mapping names, and different service names, but the only thing that works is setting a different path.
