### ISSUE TITLE
Suprising value for `ambassador_id`

### ISSUE THREAD

**Issue by ghostsquad** [emissary-ingress/emissary#4511]
**Describe the bug**
```
kubectl edit mapping diagnostics-default
```

This value doesn't match what is set with kubectl apply. Why is it changed?

```yaml
...
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
```
