### ISSUE TITLE
envoy_log_type: "json" seems to not work

### ISSUE THREAD

**Issue by ghostsquad** [emissary-ingress/emissary#4536]
**Describe the bug**
setting `envoy_log_type` to `"json"` and setting an object for `envoy_log_format` does not appear to take effect. Access logs are still formatted as text.

**To Reproduce**

`module`

```
k -n ambassador get module ambassador-edge-public -o yaml
```

```
apiVersion: getambassador.io/v2
kind: Module
metadata:
  labels:
    a8r.io/ambassador-id: public
    app: ambassador
    app.kubernetes.io/component: edge-public
    app.kubernetes.io/name: ambassador-edge-public
    app.kubernetes.io/part-of: ambassador
  name: ambassador-edge-public
  namespace: ambassador
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--public
  config:
    diagnostics:
      allow_non_local: true
      enabled: false
    envoy_log_format:
      '@timestamp': '%START_TIME%'
      client:
        address: '%DOWNSTREAM_REMOTE_ADDRESS%'
        certificate:
          local:
            subject: '%DOWNSTREAM_LOCAL_SUBJECT%'
            uri_san: '%DOWNSTREAM_LOCAL_URI_SAN%'
          peer:
            cert_v_end: '%DOWNSTREAM_PEER_CERT_V_END%'
            cert_v_start: '%DOWNSTREAM_PEER_CERT_V_START%'
            certificate: '%DOWNSTREAM_PEER_CERT%'
            issuer: '%DOWNSTREAM_PEER_ISSUER%'
            serial: '%DOWNSTREAM_PEER_SERIAL%'
            uri_san: '%DOWNSTREAM_PEER_URI_SAN%'
        direct:
          remote:
            address: '%DOWNSTREAM_DIRECT_REMOTE_ADDRESS%'
        local:
          address: '%DOWNSTREAM_LOCAL_ADDRESS%'
        remote:
          address_no_port: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
        sni: '%REQUESTED_SERVER_NAME%'
        tls:
          cipher: '%DOWNSTREAM_TLS_CIPHER%'
          session_id: '%DOWNSTREAM_TLS_SESSION_ID%'
          version: '%DOWNSTREAM_TLS_VERSION%'
      envoy:
        route:
          name: '%ROUTE_NAME%'
        upstream:
          cluster: '%UPSTREAM_CLUSTER%'
          localaddress: '%UPSTREAM_LOCAL_ADDRESS%'
          transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
      host:
        hostname: '%HOSTNAME%'
      http:
        request:
          body:
            bytes: '%BYTES_RECEIVED%'
          duration: '%DURATION%'
          duration_req: '%REQUEST_DURATION%'
          headers:
            accept: '%REQ(ACCEPT)%'
            authority: '%REQ(:AUTHORITY)%'
            content-length: '%REQ(CONTENT-LENGTH)%'
            content-type: '%REQ(CONTENT-TYPE)%'
            correlation-id: '%REQ(CORRELATION-ID)%'
            host: '%REQ(HOST)%'
            id: '%REQ(X-REQUEST-ID)%'
            session-id: '%REQ(SESSION-ID)%'
            x_b3_parentspanid: '%REQ(X-B3-PARENTSPANID)%'
            x_b3_sampled: '%REQ(X-B3-SAMPLED)%'
            x_b3_spanid: '%REQ(X-B3-SPANID)%'
            x_b3_traceid: '%REQ(X-B3-TRACEID)%'
            x_envoy_decorator_operation: '%REQ(X-ENVOY-DECORATOR-OPERATION)%'
            x_envoy_expected_rq_timeout_ms: '%REQ(X-ENVOY-EXPECTED-RQ-TIMEOUT-MS)%'
            x_envoy_internal: '%REQ(X-ENVOY-INTERNAL)%'
            x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
            x_forwarded_proto: '%REQ(X-FORWARDED-PROTO)%'
          method: '%REQ(:METHOD)%'
          path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
        response:
          body:
            bytes: '%BYTES_SENT%'
          duration_resp: '%RESPONSE_DURATION%'
          duration_tx: '%RESPONSE_TX_DURATION%'
          flags: '%RESPONSE_FLAGS%'
          headers:
            access-control-allow-origin: '%RESP(ACCESS-CONTROL-ALLOW-ORIGIN)%'
            content-length: '%RESP(CONTENT-LENGTH)%'
            content-type: '%RESP(CONTENT-TYPE)%'
            date: '%RESP(DATE)%'
            server: '%RESP(SERVER)%'
          status_code: '%RESPONSE_CODE%'
          status_code_details: '%RESPONSE_CODE_DETAILS%'
        version: '%PROTOCOL%'
      log:
        level: info
      network:
        direction: inbound
      server:
        address: '%UPSTREAM_HOST%'
      user_agent.name: '%REQ(USER-AGENT)%'
    envoy_log_type: json
    listener_idle_timeout_ms: 5000
    use_proxy_proto: true
```

I also tried restarting the pods, in case this module change required a pod restart.

**Expected behavior**

Envoy configuration is update to reflect json logging.

**Versions (please complete the following information):**
 - Ambassador: 3.1.0
 - Kubernetes environment: AWS EKS 1.21

**Additional context**
n/a
