### ISSUE TITLE
After token is refreshed, redirect back to the original origin if multiple origins are configured in the protectedOrigins

### ISSUE THREAD

**Issue by tylerelfering** [emissary-ingress/emissary#4592]
**Please describe your use case / problem.**
We have a lower env setup per team on the same domain that needs single sign on across multiple domains. We are accomplishing this with the oauth 2.0/jwt filters.

e.g. one team has services on the following origins
test1-app1.dev.net
test1-app2.dev.net
test1-app3.dev.net
...

Another team
test2-app1.dev.net
test2-app2.dev.net
test2-app3.dev.net
...

Currently we are applying the oauth2.0/jwt filter and policies per teams env as below to isolate the filters/policies per teams env.
```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: test1-oauth-filter
spec:
  ambassador_id: public
  OAuth2:
    authorizationURL: public
    clientID: id
    secret: secret
    maxStale: 24h
    protectedOrigins:
    - origin: test1-app1.dev.net
    - origin: test1-app2.dev.net
    - origin: test1-app3.dev.net
    accessTokenJWTFilter:
      name: test1-jwt-filter
```

The problem is having multiple domains on single sign is causing aes to redirect to the last configured domain in the protectedOrigins instead of the original origin the user was on. Example, after successfully authenticating and I go to test1-app2.dev.net, I'm on this origin until the access token expires which aes refreshes however im then redirected to test1-app3.dev.net. I would expect to be redirected back to the original origin I was on before aes intercepted the request to refresh the token. I see the network traffic doing the following:

```
-> original request test1-app2.dev.net/page1
test1-app1.dev.net/.ambassador/oauth2/multicookie?
test1-app2.dev.net/.ambassador/oauth2/multicookie?
test1-app3.dev.net/.ambassador/oauth2/multicookie?
-> redirects back to test1-app3.dev.net/page1 instead of test1-app2.dev.net/page1
```

**Describe the solution you'd like**
I would like aes to redirect to the original origin the user was on after it refreshes the access token.

**Describe alternatives you've considered**
Tried using one internal origin however needing to only have the filter's impact the specific teams env, we found the incoming requests were being tossed to random authorization url's not specific to the teams env.

**Additional context**
**Version**: AES v1.14
