### ISSUE TITLE
Hosts with a wildcard anywhere except the domain prefix fail.

### ISSUE THREAD

**Issue by jamesloosli** [emissary-ingress/emissary#4599]
**Describe the bug**
We're attempting to create a wildcard listener that works for a "regional" DNS entry as well as a "global" dns entry as follows;

api.somedomain.io (CNAME) api.green-us-west-2.somedomain.io
api.green-us-west-2.somedomain.io (R53AliasA) aws.nlb.amazonaws.com

To accomplish this, we created Hosts with entries like the following;
```yaml
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: api
  namespace: api-services
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  hostname: api.*
  selector:
    matchLabels:
      api_service_hostname: api
```

The matchLabel corresponds to several Mappings which should respond for both api.somedomain.io and api.green-us-west-2.somedomain.io. Those mappings omit the `spec.hostname` setting in order to work with both hostnames we're after.

With that configuration, envoy won't reconfigure and fails to start. When debugging what's going on, I went all the way down to the Envoy source to find where the error string I was seeing came from and found this; https://github.com/envoyproxy/envoy/blob/main/source/server/filter_chain_manager_impl.cc#L290

I have very little experience with C, but from what I can gather it looks like envoy only supports wildcard matchers for hosts where the wildcard is a prefix or simply `*` alone. The emissary docs for the Host CRD seem to imply that the wildcard can occur at any section of a domain as long as it doesn't break up a string, e,g, api.* or api.foo.*.

**To Reproduce**
1. Create a Host with a wildcard occurring anywhere except the prefix
2. Create a Mapping associated with that host without a given `hostname`
3. Watch the emissary logs and see a failure to reconfigure.
4. Wail in dispair.

**Expected behavior**
I'd expect behavior described in the Emissary documentation to reflect the actual configuration possibilities for the Emissary custom resources.

**Versions (please complete the following information):**
 - Ambassador: 2.2.2, 3.1.0
 - Kubernetes environment EKS
 - Version 1.22

**Additional context**
I'm going to attempt to remedy this by simply rendering out multiple `Host` resources, one for each domain. This will be a lot of duplication of code, but there's not a great alternative I can see.
