### ISSUE TITLE
Emissary loading a secret in a separate namespace doesn't work

### ISSUE THREAD

**Issue by wadexu007** [emissary-ingress/emissary#4637]
**Describe the bug**
We are running Emissary in `emissary-system` namespace and use a shared certificate in `secret` namespace to host all the secrets that also for Emissary to use.

**To Reproduce**
1. Install Last Emissary 3.2.0
2. use TLSContext
```
apiVersion: getambassador.io/v2
kind: TLSContext
  name: my-tls-context
  namespace: emissary-system
spec:
  ambassador_id: 
  - ambassador
  hosts:
  - '*.xxx.xx'
  min_tls_version: v1.2
  secret: tls-secret.secret
  secret_namespacing: true
```

use Host
```
apiVersion: getambassador.io/v2
kind: Host
spec:
  ambassador_id:
  - ambassador
  hostname: '*.xxx.xx'
  requestPolicy:
    insecure:
      action: Redirect
  tlsContext:
    name: my-tls-context
```

3.  Previously i use the same way in old Ambassador which works well. but today in Emissary, this doesn't work with below error
```
curl: (35) error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

I saw docs said The Host and the TLSContext must name the same Kubernetes Secret; if not, Emissary-ingress will disable TLS for the Host.

so now, i also configure Host with tlsSecret
```
apiVersion: getambassador.io/v2
kind: Host
spec:
  ......
  tlsContext:
    name: my-tls-context
  tlsSecret:
    name: tls-secret.secret
```

Errors:
```
2022-10-19 06:03:58 diagd 3.2.0 [P23TAEW] ERROR: Secret tls-secret.secret.emissary-system unknown
2022-10-19 06:03:58 diagd 3.2.0 [P23TAEW] ERROR: Host my-host-dev: invalid TLS secret tls-secret.secret, marking inactive
2022-10-19 06:03:58 diagd 3.2.0 [P23TAEW] INFO: -global-: <RichStatus BAD error='No Hosts defined, but TLSContexts exist that terminate TLS. The TLSContexts are being ignored.' hostname='my-emissary-emissary-ingress-7454578894-h5mjm' version='3.2.0'>
```
Change to 
```
  tlsSecret:
    name: tls-secret
```
Now errors change to
```
INFO: my-host-dev.emissary-system.1: <RichStatus BAD error='Secret info mismatch between Host my-host-dev (secret: tls-secret) and TLSContext my-tls-context: (secret: tls-secret.secret)' hostname='my-emissary-emissary-ingress-7454578894-h5mjm' version='3.2.0'>
2022-10-19 06:05:07 diagd 3.2.0 [P23TAEW] INFO: -global-: <RichStatus BAD error='No Hosts defined, but TLSContexts exist that terminate TLS. The TLSContexts are being ignored.' hostname='my-emissary-emissary-ingress-7454578894-h5mjm' version='3.2.0'>
```

**Expected behavior**
Secret can be loaded in a separate namespace in TLSContext. No need configure in Host again.

**Versions (please complete the following information):**
 - Emissary: 3.2.0
 - Kubernetes environment: GKE
 - Version 1.22

**Additional context**
Now i can't use secret in a different namespace. 
I only can create secret in same namespace with Emissary and configure TLSContext use `secret: tls-secret`
also configure Host use same secret to make it works.
```
  tlsSecret:
    name: tls-secret
```

**Comment by cindymullins-dw** [comment]
Hi @wadexu007, where you have your TLS secret can you try this syntax?  You’ll need this in the Host resource specifically.

tlsSecret:
    name: tls-secret
    namespace: secret

**Comment by wadexu007** [comment]
@cindymullins-dw Thank you for your reply. 

Host seems work. 
```
tlsSecret:
    name: tls-secret
    namespace: secret
```

What about TLSContext config, this flag `secret_namespacing` not work
```
apiVersion: getambassador.io/v2
kind: TLSContext
  name: my-tls-context
  namespace: emissary-system
spec:
  ambassador_id: 
  - ambassador
  hosts:
  - '*.xxx.xx'
  min_tls_version: v1.2
  secret: tls-secret.secret
  secret_namespacing: true
```

```
2022-10-23 00:50:02 diagd 3.2.0 [P22TAEW] ERROR: Secret tls-secret.secret.emissary unknown
2022-10-23 00:50:02 diagd 3.2.0 [P22TAEW] ERROR: Secret fallback-self-signed-cert.emissary unknown
```

**Comment by arista-marcin** [comment]
I tried different configuration option with especially the one suggested:

```
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: tlscontext
spec:
  ambassador_id:
  - proxy
  secret: test.com
  secret_namespacing: true
  alpn_protocols: "h2, http/1.1"
  hosts:
    - test.com
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: host
spec:
  ambassador_id:
  - proxy
  hostname: test.com
  requestPolicy:
    insecure:
      action: Redirect
  tlsSecret:
    name: test.com
    namespace: certs
  tlsContext:
    name: tlscontext
```

But it seems to be not respected in our setup:

Ambassador version 3.9.1
Kubernetes server Version: v1.24.17
Baremetal

```
emissary-ingress-qj6tt emissary-ingress 2024-01-09 14:25:40 diagd 3.9.1 [P37TAEW] ERROR: Secret test.com.certs.marcin unknown
emissary-ingress-qj6tt emissary-ingress 2024-01-09 14:25:40 diagd 3.9.1 [P37TAEW] INFO: host.marcin.1: <RichStatus BAD error='Secret info mismatch between Host host (secret: test.com.certs) and TLSContext tlscontext: (secret: test.com.certs)' hostname='****' version='3.9.1'>
emissary-ingress-qj6tt emissary-ingress 2024-01-09 14:25:42 diagd 3.9.1 [P37TAEW] INFO: error host.marcin.1 Secret info mismatch between Host host (secret: test.com.certs) and TLSContext tlscontext: (secret: test.com.certs)
```

Same setup is working properly when Secret is placed in the same namespace as Host and TLSContext

Already tried:
- secret_namespacing: false

as well as:
- secret: test.com.certs

None of my tests are working

Any advice? Am I doing that wrong? or there is a bug still here

**Comment by cindymullins-dw** [comment]
What happens if you remove `namespace: certs` from the Host's `tlsSecret`?  We don't specify that in our example, so I wonder if that is somehow interfering with the TLSContext being able to look across namespaces.  Can you try removing that but leave secret_namespacing: true on the TLSContext as is?

**Comment by arista-marcin** [comment]
and with that configuration I see following in the logs:
```
emissary-ingress-hfd7x emissary-ingress 2024-01-12 17:37:33 diagd 3.9.1 [P37TAEW] INFO: tlscontext.marcin.1: <RichStatus BAD error='TLSContext tlscontext found no certificate in secret test.com in namespace marcin, ignoring...' hostname='****' version='3.9.1'>
emissary-ingress-hfd7x emissary-ingress 2024-01-12 17:37:35 diagd 3.9.1 [P37TAEW] INFO: error tlscontext.marcin.1 TLSContext tlscontext found no certificate in secret test.com in namespace marcin, ignoring...
emissary-ingress-qb7dm emissary-ingress 2024-01-12 17:37:36 diagd 3.9.1 [P37TAEW] INFO: error tlscontext.marcin.1 TLSContext tlscontext found no certificate in secret test.com in namespace marcin, ignoring...
emissary-ingress-vcg2l emissary-ingress 2024-01-12 17:37:36 diagd 3.9.1 [P37TAEW] INFO: error tlscontext.marcin.1 TLSContext tlscontext found no certificate in secret test.com in namespace marcin, ignoring...
```

**Comment by arista-marcin** [comment]
Host only configuration (without connected TLSContext) is working fine though:
```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: host
spec:
  ambassador_id:
  - proxy
  hostname: test.com
  requestPolicy:
    insecure:
      action: Redirect
  tlsSecret:
    name: test.com
    namespace: certs
```
