### ISSUE TITLE
host_redirect not working as expected

### ISSUE THREAD

**Issue by niqdev** [emissary-ingress/emissary#4654]
**Describe the bug**
After bumping the version from 3.1.0 to 3.2.0 [redirects](https://www.getambassador.io/docs/emissary/latest/topics/using/redirects/) are always returning 404. By reverting the version everything works as expected

I've verified the [changelog](https://www.getambassador.io/docs/emissary/latest/release-notes/) and I don't clearly see what changes could have affected it.

Could you please help me to identify the issue?

**To Reproduce**

Example
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: emissary-ingress-host-root
spec:
  hostname: "example.com"
  mappingSelector:
    matchLabels:
      emissaryHost: emissary-host-root
  tlsSecret:
    name: certificate-letsencrypt-secret
  requestPolicy:
    insecure:
      action: Redirect

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: root-mapping
  labels:
    emissaryHost: emissary-host-root
spec:
  hostname: "example.com"
  prefix: /
  service: getambassador.io
  # this returns 404 in v3.2.0
  host_redirect: true
```

Please, let me know if you need more information

**Expected behavior**
`host_redirect` should works as expected

**Versions (please complete the following information):**
 - Ambassador: `3.2.0`
 - Kubernetes Version `1.24.4`

**Additional context**
None

**Comment by kriptor** [comment]
I have the same issue.
- AES 3.3.1
- K8S 1.25.4

The problem seems to be that the route for the mapping below is just not added to the envoy config for some reason. All routes for non-`host_redirect`-mappings are added to the envoy config correctly.

```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  labels:
    the-listener: my-https-listener
  name: root-host
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  hostname: example.com
  selector:
    matchLabels:
      my-host: root-host
  tlsContext:
    name: my-tlscontext
  tlsSecret:
    name: my-tlssecret
    namespace: ambassador
status:
  state: Ready
  tlsCertificateSource: Other

---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  labels:
    the-listener: my-https-listener
  name: subdomains-host
  namespace: ambassador
spec:
  acmeProvider:
    authority: none
  ambassador_id:
  - default
  hostname: '*.example.com'
  selector:
    matchLabels:
      my-host: subdomains-host
  tlsContext:
    name: my-tlscontext
  tlsSecret:
    name: my-tlssecret
    namespace: ambassador
status:
  state: Ready
  tlsCertificateSource: Other

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    my-host: subdomains-host
  name: www.example.com
  namespace: ambassador
spec:
  ambassador_id:
  - default
  hostname: www.example.com
  host_redirect: true
  prefix: /
  redirect_response_code: 301
  service: example.com

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    my-host: root-host
  name: example.com
  namespace: ambassador
spec:
  ambassador_id:
  - default
  connect_timeout_ms: 1000
  hostname: example.com
  prefix: /
  rewrite: /
  service: myservice.mynamespace:8080
  timeout_ms: 60000
```
