### ISSUE TITLE
envoy: remove usage of deprecated envoy configuration

### ISSUE THREAD

**Issue by LanceEa** [emissary-ingress/emissary#4664]
As part of our v3.Y series, we are committed to keeping up-to-date with the Envoy version that is shipped with Emissary-ingress. We have been doing this to ensure we can take advantage of bugfixes, performance enhancements and new features. Most importantly it ensures we are on a supported version that will get security patches from the Envoy team (_ this greatly reduces maintainer overhead_).

However, between Envoy versions they will deprecate a field and then eventually it will be removed in a future version. This coupled with our faster upgrade cadence means we need to be diligent on removing the usage of these deprecated fields.

This issue is to capture a list of the deprecated behaviors and fields that we need to update:

- [ ] remove usage of runtime flag`"envoy.reloadable_features.no_extension_lookup_by_name": false,`

TODO - collect list here

**Comment by zencircle** [comment]
Can these added as environment variables on the deployment ? If yes can someone please provide the variables. Thanks
```
apiVersion: apps/v1
kind: Deployment
spec:
    spec:
      containers:
          env:
            - name: AMBASSADOR_SINGLE_NAMESPACE
              value: 'YES'
```
