### ISSUE TITLE
Emissary Ingress - does not reread Istio certificates after a few days

### ISSUE THREAD

**Issue by szdonat** [emissary-ingress/emissary#4744]
**Describe the bug**
After integrating Emissary Ingress with Istio mTLS, 2 or 3 days later Emissary Ingress does not reread the TLS certificates coming from Istio any more and reports TLS error.
I found 2 quick fixes for the problem:
- restart Emissary Ingress with a cron job every day
- turn of diagnostics with the Helm parameter agent.reportDiagnostics: false, and adding a module with diagnostics.enabled: false and diagnostics.allow_non_local: false
 
**To Reproduce**
1. Install Emissary Ingress with Helm Chart and integrate mTLS with Istio, based on the documentation https://www.getambassador.io/docs/emissary/latest/howtos/istio
2. Wait 3 days
3. Cannot access Emissary Ingress, it reports TLS error
4. See error: upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436501:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_EXPIRED

**Expected behavior**
The Emissary Ingress - Istio integration should work at least for a week without turning diagnostics off.

**Versions (please complete the following information):**
 - Emissary Ingress: [3.3.0]
 - Emissary Ingress Chart: [8.3.0]
 - Kubernetes environment [bare metal, 1.21.8]
 - Istio [1.15.3]

**Additional context**
The Emissary Ingress - Istio integration always survives 36 hrs, the TLS problem comes after 2-3 day.
It is interesting that after turning off the diagnostics, I continue to see the Ambassador Diagnostic Overview page, but the integration survives for at least 8 days. I attached the values file used with the Helm Chart.
[values.yaml.txt](https://github.com/emissary-ingress/emissary/files/10185511/values.yaml.txt)

**Comment by LiVe** [comment]
Unfortunately this issue has been unresolved for quite a while :/

See for example:
https://github.com/emissary-ingress/emissary/issues/4484

**Comment by cindymullins-dw** [comment]
I believe we're aware of this issue and working on it.  Are you seeing any 503 errors?  Can you reproduce it consistently or able you able to output Ambassador pod logs /snapshot when it occurs?  Does it happen at the same time or at random intervals?  Any specs you can share with us to assist with replication would be helpful.

**Comment by LiVe** [comment]
@cindymullins-dw after the cert expires, the response is a 503 "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268436501:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_EXPIRED"

it can be reproduced consistently. for what its worth, it happens per default once a day. we're currently restarting the emissary pods once a day to work around this. but by reducing the secret ttl as mentioned above, the interval can be shortened.

I've updated our test environment to emissary 3.4.0 and it still shows the same error. If there is anything i can provide (logs or anything), i glady do so :)

**Comment by EamonKeane** [comment]
I believe I'm coming across the same issue. Adding some details on how to reproduce in case it helps.

1. Set the secret_ttl env var on the istio container:
```yaml
sidecarContainers:
  - name: istio-proxy
    env:
      - name: SECRET_TTL
        value: 1m
```
2. Restart the ambassador container and wait two minutes. Make a request to a resource and you will see similar to the below. 
```shell
curl --header "Authorization: Basic dXNlcm5hbWU6cGFzc3dvcmQ=" --insecure --verbose https://127.0.0.1:8443/backend/

....
* Connection #0 to host 127.0.0.1 left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure%
```
Note that if an existing connection is still in place, envoy does not re-validate the cert during the connection. To get around this, you can also set a destination rule to force a new connection, or restart the pods at the other end of the connection.
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: quote-rule
  namespace: quote
spec:
  host: quote.quote.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        connectTimeout: 30ms
        maxConnections: 100
        tcpKeepalive:
          interval: 500ms
          time: 1s
```

**Comment by szdonat** [comment]
Sorry for the late reply, this time my Emissary Ingress died only after 19 days. The logs are attached.
[emissary_error.txt](https://github.com/emissary-ingress/emissary/files/10536298/emissary_error.txt)

**Comment by EamonKeane** [comment]
Jotting down some additional observations on the issue in case it helps anyone.

Istio integration causing issues going from 1.14.4 to 2.5.1. 

This manifests itself in two ways:
* Initial valid cert at pod startup is read, but the update isn't seen, meaning pods have to be restarted (I have mitigated this by increasing cert lifetime to 90 days).

* During initial compilation of valid envoy snapshot, if the cert has not yet been saved into the shared in-memory directory by istio, emissary-ingress fails to compile a valid snapshot due to the missing cert. Provisioning of the cert occurs before emissary-ingress startup in a local cluster on my laptop, but not in EKS presumably due to additional network latency. Miliseconds later a cert is provisioned but emissary-ingress doesn't read it, and crucially doesn't restart the container, but stays in a ready state but without a valid envoy snapshot.

I don't have any good mitigations for the latter issue apart from perhaps forking the chart or docker image and over-riding the entrypoint to sleep for a few seconds. Or it also works if I add a random annotation to the tlscontext (like test: true) to cause a recompilation. Are there any suggestions on a clean way to get around this issue? (

**Comment by LiVe** [comment]
any update / workaround on this one?

**Comment by EamonKeane** [comment]
@LiVe for now I'm just sticking with 1.14.4 where it works fine.

My most hopeful solution is to use 90 days cert lifetime and for the startup race condition try `holdApplicationUntilProxyStarts` (an istio injection setting which, as I understand, injects istio-proxy container first in the pod manifest and also uses a `postStart` hook to delay the main container starting before istio-proxy is finished).

The below helm values works locally, I've yet to test it in EKS.

```yaml
podAnnotations:
  proxy.istio.io/config: |
    holdApplicationUntilProxyStarts: true
    proxyMetadata:
      OUTPUT_CERTS: /etc/istio-certs
  sidecar.istio.io/inject: "true"
  sidecar.istio.io/agentLogLevel: debug
  sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
  traffic.sidecar.istio.io/includeInboundPorts: ""
  traffic.sidecar.istio.io/includeOutboundIPRanges: ""
volumeMounts:
  - mountPath: /etc/istio-certs/
    name: istio-certs
volumes:
  - name: istio-certs
    emptyDir:
      medium: Memory
```
