### ISSUE TITLE
Configuration errors when multiple redirect mapping names contain dots with similar prefixes

### ISSUE THREAD

**Issue by cezarsa** [emissary-ingress/emissary#4879]
**Describe the bug**

When multiple redirect mappings contain names with dots `.` with a similar prefix (e.g `foo.1` and `foo.2`) ambassador will report the following error on the diagnostics page:
```
CONFIGURATION ERRORS
  foo.1.default.1: cannot accept foo.1 as second host_redirect after foo.1
```

**To Reproduce**

1. On a cluster with emissary-ingress installed but with no Mapping resources created apply the following yaml:
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: foo.1
  namespace: default
spec:
  host: source1.internal
  host_redirect: true
  prefix: /
  service: detination1.internal
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: foo.2
  namespace: default
spec:
  host: source2.internal
  host_redirect: true
  prefix: /
  service: detination2.internal
```

2. Apply another yaml file adding a simple proxy mapping, this step is important and I was only able to reliably trigger the error when this new mapping is applied AFTER the previous redirect mappings:
```yaml
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: anything
  namespace: default
spec:
  host: anything.internal
  prefix: /
  service: any.service
```

3. Open the diagnostics page at `http://<host>:8877/ambassador/v0/diag/` you may have to port-forward to the emissary-ingress pod to access it.

You should see the error:
```
CONFIGURATION ERRORS
  foo.1.default.1: cannot accept foo.1 as second host_redirect after foo.1
```
On the `Ambassador Route Table` section, there will be no entry for `http://source2.internal/` as should be expected.
Also, trying to hit emissary ingress will only return a redirect for the source1 hostname, not for the source2:
```sh
$ k port-forward svc/<emissary-ingress service> 8080:80 &

$ curl -H"Host: source1.internal" -w'%{http_code}' http://localhost:8080
301

$ curl -H"Host: source2.internal" -w'%{http_code}' http://localhost:8080
404
```

4. Now this is weird, after a while the error on the diagnostics page may stop ocurring. I'm not sure what triggers it to fix itself but we can make the error show up again by deleting the `anything` mapping added on step 2 and applying it again.

**Expected behavior**

I expected no errors to show up on the diagnostics page, both redirects to be listed under the `Ambassador Route Table` and emissary to return a proper redirect.

**Versions (please complete the following information):**
 - Ambassador: `gcr.io/datawire/emissary:3.4.0`
 - Kubernetes environment: AWS EKS
 - Version: v1.22.16-eks-ffeb93d

**Additional context**
