### ISSUE TITLE
AuthService backend request should use the provided URL as Host header, or allow overriding it

### ISSUE THREAD

**Issue by lorenzo-biava** [emissary-ingress/emissary#4899]
**Describe the bug**

Looks like AuthService resolves the DNS name to an IP and makes a call to that IP, but the injects the Host header (authority) of the external request.

In certain use cases, like a service mesh, the host header must be the one of the actual auth service backend, and without it the request is misrouted.

**To Reproduce**

**Expected behavior**

The Host header provided in the request made to the auth service is the original from the provided AuthService URL.
As an alternative, an explicit override field should be provided (similarly to the Mapping's `host_rewrite`).

**Versions (please complete the following information):**
 - Ambassador: 3.5.1
 - Kubernetes environment [e.g. Minikube, bare metal, Google Kubernetes Engine]
 - Version [e.g. 1.8.1]

**Additional context**

```
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
  namespace: ingress-controllers
spec:
  ambassador_id: [ "ambassador-internal" ]
  auth_service: oauth2-proxy.ingress-controllers
  path_prefix: ""
  proto: http
  tls: false
```

```
[2023-03-02 17:11:27.290][43][debug][router] [source/common/router/router.cc:470] [C0][S8394578190331705916] cluster 'cluster_extauth_http___oauth2_proxy_ingr-CC0A4911B63FBAA6-0' match for URL '/ambassador/v0/diag/?test'
[2023-03-02 17:11:27.290][43][debug][router] [source/common/router/router.cc:678] [C0][S8394578190331705916] router decoding headers:
':authority', 'xinfra-ci-lorenzo.xxxxxx' ===> This should be 'oauth2-proxy.ingress-controllers'
':path', '/ambassador/v0/diag/?test'
':method', 'GET'
':scheme', 'https'
'content-length', '0'
'user-agent', 'Mozilla/5.0 xxxx'
'x-forwarded-for', '10.xxxx'
'x-forwarded-proto', 'https'
'x-b3-traceid', 'a1c1a6583312a6af8f55c8bc0b164263'
'x-b3-spanid', 'fdd9be16c0297059'
'x-b3-parentspanid', '8f55c8bc0b164263'
'x-b3-sampled', '1'
'x-envoy-internal', 'true'
'x-envoy-expected-rq-timeout-ms', '5000'
```
