### ISSUE TITLE
JWT Filter not working with Okta JWT

### ISSUE THREAD

**Issue by TechnoChimp** [emissary-ingress/emissary#4900]
I'm using the Node package '@openid/appauth' in an Electron app to handle the Okta auth flow and get tokens. (accessToken, idToken, and refreshToken)

I've setup a JWT filter in EdgeStack:
```
apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: okta-jwt-filter
  namespace: ambassador
spec:
  JWT:
    errorResponse:
      bodyTemplate: |-
        {
          "message": {{ .message | json "" }}
        }
      realm: ""
    insecureTLS: false
    issuer: https://<redacted>
    jwksURI: https://<redacted>/oauth2/v1/keys
    leewayForExpiresAt: 0s
    leewayForIssuedAt: 0s
    leewayForNotBefore: 0s
    renegotiateTLS: never
    requireAudience: false
    requireExpiresAt: true
    requireIssuedAt: true
    requireIssuer: true
    requireNotBefore: false
    v3MaxStale: 0s
    validAlgorithms:
    - RS256
   ```
When I test my endpoint using my accessToken, I get this error:
```
{
    "message": "Token validation error: token is invalid: errorFlags=0x00000002=(ValidationErrorUnverifiable) wrappedError=(KeyID=\"Js7bDL65LcN3DbrfoicbcxOWNIKm4KpaLCJFM9oI1xs\": JWK not found)"
}
```

When I check the Okta JWK endpoint I see that the KID of this accessToken in fact is not there, however the Okta JWK endpoint does have the KID for the idToken, so when I try that one, I now get this error instead:

```
{
    "message": "missing required scope values: [\"openid\" \"profile\"]"
}
```

When I take a look at the JWT content, I see that the scopes section is indeed missing.

So, how can this work with an Okta JWT when:

1. The access token has the required scope fields, but the JWK endpoint does not include this tokens KID
2. The id token's KID is listed in the JWK endpoint, but is missing the required scopes field

Thanks!

-Tommy
