### ISSUE TITLE
Emissary not showing content when hit the URL

### ISSUE THREAD

**Issue by faizananwar532** [emissary-ingress/emissary#4913]
Before using emissary we were using Ambassador as our API gateway but we wanted to shift to Emissary-ingress so we follow the same architecture we were using for Ambassador i.e.  we had Nginx ingress in our EKS, then deployed Ambassador as a chart dependency within our application's helm chart, the ingress resource of our chart is the place where we set the above host(URL). 

Now I have setup the Emissary-ingress as per the documentation with same architecture, EKS (version: 1.24), Nginx deployed within our cluster as Network loadbalancer(NLB) and followed by the instructions given by Emissary i.e. Install the Emissary-ingress CRDs. in emissary-system namespace, add Emissary-ingress our application chart dependency, with host, listener and mapping resource. Everything was successfully deployed and pods are running fine but I am unable to get any content when I visit the URL.  

My configs are as follow:

### Host
```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: minimal-host
spec:
  hostname: {{ .Values.hostnames.emissary | quote }}
  mappingSelector:
    matchLabels:
      testhost: hostemissary

```
### Listener
```
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ template "relname" . }}-http-listener
spec:
  port: 8080                     
  protocol: HTTP             
  securityModel: XFP          
  statsPrefix: http-listener  
  l7Depth: 0                  
  hostBinding:
    namespace:
      from: ALL               
    # selector: host


apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: {{ template "relname" . }}-https-listener
spec:
  port: 8443                     
  protocol: HTTPS                
  securityModel: XFP             
  statsPrefix: https-listener  
  l7Depth: 0                   
  hostBinding:
    namespace:
      from: ALL                
    # selector: host
```

### AuthService
```
apiVersion: getambassador.io/v3alpha1
kind:  AuthService
metadata:
  name: {{ template "relname" . }}-sternguard-verify
  labels:
    testhost: hostemissary
spec:
  auth_service: {{ template "relname" . }}-sternguard
  path_prefix: "/v1/rbac/check"
  allowed_request_headers:
    - Origin
  allowed_authorization_headers:
    - "user"
    - "tenant-id"
    - "user-id"
    - "role"

```
### Mapping
```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: {{ template "relname" . }}-unauthenticated-endpoints
  labels:
    testhost: hostemissary
spec:
  prefix: /v1/auth/
  rewrite: ""
  service: {{ template "relname" . }}-sternguard
  bypass_auth: true
```

### Chart dependency
```
dependencies:
    - name: emissary-ingress
      version: 8.5.0
      repository: https://www.getambassador.io/
      condition: emissary-ingress.install
```

The status of emissary pods are as follow:
```
tf-pr169-emissary-ingress-568b98f7bf-nvmrv         1/1     Running     0          7d
tf-pr169-emissary-ingress-agent-698466dc46-9z2vg   1/1     Running     0          7d
```

The url is: https://pr169-app.crewnetics.com/

Is there anything I am missing? because as per the logs of emissary there don't seems to be an issue with its installation!
