### ISSUE TITLE
TLS certs cannot be provided via file alone

### ISSUE THREAD

**Issue by ianunruh** [emissary-ingress/emissary#4939]
**Describe the bug**

When configuring the TLS certificate to use for termination, it appears that file-based TLS certificates are silently ignored. Specifically, the `cert_chain_file` and `private_key_file` options.

https://www.getambassador.io/docs/emissary/3.2/topics/running/tls#advanced-tls-configuration-with-the-host
https://www.getambassador.io/docs/emissary/3.2/topics/running/tls#tlscontext

When passing this same TLS certificate/key combination through a K8s secret, it correctly populates the host's TLS context. However, we cannot use K8s secrets for this purpose and must read them solely off disk.

**To Reproduce**

Create a basic Host resource with only a reference to a TLSContext with file paths set:

```
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: demo
spec:
  hostname: demo.example.com
  tlsContext:
    name: identity
---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: identity
spec:
  hosts: ["*"]
  cert_chain_file: /path/to/identity.cert
  private_key_file: /path/to/identity.key
```

The TLSContext is handled correctly, I see it represented in `ir.json` with the expected values.

However, the host does not end up with the `context` key populated correctly:

```
  "hosts": [
    {
      "_active": true,
      "_errored": false,
      "_referenced_by": [
        "demo.traffic-ingress.1"
      ],
      "_rkey": "demo.traffic-ingress.1",
      "hostname": "demo.example.com",
      "insecure_action": "Redirect",
      "kind": "Host",
      "location": "demo.traffic-ingress.1",
      "metadata_labels": {
        "ambassador_crd": "demo.traffic-ingress"
      },
      "name": "demo",
      "namespace": "traffic-ingress",
      "secure_action": "Route",
      "tls": {
        "min_tls_version": "v1.2"
      },
      "tlsContext": {
        "name": "identity"
      }
    }
```

**Expected behavior**

I expect that the `ir.json` is generated with the host's `context` field populated with references to my TLS certificates on disk, similarly to how it does with TLS certs placed on disk from K8s secrets. I would also expect the same to work if I provided the cert_chain_file/private_key_file options through the host's `tls` field, if provided instead of the `tlsContext`.

**Versions (please complete the following information):**

- Emissary v3.2.0
- Kubernetes v1.20.15 on bare metal

**Additional context**

It seems that this is the problematic code path: https://github.com/emissary-ingress/emissary/blob/v3.2.0/python/ambassador/ir/irhost.py#LL94

The code that would be calling `save_context` for a host's TLSContext only does so when a `tlsSecret` is provided.

I believe this bug is still present in the latest Emissary, as there wasn't any relevant changes to that part of the code since v3.2.0.
