### ISSUE TITLE
Module configured`liveness_probe` is hitting the AuthService

### ISSUE THREAD

**Issue by joshbranham** [emissary-ingress/emissary#4948]
**Describe the bug**
When using the `liveness_probe: true` config in `kind: Module`, traffic to the `/ambassador/v0/check_alive` path (served from [here](https://github.com/emissary-ingress/emissary/blob/9b19425da237a46461d79cb0e65ecb49f99cf564/cmd/entrypoint/healthcheck_server.go#L50)) is routed to our AuthService before the responding with `Ambassador is ready and waiting`. 

**To Reproduce**
Deploy a Module like the following
```
apiVersion: getambassador.io/v3alpha1
kind: Module
metadata:
  name: ambassador
spec:
  config:
    ....
    liveness_probe:
      enabled: true
```

Deploy an AuthService like the following
```
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "some-service"
```

Then you can see the request in the logs of your AuthService. To confirm, you can view the route for `/ambassador/v0/check_alive` in the diagnostic UI has no config to bypass authentication, which would come from `bypass_auth: true` like any other Mapping.

**Expected behavior**
I would expect internal health checking routes to bypass AuthService and RateLimitService configurations.

**Versions (please complete the following information):**
 - emissary-ingress v2.5.1
 - Kubernetes via kOps on EC2
 - v1.24.10

**Additional context**
A workaround we found was to manually create Mappings for the health check route like the below, then set `liveness_probe: false` in the Module.

Sample Mapping:
```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: liveness-probe
  namespace: emissary-ingress
spec:
  hostname: "*"
  prefix: /ambassador/v0/check_alive
  rewrite: /ambassad/v0/check_alive
  service: emissary-ingress-admin.emissary-ingress:8877
```
