### ISSUE TITLE
Cannot get certificates using ACME Provider

### ISSUE THREAD

**Issue by lucacox** [emissary-ingress/emissary#4966]
**Describe the bug**
Using Ambassador Edge Stack, I cannot obtain certificates (with letsencrypt) for hosts a part from the first one. 

For the second host edge stack logs reports this line:

```bash
ACCESS [2023-04-12T10:29:39.872Z] "GET /.well-known/acme-challenge/dRnDP6qVr93ithLoltJoWc-JiK6EpbYsl4JXUyfK8c4 HTTP/1.1" 404 NR 0 0 0 - "10.68.2.1" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "1ce1dbed-3383-45b9-a984-a25107adae01" "second.domain.it" "-""
```

whereas for the first one it reports 200.

Here are the Host resources:

```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: first-host
spec:
  hostname: fisrt.domain.it # not real domain but something very similar
  acmeProvider:  
    email: it@example.com # not real email
  tlsSecret:
    name: first-domain-it-certs
  requestPolicy:
    insecure:
      action: Redirect  
  mappingSelector:
    matchLabels:
      targethost: main-host 
  tls:
    min_tls_version: v1.2
```

```yaml
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: second-domain-it
spec:
  hostname: second.domain.it # not real domain but something very similar
  acmeProvider: 
    email: it@example.com # not real email
  tlsSecret:
    name: second-domain-it-certs
  requestPolicy:
    insecure:
      action: Redirect 
  mappingSelector:
    matchLabels:
      targethost: second-host  
  tls:
    min_tls_version: v1.2
```

These are the events in the second Host:

```bash
Events:
  Type     Reason   Age               From                   Message
  ----     ------   ----              ----                   -------
  Normal   Pending  20s               Ambassador Edge Stack  waiting for Host DefaultsFilled change to be reflected in snapshot
  Normal   Pending  19s               Ambassador Edge Stack  creating private key Secret
  Normal   Pending  19s               Ambassador Edge Stack  waiting for private key Secret creation to be reflected in snapshot
  Normal   Pending  18s               Ambassador Edge Stack  waiting for Host status change to be reflected in snapshot
  Normal   Pending  17s               Ambassador Edge Stack  registering ACME account
  Normal   Pending  16s               Ambassador Edge Stack  ACME account registered
  Normal   Pending  16s               Ambassador Edge Stack  waiting for Host ACME account registration change to be reflected in snapshot
  Normal   Pending  9s (x2 over 16s)  Ambassador Edge Stack  tlsSecret "second-domain-it-certs"."edge" (hostnames=["second.domain.it"]): needs updated: tlsSecret does not exist
  Normal   Pending  9s (x2 over 16s)  Ambassador Edge Stack  performing ACME challenge for tlsSecret "second-domain-it-certs"."edge" (hostnames=["second.domain.it"])...
  Warning  Error    1s                Ambassador Edge Stack  obtaining tlsSecret "second-domain-it-certs"."edge" (hostnames=["second.domain.it"]): error: one or more domains had a problem:
[second.domain.it] context canceled
```

**To Reproduce**
* Install Edge Stack via Helm
*  add first host and obtain certificate 
* add second host get error:
`obtaining tlsSecret "second-domain-it-certs"."edge" (hostnames=["second.domain.it"]): error: one or more domains had a problem:
[second.domain.it] context canceled`

**Expected behavior**
Get all  needed certificates

**Versions (please complete the following information):**
 - Ambassador: 3.5.1
 - Kubernetes environment: Google Kubernetes Engine
 - image: docker.io/datawire/aes:3.5.1
