### ISSUE TITLE
Istio Integration failing with envoy upstream request timeout

### ISSUE THREAD

**Issue by whitelancer** [emissary-ingress/emissary#5056]
**Describe the bug**

When trying to use Istio service mesh (1.17.2) with Ambassador Edge Stack (8.6.0), Emissary-ingress (envoy) fails with an upstream request timeout.  This appears to be due to there being a missing secret when generating the TLSContext, but that may be a false lead.

**To Reproduce**
_Note: I have not yet tried installing Istio without cert-manager yet_

1. Install cert-manager using helm (https://cert-manager.io/docs/installation/helm/)
2. Install cert-manager-istio-csr using helm (https://cert-manager.io/docs/projects/istio-csr/)
3. Install Istio-base and istiod using helm.  (https://istio.io/latest/docs/setup/install/helm/)
4. Namespaces (ambassador) are configured to use istio-injection via labels.
5. Deploy a test manifest of a simple default host, TLSContext, deployment, service, and mapping.  See manifest below.

**Expected behavior**
The service should respond with valid upstream responses.

**Versions (please complete the following information):**
 - datawire/edge-stack;  helm v8.6.0, app v3.6.0
 - Kubernetes environment [Microk8s with k8s v1.16.4, Minikube v1.30.1 running k8s v1.26.3]
 - istio: helm v1.17.2, app v1.17.2

**Additional context**

I have reviewed similar issues but none seem to be the one I'm experiencing.
https://github.com/emissary-ingress/emissary/issues/4744
https://github.com/emissary-ingress/emissary/issues/3510
https://github.com/emissary-ingress/emissary/issues/4484

Under the section on configuring a TLSContext in the docs (https://www.getambassador.io/docs/emissary/latest/howtos/istio#configure-an-mtls-tlscontext) it states:
```
Emissary-ingress reads the mTLS certificates from /etc/istio-certs (per the AMBASSADOR_ISTIO_SECRET_DIR environment variable) and creates a Secret named istio-certs.
```

However, I never see a secret get generated, and so when I configure the TLSContext to use that secret, it's missing.  This is why I suspect maybe this is the issue.  I wanted to attempt to create this secret manually to test, but I am not sure what format to use/how to create it.  Not to mention, this will need to be constantly updated as cert-manager/istio rotate certs every few hours/days.

Here is a sample manifest file with what I'm testing:

```
# The helm chart  will create the two default Listeners for HTTP on port 8080 and HTTPS on port 8443.
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
  namespace: ambassador
spec:
  hostname: "*"
  tlsSecret:
    name: istio-certs
  tlsContext:
    name: istio-upstream

---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: istio-upstream
  namespace: ambassador
spec:
  secret: istio-certs     # This Secret name cannot currently be changed.
  alpn_protocols: istio   # This is required for Istio.

---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  catch-all
  namespace: ambassador
spec:
  prefix: /
  hostname: "*"
  service: default-http-backend-svc
  tls: istio-upstream

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-http-backend
  labels:
    app.kubernetes.io/name: default-http-backend
    app.kubernetes.io/version: "1.0"
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: default-http-backend
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: default-http-backend
        app.kubernetes.io/version: "1.0"
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: default-http-backend
          image: gcr.io/google_containers/defaultbackend:1.0
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: ambassador
  name: default-http-backend-svc
  labels:
    app.kubernetes.io/name: default-http-backend-svc
    app.kubernetes.io/version: "1.0"
spec:
  selector:
    app.kubernetes.io/name: default-http-backend
    app.kubernetes.io/version: "1.0"
  ports:
    - appProtocol: tcp
      name: tcp-80
      port: 80
      targetPort: 8080
```

Here are the results:
```
$> curl -Lki https://172.17.45.245/

HTTP/1.1 504 Gateway Timeout
content-length: 24
content-type: text/plain
date: Wed, 17 May 2023 19:37:44 GMT
server: envoy

upstream request timeout
```

```
$> kubectl get secrets -n ambassador

NAME                               TYPE                 DATA   AGE
ambassador                         Opaque               1      40m
sh.helm.release.v1.ambassador.v1   helm.sh/release.v1   1      40m
ambassador-internal                Opaque               2      40m
fallback-self-signed-cert          kubernetes.io/tls    2      40m
```

**Comment by whitelancer** [comment]
After all of that, and days of working on this, I finally added a port 80 to the end of the Mapping, and it started working.  I even remember reading that warning, here:  https://www.getambassador.io/docs/emissary/latest/howtos/istio#configure-mappings-to-use-mtls and https://www.getambassador.io/docs/emissary/latest/howtos/istio#configure-service-ports.

What's bothering me is that during initial development, I did use the port 80 syntax and I also used 80/443 on the service, and was running into some issues.  I wish I had documented better.  For anyone coming in the future, just beware of that if you see a timeout issue.

Two fixes:
```
---
apiVersion: getambassador.io/v3alpha1
kind:  Mapping
metadata:
  name:  catch-all
  namespace: ambassador
spec:
  prefix: /
  hostname: "*"
  service: default-http-backend-svc:80
  tls: istio-upstream

```

or

```
---
apiVersion: v1
kind: Service
metadata:
  namespace: ambassador
  name: default-http-backend-svc
  labels:
    app.kubernetes.io/name: default-http-backend-svc
    app.kubernetes.io/version: "1.0"
spec:
  selector:
    app.kubernetes.io/name: default-http-backend
    app.kubernetes.io/version: "1.0"
  ports:
    - appProtocol: tcp
      name: tcp-80
      port: 80
      targetPort: 8080
    - appProtocol: tcp
      name: tcp-443
      port: 443
      targetPort: 8080
```
