### ISSUE TITLE
Default ingress regex not mapping

### ISSUE THREAD

**Issue by davehardyuk** [emissary-ingress/emissary#5069]
I have a default Kubernetes ingress which contains regex paths, these are being treated as exact matches by Emissary and not regex.

**To Reproduce**
Create an ingress with. a regex path:

```
- path: /blog/.*-cars.*
  pathType: Prefix
  backend:
  service:
    name: cars-blog-service
    port:
      number: 9898
```

**Expected behavior**
```https://www.host.com/blog/red-cars``` should forward to the service but it 404s. 

Visiting the path ```https://www.host.com/blog/.*-cars.*``` forwards to the service (appears to be treating as an exact match and not regex)

Are there any annotations I need to add to the ingress to flag it as regex so Emissary treats it as regex?
