### ISSUE TITLE
FilterPolicy rules are all executed instead of the first matching rule

### ISSUE THREAD

**Issue by steinwelberg** [emissary-ingress/emissary#5092]
**Describe the bug**
According to the documentation, the first `FilterPolicy` rule that matches the incoming request, will be executed. However, Ambassador seems to execute ALL matching rules in a FilterPolicy.

Quote from the docs:
> Edge Stack will choose the first FilterPolicy rule that matches the incoming request. As in the above example, you must list your rules in the order of least to most generic.

Effectively, this also means that the below snippet (taken from the documentation) won't work:
```
---
apiVersion: getambassador.io/v3alpha1
kind: Filter
metadata:
  name: param-filter # This is the name used in FilterPolicy
  namespace: standalone
spec:
  Plugin:
    name: param-filter # The plugin's `.so` file's base name

---
apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: httpbin-policy
spec:
  rules:
  # Don't apply any filters to requests for /httpbin/ip
  - host: "*"
    path: /httpbin/ip
    filters: null
  # Apply param-filter and auth0 to requests for /httpbin/
  - host: "*"
    path: /httpbin/*
    filters:
    - name: param-filter
    - name: auth0
  # Default to authorizing all requests with auth0
  - host: "*"
    path: "*"
    filters:
    - name: auth0
```

**To Reproduce**
1. Deploy Ambassador
2. Deploy the httpbin application
3. Deploy the Filter and FilterPolicy listed above
4. Make a request to `/httpbin/ip`

**Expected [behavior**](url)

Expect that no filters are triggered. However, actually the `param-filter` and `auth0` filter will be triggered.

**Versions (please complete the following information):**
 - Ambassador: 3.3.0
 - Kubernetes environment: AWS EKS 
 - Version: 1.23
