### ISSUE TITLE
Emissary uses wrong TLSContext with identical name in different namespace

### ISSUE THREAD

**Issue by dschuldt** [emissary-ingress/emissary#5106]
**Describe the bug**
If two TLSContexts are present with an identical name but in different namespaces, Emissary does not use the one which resides in the same namespace as the Host resource. 

**To Reproduce**
1. Create two namespaces
2. Create a TLSContexts and Hosts with the same names in these namespaces
3. Create two different certificates with different hostnames and configure the ambassador resources accordingly
4. You'll experience a host mismatch error and the wrong certificate is presented to user requests

**Expected behavior**
Emissary should use the TLSContext within the same namespace as the Host

**Versions (please complete the following information):**
 - docker.io/emissaryingress/emissary:3.6.0
 - Rancher RKE Cluster v1.24.4

**Additional context**
I'm sorry if I misunderstood the TLSContext resource. Is it not bound to a specific namespace?

Best 
Denis

**Comment by cindymullins-dw** [comment]
HI @dschuldt , are you [linking the Host](https://www.getambassador.io/docs/emissary/latest/topics/running/tls#host-and-tlscontext) to the TLSContext you want it to use?  You can configure that explicitly, just make sure the The Host and the TLSContext refer to the same Kubernetes Secret.

**Comment by dschuldt** [comment]
Hi @cindymullins-dw,

yes, the Host/TLSContext are linked. The secret is the same in both resources. The secret also exists in both namespaces with an identical name. I'll provide a redigated code example.

**Comment by dschuldt** [comment]
Here we go.

These are the **TLSContexts** (Same name, but different namespace and hostname):

```
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: my-tlscontext
  namespace: my-namespace-1
spec:
  alpn_protocols: h2,http/1.1
  hosts:
  - my-fqdn-1
  min_tls_version: v1.2
  secret: my-secret
---
apiVersion: getambassador.io/v2
kind: TLSContext
metadata:
  name: my-tlscontext
  namespace: my-namespace-2
spec:
  alpn_protocols: h2,http/1.1
  hosts:
  - my-fqdn-2
  min_tls_version: v1.2
  secret: my-secret
```

The **Hosts** (again, same name but different namespace and different hostname):

```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: my-host
  namespace: my-namespace-1
spec:
  hostname: my-fqdn-1
  requestPolicy:
    insecure:
      action: Redirect
  tlsContext:
    name: my-tlscontext
  tlsSecret:
    name: my-secret
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: my-host
  namespace: my-namespace-2
spec:
  hostname: my-fqdn-2
  requestPolicy:
    insecure:
      action: Redirect
  tlsContext:
    name: my-tlscontext
  tlsSecret:
    name: my-secret
```

Here are the used **Secrets** (same name but different namespace and content:

```
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: my-secret
  namespace: my-namespace-1
data:
  tls.crt: ...
  tls.key: ...
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: my-secret
  namespace: my-namespace-2
data:
  tls.crt: ...
  tls.key: ...
```

With this configuration, Emissary links the TLSContext from my-namespace-1 to the host from my-namespace-2 (or vice versa). If you rename a TLSContext and reconfigure any host to use the new name, everything works fine.

Hope this helps.
