### ISSUE TITLE
Ambassador returns http 404 when request url doesn't include a port in host header

### ISSUE THREAD

**Issue by rootrahulagr** [emissary-ingress/emissary#5131]
As per the following release note, if a request doesn’t specify a port, port 443 is assumed by ambassador when it comes through.  So, ambassador should handle both the requests with or without port with common host configuration. 

https://www.getambassador.io/docs/emissary/latest/release-notes#3.5.0

However, this theory is not working in our case. Ambassador is able to translate only one type of request at a time, depending on its host configuration. If host.hostname is configurated with ":port", the incoming request with a port in host header would be accepted (the request without port would get 404) and vice versa.

We are using Ambassador (Emissary Ingress) v3.6.0, chart version emissary-ingress-8.6.0, on EKS v1.24 cluster.

Configuration of ambassador related resources look like this (have masked some fields):

Host -
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
 name: demo-host
spec:
  hostname: "*.xxx.yyy.abc.com.cd:443"
  tlsSecret:
    name: ambassador-certs
  requestPolicy:
    insecure:
      action: Redirect
      

Listeners -
---
apiVersion: getambassador.io/v3alpha1
 kind: Listener
 metadata:
    name: https-listener
 spec:
    port: 8443
   protocol: HTTPS
   securityModel: XFP
   hostBinding:
	namespace:
	     from: ALL

apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
     name: http-listener
spec:
   port: 8080
   protocol: HTTP
   securityModel: XFP
   hostBinding:
        namespace:
	     from: ALL

Mapping (Note: This mapping is defined as annotation of application's service object) -
---
apiVersion: ambassador/v3alpha1
kind: Mapping
name: myapp_mapping
service: https://kubernetes-dashboard.kube-system
host: "myapp\\..*\\.abc\\.com\\.cd"
host_regex: true
prefix: /dashboard/

**Comment by rootrahulagr** [comment]
We were not using TLS context, so it was not part of the setup originally. However, I have created TLS Context now with following definition, as suggested by @cindymullins-dw, tested again and it didn't make any difference. I am not sure either what purpose this TLS context is serving here.

---
apiVersion: getambassador.io/v3alpha1
kind: TLSContext
metadata:
  name: example-host-context
  namespace: default
spec:
  hosts: ["*.xxx.yyy.abc.com.cd", "*.xxx.yyy.abc.com.cd:443"]
  secret: ambassador-certs

**Comment by cindymullins-dw** [comment]
Thanks for trying that.  I think you can remove the TLSContext.  The original issue was fixed in 3.5 so your config should be working for you and I was hoping the TLSContext was the missing piece.  However since that isn't working, we do have a manual workaround it'd be great if you could test.  

8443 is special in that it is our default listener for 443 (or "port-less" requests).  Can you use a port like 10443?  If so:
- create listener for 10443 and expose that on the EdgeStack service 
- add match Labels to say which Host can attach to the Listener
- add host with hostname: example.com:8443
- include the same match labels as listener
- add mappingSelectors (hostname example.com:443) so that Mappings will only be attached to this Host

Then request to https://example.com:10443/backend/would have its own Listener/FilterChain/Vhost and routes and would not collide with the other routes that are on the standard 8443 listener.  The config would look like this:

```
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: edge-stack-listener-10443
  namespace: ambassador
spec:
  hostBinding:
    namespace:
      from: ALL
    selector:
      matchLabels:
        "aes-listener": "10443"
  port: 10443
  protocol: HTTPS
  securityModel: XFP
```
Second, create a Host that has a wild-card hostname ( "*") but leverages the a TLS Secret that works for the hostname without the port (i.e v3test.mstanfield.k736.net). In this sample, I just use the one Acme created for the other host.

Add Labels to the metadata so that it will bind to the Listener listening on 10443.  Add Mapping selectors too, which will ensure only the routes you want exposed on this listener are added and not the routes that attach to the other Host.

```
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: 10443-wildcard-host
  labels:
    "aes-listener": "10443"
spec:
  hostname: "*"
  tlsSecret:
    name: v3test.mstanfield.k736.net
  mappingSelector:
    matchLabels:
      "aes-listener": "10443"
```
Add the mapping to back end service, ensuring you have the correct Labels added so that it can be added to the Host

---
```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend3
  namespace: default
  labels:
    "aes-listener": "10443"
spec:
  prefix: /backend3/
  service: quote2
```
Finally, expose it externally on the Edge Stack LoadBalancer Service. You can expose 8443 externally while forwarding it to the 10443 where our Listener is configured with the new Host and Mapping:

```
ports:
- name: http
   protocol: TCP
   port: 80
   targetPort: 8080
- name: https
   protocol: TCP
   port: 443
   targetPort: 8443
 - name: https2
   protocol: TCP
   port: 8443
   targetPort: 10443
```
To ensure that this Host and Mapping do not attach to the other listeners (8443, 8080) then we need to set selectors and labels so something like this on those Listeners with corresponding labels on the Host:

```
# On Listener in hostbinding
selector:
  matchLabels:
    aes-listener: 8443-8080
        
 # on Host in metadata as Labels
labels:
  aes-listener: 8443-8080
```
This isolates the Host, and Routes into their own Listener and FilterChain in Envoy.
