### ISSUE TITLE
Mapping: uri_template path match and rewrite support

### ISSUE THREAD

**Issue by ppanyukov** [emissary-ingress/emissary#5204]
**Please describe your use case / problem.**

We currently use Azure API Management for external traffic routing which has URL template rules like this:

```yaml
route:
  uri_template: /account/{userId}
  backend_service: https://account.example.com
  uri_template_rewrite: /{userId}
```

Currently, the only way to implement similar functionality in Emissary looks to be using regex paths and regex rewrite. But 

* Regex is awkward, and prone to errors, as well as having to use numbered capture groups like `\1` and `\2`.
* Uri patterns provide more interesting features like matching globs with `*` and `**`.

**Describe the solution you'd like**

We'd like to be able to achieve uri pattern with Emissary Mappings, e.g like this:

```yaml
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: mapping-to-account
spec:
  prefix: /account/{userId}
  prefix_uri_template: true
  service: https://account.example.com
  uri_template_rewrite: /{userId}
```

I understand that Envoy does have this as an extension, which is probably bundled with the Emissary build? Here are the docs, which look to do exactly what we want:

* Envoy [path_template](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/path/match/uri_template/v3/uri_template_match.proto#extension-envoy-path-match-uri-template-uri-template-matcher)

* Envoy [path_template_rewrite](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/path/rewrite/uri_template/v3/uri_template_rewrite.proto#extension-envoy-path-rewrite-uri-template-uri-template-rewriter)

So it should be doable fairly easily in Emissary? But I'm not very familiar with Envoy and internals of Emissary.

**Describe alternatives you've considered**

* Regex rewrites is an obvious alternative. Could work but not ideal.

* I see there is `envoy_override` field in Mapping CRD. Perhaps we could use that to plug in uri template things? I couldn't find any docs on what this field does and also I'm not sure what I'd need to put there for it to do what I need.
