### ISSUE TITLE
Multiple domains for RateLimitService

### ISSUE THREAD

**Issue by iamalryz** [emissary-ingress/emissary#5238]
**Please describe your use case / problem.**
Hi! I have a K8s cluster with multiple services deployed into. I'm trying to implement `remote_address`-based rate limiting for them using [envoyproxy/ratelimit](https://github.com/envoyproxy/ratelimit) project as a `RateLimitService` implementation. 

For that, I'd like to separate them from each other by [domain](https://github.com/envoyproxy/ratelimit#definitions) + `remote_address`.

For example, I have such [envoyproxy/ratelimit](https://github.com/envoyproxy/ratelimit) configuration for domains `quote-qa` and `quote-prod`:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit
  namespace: emissary
data:
  quote-qa.yaml: |
    ---
    domain: quote-qa
    descriptors:
    - key: remote_address
      rate_limit:
        unit: minute
        requests_per_unit: 10

  quote-prod.yaml: |
    ---
    domain: quote-prod
    descriptors:
    - key: remote_address
      rate_limit:
        unit: minute
        requests_per_unit: 20
```

And two mappings for their services:
```
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote
  namespace: quote-qa
spec:
  hostname: quote-qa.com
  prefix: /backend
  service: quote
  labels:
    quote-qa: <--------- domain
    - remote_address:
      - remote_address:
          key: remote_address
```

```
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote
  namespace: quote-prod
spec:
  hostname: quote-prod.com
  prefix: /backend
  service: quote
  labels:
    quote-prod: <--------- domain
    - remote_address:
      - remote_address:
          key: remote_address
```

But there is no way to specify two or more domains in a `RateLimitService` manifest, as [explained in documentation](https://www.getambassador.io/docs/emissary/latest/topics/using/rate-limits#attaching-labels-to-requests):
> ... **Note that at present, rate limiting supports just one domain** ...

**Describe the solution you'd like**
I'd like to have an ability to specify multiple domains in a `RateLimitService` manifest. Or, more general, I'd like to have an ability to more convenient configuration for per-service `remote_address`-based rate limit. At the moment I have no idea how can I achieve it.

**Describe alternatives you've considered**
As a workaround I tried to create `RateLimitService` resource per domain, but got this error in emissary-ingress:
> 2023-08-16 15:08:37 diagd 3.7.2 [P33TAEW] INFO: ir.ratelimit: <RichStatus BAD error='only one RateLimitService is supported, got 2' hostname='emissary-ingress-98f8d9bbc-l5fqj' version='3.7.2'>
