### ISSUE TITLE
Emissary Ingress in perpetual OutOfSync in ArgoCD due to aggregaredRoles in ClusterRole's

### ISSUE THREAD

**Issue by alexbowers** [emissary-ingress/emissary#5243]
**Describe the bug**
In ArgoCD, Emissary is perpetually stuck in a loop of OutOfSync and In Sync

**To Reproduce**

1. Install ArgoCD
```
{
    configs: {
        cm: {
            'resource.compareoptions.ignoreAggregatedRoles': 'true',
        },
        params: {
            "server.insecure": true,
        },
        secret: {
            githubSecret: "XXX"
        }
    }
}
```

These are the configs i'm passing to the `values.yaml` file in Helm for installing ArgoCD.

2. Install the Emissary Ingress CRDs
3. Install Emissary Ingress via ArgoCD, I make use of a Helm Chart:

```yaml
charts:
  - name: emissary-ingress
    namespace: emissary
    repoURL: https://app.getambassador.io
    targetRevision: 8.5.2
    values:
      createDefaultListeners: true
      env:
        STATSD_ENABLED: true
      envRaw: |
        - name: STATSD_HOST
          valueFrom:
            fieldRef:    
              fieldPath: status.hostIP
      service:
        type: LoadBalancer
        ports:
          - name: http
            port: 80
            targetPort: 8080
          - name: https
            port: 443
            targetPort: 8443
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      resources:
        requests:
          cpu: 250m
          memory: 250Mi
      livenessProbe:
        failureThreshold: 5
        initialDelaySeconds: 60
        periodSeconds: 10
      readinessProbe:
        failureThreshold: 5
        initialDelaySeconds: 60
        periodSeconds: 10
```

```
{
        apiVersion: 'argoproj.io/v1alpha1',
        kind: 'ApplicationSet',
        metadata: {
            name: 'platform-charts',
            namespace: 'argocd',
        },
        spec: {
            goTemplate: true,
            generators: [
                {
                    matrix: {
                        generators: [
                            {
                                git: {
                                    repoURL: 'git@github.com:shopblocks-engineering/release-manifests.git',
                                    revision: 'main',
                                    files: [
                                        {
                                            path: `platform/staging/platform/charts.yaml`,
                                        }
                                    ]
                                }
                            },
                            {
                                list: {
                                    elements: [],
                                    elementsYaml: '{{ .charts | toJson }}',
                                }
                            }
                        ]
                    }
                }
            ],
            template: {
                metadata: {
                    name: '{{ .name }}',
                },
                spec: {
                    project: 'default',
                    source: {
                        chart: '{{ .name }}',
                        repoURL: '{{ .repoURL }}',
                        targetRevision: '{{ .targetRevision }}',
                        helm: {
                            releaseName: '{{ .name }}',
                            values: '{{ index . "values" | toJson }}',
                        },
                    },
                    destination: {
                        namespace: '{{ .namespace }}',
                        server: 'https://kubernetes.default.svc',
                    },
                    syncPolicy: {
                        automated: {
                            selfHeal: true,
                            prune: true,
                        },
                        syncOptions: [
                            'CreateNamespace=true',
                        ]
                    },
                }
            }
        }
    }
```
4. Watch ArgoCD, it will cycle in and out of sync.

**Expected behavior**
Once it syncs properly, it should list itself as in sync and not cycle between in and out of sync for the ClusterRole's

**Versions (please complete the following information):**
 - Emissary Ingress: Helm Chart: 8.7.2, Application Version: 3.7.2
 - ArgoCD: Helm Chart: 5.43.4, Application: v2.8.0
 - Kubernetes environment: EKS 1.27

**Additional context**
Some videos showing the OutOfSync behaviour

https://github.com/emissary-ingress/emissary/assets/842974/3118edc5-c8b4-428d-82b2-8637ac2431f5
https://github.com/emissary-ingress/emissary/assets/842974/aa4e048c-69ea-4450-a788-07f820a72772

The videos show 8.5.2 as the version; I have since upgraded to 8.7.2; this still occurs.

**Comment by alexbowers** [comment]
https://github.com/argoproj/argo-cd/issues/3602#issuecomment-1678751259

**Comment by alexbowers** [comment]
Looking through the ArgoCD code, it is possible that his might be the issue:

https://github.com/argoproj/argo-cd/blob/2dbc6c7c71848109a6cd29e10dcb368efdfb9ece/cmd/argocd/commands/app.go#L1076

**Comment by thedevelopnik** [comment]
Do you have anything else in the cluster that monitors ClusterRoles according to some policy and modifies them, say if they're too permissive, or missing an annotation or something? What appears to be happening is that something is modifying your ClusterRoles and then Argo is sync'ing them back. That's my first guess, but could be wrong.

**Comment by alexbowers** [comment]
Not to my knowledge. Ill try to create a full reproduction if I can locally, but the other stuff that is installed is all fairly basic stuff, nothing that I know of that should modify the cluster roles
________________________________

**Comment by alexbowers** [comment]
The only other things installed on this server are:

- metrics-server
- cert-manager
- external-secrets
- crossplane (crossplane/provider-sql)
- reflector
- reloader

To my knowledge, none of these should affect anything to do with ClusterRole.

**Comment by alexbowers** [comment]
![CleanShot 2023-08-18 at 14 09 45](https://github.com/emissary-ingress/emissary/assets/842974/0bd0611b-aba9-46cd-9733-088eb434ba19)

As you can see from this, the diff is trying to remove all `rules` back to an empty array that is listed in the Desired Manifest

![CleanShot 2023-08-18 at 14 10 36](https://github.com/emissary-ingress/emissary/assets/842974/0ca39121-5a4c-4af4-95c6-dd8aa2e591bc)

**Comment by fad3t** [comment]
Hello @alexbowers ,

You can configure the ArgoCD app to ignore those differences.
```yaml
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    managedFieldsManagers:
    - clusterrole-aggregation-controller
    jsonPointers:
    - /roles
```

**Comment by crogers-harrys** [comment]
@fad3t solution above worked for me.  I only had to change `/roles` to `/rules` like this:

```
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      managedFieldsManagers:
        - clusterrole-aggregation-controller
      jsonPointers:
        - /rules
 ```
