### ISSUE TITLE
kubectl explain does not show all config options

### ISSUE THREAD

**Issue by gecube** [emissary-ingress/emissary#5358]
Good day colleagues!

I am facing very weird issue with the documentation. One already knows that there is such a good tool like `kubectl explain` which shows all parameters in CR. Like:

```yaml
kubectl explain mappings.spec
GROUP:      getambassador.io
KIND:       Mapping
VERSION:    v2

FIELD: spec <Object>

DESCRIPTION:
    MappingSpec defines the desired state of Mapping
    
FIELDS:
  add_linkerd_headers	<boolean>
    <no description>

  add_request_headers	<Object>
    <no description>

  add_response_headers	<Object>
    <no description>

  allow_upgrade	<[]string>
    A case-insensitive list of the non-HTTP protocols to allow "upgrading" to
    from HTTP via the "Connection: upgrade" mechanism[1].  After the upgrade,
    Ambassador does not interpret the traffic, and behaves similarly to how it
    does for TCPMappings. 
     [1]: https://tools.ietf.org/html/rfc7230#section-6.7 
     For example, if your upstream service supports WebSockets, you would write 
     allow_upgrade: - websocket 
     Or if your upstream service supports upgrading from HTTP to SPDY (as the
    Kubernetes apiserver does for `kubectl exec` functionality), you would write
     allow_upgrade: - spdy/3.1

  auth_context_extensions	<map[string]string>
    <no description>

  auto_host_rewrite	<boolean>
    <no description>
...
```

I am using `ambassador_id` key for selecting which particular emissary-ingress must serve the particular object. Unfortunately, I don't see this key in `kubectl explain` output. 
The Mapping I am using could look like this:

```yaml
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: some-name
  namespace: emissary
spec:
  ambassador_id: [ "public" ]
  hostname: some.domain.com
  prefix: /api/v4
  rewrite: ""
  add_request_headers:
    Site-Enum:
      value: _SOME_HEADER
      append: False
  service: some-service.namespace:8484
```

I am kindly asking you to share your suggestions.
I hope that sometime I will be able to retrieve the full list of conf. options with the help of `kubectl explain` command.
