### ISSUE TITLE
emessary-ingress not working

### ISSUE THREAD

**Issue by gigi206** [emissary-ingress/emissary#5399]
I installed emissary-ingress (last 8.8.2) via helm chart with default values.

I try to test on longhorn and I changed the `ingressClassName` from `nginx` to `ambassador`:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  ingressClassName: ambassador
  rules:
  - host: longhorn.gigix
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - longhorn.gigix
    secretName: longhorn-cert-tls
```

```shell
$ kubectl get ing -n longhorn-system 
NAME               CLASS        HOSTS            ADDRESS           PORTS     AGE
longhorn-ingress   ambassador   longhorn.gigix   192.168.122.180   80, 443   15h
```

```shell
$ kubectl get ingressclass
NAME         CONTROLLER                            PARAMETERS   AGE
ambassador   getambassador.io/ingress-controller   <none>       17h
cilium       cilium.io/ingress-controller          <none>       8d
nginx        k8s.io/ingress-nginx                  <none>       2d18h
```

```shell
$ curl http://longhorn.gigix -kIL          
curl: (7) Failed to connect to longhorn.gigix port 80 after 6 ms: Couldn't connect to server
```

I also try with CRDs:
```yaml
# CRD Mapping
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: my-mapping
  namespace: longhorn-system
  #namespace: emissary-ingress
spec:
  hostname: longhorn2.gigix
  service: http://longhorn-frontend.longhorn-system:80
  prefix: /
---
# CRD Host
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: longhorn2.gigix
  namespace: longhorn-system
  #namespace: emissary-ingress
spec:
  hostname: longhorn2.gigix
---
# CRD Listener
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: my-listener
  namespace: longhorn-system
  #namespace: emissary-ingress
spec:
  port: 80
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
      #from: ALL
```

But I see no state:
```shell
NAME                                  SOURCE HOST   SOURCE PREFIX   DEST SERVICE                                  STATE   REASON
mapping.getambassador.io/my-mapping                 /               http://longhorn-frontend.longhorn-system:80           

NAME                                    HOSTNAME          STATE   PHASE COMPLETED   PHASE PENDING   AGE
host.getambassador.io/longhorn2.gigix   longhorn2.gigix                                             10s

NAME                                    PORT   PROTOCOL   STACK   STATSPREFIX   SECURITY   L7DEPTH
listener.getambassador.io/my-listener   80     HTTP                             XFP        
```

```shell
$ kubectl get all -n emissary-ingress
NAME                                          READY   STATUS    RESTARTS   AGE
pod/emissary-ingress-899ff87f6-2wp9q          1/1     Running   0          11h
pod/emissary-ingress-agent-6fc7589644-kxncd   1/1     Running   0          11h

NAME                             TYPE           CLUSTER-IP      EXTERNAL-IP       PORT(S)                      AGE
service/emissary-ingress         LoadBalancer   10.43.167.123   192.168.122.180   80:32540/TCP,443:31255/TCP   17h
service/emissary-ingress-admin   ClusterIP      10.43.120.174   <none>            8877/TCP,8005/TCP            17h
service/emissary-ingress-agent   ClusterIP      10.43.12.239    <none>            80/TCP                       17h

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/emissary-ingress         1/1     1            1           17h
deployment.apps/emissary-ingress-agent   1/1     1            1           17h

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/emissary-ingress-899ff87f6          1         1         1       17h
replicaset.apps/emissary-ingress-agent-6fc7589644   1         1         1       17h
```

```shell
$ kubectl get all -n emissary-system 
NAME                                   READY   STATUS    RESTARTS   AGE
pod/emissary-apiext-7d4dc6fcfb-29zlw   1/1     Running   0          11h
pod/emissary-apiext-7d4dc6fcfb-jkll5   1/1     Running   0          11h
pod/emissary-apiext-7d4dc6fcfb-jkvls   1/1     Running   0          11h

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/emissary-apiext   ClusterIP   10.43.68.158   <none>        443/TCP   17h

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/emissary-apiext   3/3     3            3           17h

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/emissary-apiext-7d4dc6fcfb   3         3         3       17h
```

Any ideas ?
