### ISSUE TITLE
OAuth endpoints 404 when having one or more Hosts with SSL Cert

### ISSUE THREAD

**Issue by dps-leemcneil** [emissary-ingress/emissary#5407]
I'm having a problem with URL paths such as `/.ambassador/oauth2/multicookie` (or anything /.ambassador) will return a 404 when I use a Host resource.

When the Host is removed, the .ambassador paths work again.

I am trying to setup the OAuth2 filter (Azure AAD), and have multiple Host resources (hostnames) pointing at different services.
However whenever I add a Host, the .ambassador paths are no longer possible to reach.

Is it possible to add a Mapping to get the .ambassador URLs working within a Host?

**To Reproduce**
Create `Service` and `Mapping`:
```
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: web-frontend
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: web-frontend
  namespace: web-frontend
  labels:
    hostname: web-frontend.example.com
spec:
  hostname: web-frontend.example.com
  prefix: /
  service: web-frontend
```

This works and `/.ambassador/oauth2/...` endpoints are available.

If I now add a `Host` with or without a TLS cert, all `/.ambassador/oauth2/...` endpoints 404.
```
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: web-frontend.example.com
  namespace: web-frontend
spec:
  hostname: web-frontend.example.com
  mappingSelector:
    matchLabels:
      hostname: web-frontend.example.com
    acmeProvider:
      authority: 'https://acme-v02.api.letsencrypt.org/directory'
      email: email@example.com
    tlsSecret:
      name: web-frontend.example.com
```

**Expected behavior**
Expecting that `/.ambassador/oauth2/...` endpoints are available on a defined `Host`resource.
Currently only on the default host, no `Host` resources (for example different hostnames with TLS certs).

**Versions (please complete the following information):**
 - Ambassador: 3.8.2
 - Kubernetes environment: Azure AKS
 - Version (k8s): 1.26.6

**Additional context**
