### ISSUE TITLE
Ingress no longer functions

### ISSUE THREAD

**Issue by darkn3rd** [emissary-ingress/emissary#5451]
**Describe the bug**

The ingress resource is not functional it seems, emissary-ingress does not capture any changes needed.  If there are any other requirements outside of the ingress, it is not documented at https://www.getambassador.io/docs/emissary/latest/topics/running/ingress-controller#when-and-how-to-use-the-ingress-resource

**To Reproduce**

1. Install an ingress resource for a service that supports HTTP, e.g.
    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: dg-dgraph-ingress
      annotations:
        kubernetes.io/ingress.class: ambassador
    spec:
      ingressClassName: ambassador
      rules:
        - http:
            paths:
              - backend:
                  service:
                    name:  dg-dgraph-alpha
                    port:
                      number: 8080
                pathType: ImplementationSpecific
                path: /
          host: dgraph.local
    ```
2. Either update DNS record or /etc/hosts with emissary-ingress LB address
    ```bash
    export DGRAPH_HOSTNAME_HTTP="dgraph.local"
    export SERVICE_IP=$(kubectl get svc emissary-ingress \
      --namespace emissary \
      --output jsonpath='{.status.loadBalancer.ingress[0].ip}'
    )
    
    sudo sh -c "echo ${SERVICE_IP} ${DGRAPH_HOSTNAME_HTTP} >> /etc/hosts"
    ```
3. Attempt to reach the address
    ```bash
    curl -siv dgraph.local/state
    ```
**Expected behavior**

I would expect when accessing the endpoint using the hostname, e.g. `dgraph.local`, that I would get a response from the server.  This means that emissary-ingress would scan for the ingress resource, make the appropriate configurations, and communicate this in the logs. But not of these seems to be happening. 

When I try to configure something similar using Listerner, Host, and Mapping, this works fine. 

**Versions (please complete the following information):**
 - Ambassador: 3.9.1
 - Kubernetes environment GKE v1.27.3-gke.100

**Additional context**

* GKE was provisioned using this guide: https://joachim8675309.medium.com/ultimate-baseline-gke-cluster-261c1b5544be
* Emissary-Ingress was installed using helm: https://www.getambassador.io/docs/emissary/latest/tutorials/getting-started
* Dgraph was deployed using the following below, but any web service should illustrate the problem.  

```bash
export DGRAPH_ALLOW_LIST="0.0.0.0/0" 
export DGRAPH_RELEASE_NAME="dg"
helm repo add dgraph https://charts.dgraph.io
helm update
helm install $DGRAPH_RELEASE_NAME dgraph/dgraph \
  --namespace dgraph \
  --create-namespace \
  --values -  <<EOF
zero:
  persistence:
    storageClass: premium-rwo
    size: 10Gi
alpha:
  configFile:
    config.yaml: |
      security:
        whitelist: ${DGRAPH_ALLOW_LIST}
  persistence:
    storageClass: premium-rwo
    size: 30Gi
EOF
```
