### ISSUE TITLE
Give the possibility to configure other ports than HTTP and HTTPS inside the Service

### ISSUE THREAD

**Issue by Prop4et** [emissary-ingress/emissary#5455]
I needed Emissary Ingress to be able to forward the AMQP traffic coming from the outside to the RabbitMQ broker running inside the cluster. Due to internal resource limitations it's impossible to set the Broker as a LoadBalancer service so the solution was to go with a ClusterIP service and let Emissary Ingress do the forward.
I initially tried by setting a `Listener` resource like so (and other tests):
```yaml
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: amqp-listener
  namespace: emissary
spec:
  port: 5672
  protocol: TCP
  securityModel: INSECURE
  hostBinding:
    namespace:
      from: ALL
```
In combination with a `mapping `like the following:
```yaml
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: amqp-mapping
  namespace: rabbitmq
spec:
  port: 5672
  service: 	rabbit-service:5672
```
But it didn't work. 
Then i noticed that inside the  `Service` resource deployed through the helm chart only these two ports are set:
```yaml
spec:
  ports:
    - name: amqps
      nodePort: 31668
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: http
      nodePort: 30214
      port: 80
      protocol: TCP
      targetPort: 8080
```
So i had to manually patch the service by adding the port that i need. This wouldn't be a problem if not for the fact that i deploy emissary ingress through argoCD by directly pointing at the helm chart from an internal registry that mirrors a bunch of things.
My request is therefore to parametrize the ports field, allowing us to specify the ports during the deploy phase. In fact in case of the service going down and being recreated a new i have to apply the patch again, breaking the cycle of automation.

Or in case there are already automated ways for applying patches i'd happily accept suggestions

**Comment by Prop4et** [comment]
It is possible to override the ports list by overriding the values of the service like so:
```yaml
...
values: |
          service:
            type: LoadBalancer
            ports:
            - name: http
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8443
              protocol: TCP
            - name: amqp
              port: 5672
              protocol: TCP
              targetPort: 5672
```
