### ISSUE TITLE
Content-Type from Auth service is overwritten in error response

### ISSUE THREAD

**Issue by iam-nagarajan** [emissary-ingress/emissary#5484]
Content-Type from Auth service is overwritten in error response

**To Reproduce**
Setup AuthService 
```
---
apiVersion: getambassador.io/v3alpha1
kind: AuthService
metadata:
  name: authentication
spec:
  ambassador_id: ["--apiVersion-v3alpha1-only--default"]
  auth_service: "mockserver.default:8080"
  path_prefix: "/ambassador"
  allowed_authorization_headers:
  - "x-test"
```

The mockserver is configured to authenticate the requests and for invalid requests it'll send the response body like below with 403 status code and **Cotent-Type** set as **application/json**

```
{
  "result" : "Forbidden"
}
```
When we call the API through emissary, it overrides the Content-Type as text/plain from application/json

```
HTTP/1.1 403 Forbidden
Content-Type: text/plain
... <other headers>
{"result":"Forbidden"}
```

**Expected behavior**
The auth failure response should retain original Content-Type
```
HTTP/1.1 403 Forbidden
Content-Type: application/json
... <other headers>
{"result":"Forbidden"}
```

**Versions (please complete the following information):**
 - Ambassador: 3.9.1
 - Kubernetes environment AWS EKS
 - Version 1.27
