### ISSUE TITLE
`propagation_modes` incompatible with `opentelemetry` driver

### ISSUE THREAD

**Issue by miguelvr** [emissary-ingress/emissary#5505]
**Describe the bug**
Emissary ingress pod enters `CrashLoopBackoff` when `propagation_modes` is specified with `driver: opentelemetry`.

Also, the documentation hints that the way to specify propagation modes is `spec.propagation_modes`, when in reality it is `spec.config.propagation_modes`.

**To Reproduce**
1. Apply the following `TracingService`:
```yaml
apiVersion: getambassador.io/v3alpha1
kind: TracingService
metadata:
  name: tracing
  namespace: emissary
spec:
  driver: opentelemetry
  service: opentelemetry-collector.opentelemetry:4317
  config:
    service_name: emissary
    propagation_modes: [TRACE_CONTEXT]
  sampling:
    overall: 100
```
2. Restart emissary-ingress deployment
3. Observe the CrashLoopBackOff

**Expected behavior**
- `propagation_modes` to be supported with `opentelemetry` driver
- emissary-ingress pod to restart successfully

**Versions (please complete the following information):**
 - Ambassador: v3.9.1
 - Kubernetes environment: Google Kubernetes Engine
 - Version: v1.25.13-gke.20
