### ISSUE TITLE
Opentelemetry driver missing spans

### ISSUE THREAD

**Issue by himanshu2998** [emissary-ingress/emissary#5573]
Hi, I am using tracing service in emissary ingress
https://www.getambassador.io/docs/emissary/latest/topics/running/services/tracing-service
below is the config
```
{{- if .Values.tracing.enabled }}
apiVersion: getambassador.io/v3alpha1
kind:  TracingService
metadata:
  name:  tracing
  namespace: {{ include "ambassador.namespace" . }}
spec:
  service: {{ .Values.tracing.endpoint }}
  {{- if .Values.env }}
  ambassador_id: [{{ .Values.env.AMBASSADOR_ID | quote }}]
  {{- end }}
  driver: opentelemetry
  sampling:
    overall: {{ .Values.tracing.overall_sampling }}
{{- end }}

```
Although I am getting traces but for some traces some spans are missing due to which I am getting missing root spans.
This can be due to high load, is there a way to configure timeouts and batching config for tracing data in the service for opentelemetry driver?
<img width="870" alt="Screenshot 2024-02-15 at 4 39 54 PM" src="https://github.com/emissary-ingress/emissary/assets/41501501/05a40530-8d75-42ae-9a10-2b5bb4ae2af6">
