### ISSUE TITLE
SSL Handshake Failure When Mapping to External HTTPS Service (AWS CloudFront + S3) in Emissary Ingress

### ISSUE THREAD

**Issue by umjoshua** [emissary-ingress/emissary#5609]
Issue Description:
We are encountering an SSL handshake failure when attempting to map to an external HTTPS service hosted on AWS CloudFront with S3 origin. The error message we're receiving is:

```sh
upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: TLS error: 268436496:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE 268435610:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO
```

Mapping Configuration:
````sh
apiVersion: getambassador.io/v3alpha1
kind: Mapping
spec:
  bypass_auth: true
  host_rewrite: ***.**abc.com
  hostname: ***.**xyz.com
  precedence: 500
  prefix: /v4
  rewrite: /index.html
  service: 'https://***.**abc.com'
````

Expected Behavior:
The response should contain the HTML from CloudFront.

Additional Context:
* Emissary Ingress Version: 3.9.1
* The CDN is directly accessible without issue.
* Mapping is working fine when we use http instead of https for service.

Thank you for your attention to this matter.

**Comment by umjoshua** [comment]
The issue was solved by adding a TLSContext with the following conifguration

```
apiVersion: getambassador.io/v3alpha1
kind:  TLSContext
metadata:
  name:  tls
spec:
  ambassador_id: ["ambassador-id"]
  secret: eksqa-secret
  sni: "cdn.abc.com"
```

And TLSContext was referenced in the mapping file.
