### ISSUE TITLE
Listener not accepting HTTPS without a `*` host being defined, but with a `*` host, `mappingSelector` do not work

### ISSUE THREAD

**Issue by dmaclaury** [emissary-ingress/emissary#5626]
**Describe the bug**
Through testing locally and on EKS 1.29 I have run into this same issue. 

- Without a Host defined for the hostname `*`, a listener defined with `protocol: HTTPS` does not accept HTTPS/TLS connections
- If I create a host with `hostname: "*"`, `mappingSelector` does not work on more specific hosts. 

**To Reproduce**
1. Deploy Emissary following the getting started guide, and these values: 
```yaml
namespace:
  name: emissary
ingressClassResource:
  name: emissary
service:
  type: ClusterIP
replicaCount: 1
resources:
  limits:
    # cpu: 100m
    memory: 6000Mi
  requests:
    # cpu: 100m
    memory: 3000Mi
```

```console
helm install emissary-ingress --namespace emissary datawire/emissary-ingress --version 8.9.1 -f emissary-values.yaml 
NAME: emissary-ingress
LAST DEPLOYED: Mon Apr  8 11:02:05 2024
NAMESPACE: emissary
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
-------------------------------------------------------------------------------
  Congratulations! You've successfully installed Emissary Ingress!

-------------------------------------------------------------------------------
To get the IP address of Emissary, run the following commands:
  export POD_NAME=$(kubectl get pods --namespace emissary -l "app=emissary-ingress,release=emissary-ingress" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80

For help, visit our Slack at http://a8r.io/Slack or view the documentation online at https://www.getambassador.io.
```

2. Apply the `qotm` test service from getting started guide
```console
kubectl apply -f https://app.getambassador.io/yaml/v2-docs/3.9.1/quickstart/qotm.yaml

deployment.apps/quote created
service/quote created
```
3. Create a self-signed cert following the steps from https://www.getambassador.io/docs/emissary/latest/howtos/tls-termination
```console
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -subj '/CN=ambassador-cert' -nodes
```
```console
kubectl create secret tls tls-cert --cert=cert.pem --key=key.pem

secret/tls-cert created
```
4. Create the following listener configs (and port forward `443` on the service to `10443` locally)
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8080
  namespace: emissary
spec:
  port: 8080
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: emissary-ingress-listener-8443
  namespace: emissary
spec:
  port: 8443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: ALL
```
5. Create these hosts
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: tls-cert
  mappingSelector:
    matchLabels:
      hostKind: wildcard-host
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: localhost2
spec:
  hostname: localhost2
  tlsSecret:
    name: tls-cert
  mappingSelector:
    matchLabels:
      hostKind: localhost2
  requestPolicy:
    insecure:
      action: Route
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: localhost-splat
spec:
  hostname: "*.localhost"
  tlsSecret:
    name: tls-cert
  mappingSelector:
    matchLabels:
      hostKind: localhost-splat
  requestPolicy:
    insecure:
      action: Route
```
6. Create these mappings
```yaml
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    hostKind: wildcard-host
  name: quote-backend-wildcard
  namespace: default
spec:
  docs:
    path: /.ambassador-internal/openapi-docs
  prefix: /backend/
  service: quote
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  labels:
    hostKind: localhost2
  name: quote-backend
  namespace: default
spec:
  docs:
    path: /.ambassador-internal/openapi-docs
  prefix: /backend/
  service: quote
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend-host
  labels:
    hostKind: localhost2
spec:
  prefix: /
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend-host-splat
  labels:
    hostKind: localhost-splat
spec:
  prefix: /splat-only/
  service: quote
  docs:
    path: "/.ambassador-internal/openapi-docs"
```
7. Check which mappings work - results attached 
[https_with_wildcard_test.txt](https://github.com/emissary-ingress/emissary/files/14911150/https_with_wildcard_test.txt)
But only the `quote-backend-wildcard` mapping is effective
```console
curl -kvv https://localhost:10443/backend/
curl -kvv https://localhost:10443/ -H "Host:localhost2"
curl -kvv https://localhost:10443/backend/ -H "Host:localhost2"
curl -kvv https://localhost:10443/backend/ -H "Host:test.localhost"
curl -kvv https://localhost:10443/splat-only/ -H "Host:test.localhost"
```
8. Delete `host/wildcard-host`
```console
k delete host/wildcard-host                                           
host.getambassador.io "wildcard-host" deleted
```
9. Re-test, and we receive SSL errors on the mappings that should complete
```console
curl -kvv https://localhost:10443/ -H "Host:localhost2"
*   Trying [::1]:10443...
* Connected to localhost (::1) port 10443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
* Closing connection
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```
10. Try the same curl with http on the `https` listener and we see a `200` response
```console
curl -kvv http://localhost:10443/ -H "Host:localhost2"
*   Trying [::1]:10443...
* Connected to localhost (::1) port 10443
> GET / HTTP/1.1
> Host:localhost2
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json
< date: Mon, 08 Apr 2024 21:57:21 GMT
< content-length: 131
< x-envoy-upstream-service-time: 0
< server: envoy
<
{
    "server": "chubby-kiwi-t82xhysy",
    "quote": "668: The Neighbor of the Beast.",
    "time": "2024-04-08T21:57:21.903616Z"
* Connection #0 to host localhost left intact
}%
```

**Expected behavior**
Either, the listener accepts HTTPS connections without a `*` host being created, or more specific routes can use `mappingSelector` when a `*` host is provided. 

In Step 7,  all CURLs should have been `200` response.
In step 9, we would expect a `200` response, but instead get ssl errors
In step 10, we would not expect `200` response on `http` when the host has a TLS-secret and we're using the HTTPS listener 

**Versions (please complete the following information):**
 - Emissary: `3.9.1`, Helm version `8.9.1`
 - Kubernetes environment: Rancher Desktop Kubernetes `1.29.3` and EKS `1.29`

**Additional context**
