### ISSUE TITLE
spec.host_redirect in Mapping does not work

### ISSUE THREAD

**Issue by Vislor** [emissary-ingress/emissary#5776]
**Describe the bug**
In a Mapping, whenever host_redirect is set to true, the mapping is not recognized and doesn't work.  This happens no matter what redirect options are used (path, regex, prefix).  We are not using label selectors to link the Mapping to a Host, we are using hostname and the hostname is not a wildcard (nor does it contain a wildcard).  Mappings without host_redirect seem to work as expected (they are applied and associated with the proper Host).

**To Reproduce**
1. Create a mapping with a host_redirect, such as:
```
apiVersion: ambassador.io/v3alpha1
kind: Mapping
metadata:
  name: test
  namespace: some-namespace
spec:
  hostname: api.dev.local
  prefix: /swagger-dev/
  host_redirect: true
  prefix_redirect: /swagger
```
2. Apply the mapping to the cluster
3. In the diagnostics endpoint (http://localhost:8877/ambassador/v0/diag/) observe that the mapping has not been applied.
4. Test the route, observe that a 404 is returned.

**Expected behavior**
I expect the mapping to be applied and a 301 redirect to be returned.

**Versions (please complete the following information):**
 - Ambassador: Emissary-Ingress 3.9.1
 - Kubernetes environment : kubeadm on VMWare vSphere
 - Version: 1.30.3
