### ISSUE TITLE
Datadog APM not working 

### ISSUE THREAD

**Issue by nanugantiep** [emissary-ingress/emissary#5786]
**Describe the bug**
followed the documentation [here](https://www.getambassador.io/docs/emissary/latest/howtos/tracing-datadog) to configure datadog but do not see traces coming in from Emissary-Ingress.  traces are going fine via [datadog](https://docs.datadoghq.com/tracing/guide/send_traces_to_agent_by_api/?tab=shell) agent

**To Reproduce**
1. implement datadog tracing as mentioned [here](https://www.getambassador.io/docs/emissary/latest/howtos/tracing-datadog) 
2. can not see emissary-ingress in datadog APM

**Expected behavior**
service traces are coming in and see it in Dadadog APM

**Versions (please complete the following information):**
 - Ambassador: **emissary:3.9.1**
 - Kubernetes environment: **EKS**
 - Version: 1.29

**Additional context**
Configuring Envoy JSON logging in values.yaml via HELM 
<img width="694" alt="Screenshot 2024-09-19 at 3 18 25 PM" src="https://github.com/user-attachments/assets/c0e0c58f-87ff-4895-89db-777807907381">
Tracing service 
```
apiVersion: getambassador.io/v3alpha1
kind: TracingService
metadata:
  name: tracing
  namespace: api-emissary
spec:
  service: "${HOST_IP}:8126"
  driver: datadog
  config:
    service_name: api-ambassador-ingress
```
Host IP configuration 
<img width="519" alt="Screenshot 2024-09-19 at 3 20 56 PM" src="https://github.com/user-attachments/assets/12c2cb75-86a8-49db-aed9-26b96d151598">
