### ISSUE TITLE
Diagnostics page reports 0 weight mapping as 100

### ISSUE THREAD

**Issue by buckner** [emissary-ingress/emissary#5811]
**Describe the bug**
 If I define a mapping to have a weight of 0 it is displayed in the route table of the diagnostics page (`[host]/ambassador/v0/diag/`) as having a weight of 100%:
![image](https://github.com/user-attachments/assets/422d360d-7d01-425c-bb2d-d98d2411d0f2)
![image](https://github.com/user-attachments/assets/1d7b3760-97c8-4eb1-95e7-f5eb031337c7)
I've tested it and the weight is actually 0 despite what it says in the GUI

**To Reproduce**

Define two mappings:
```
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: nginx-primary
  namespace: buckner
spec:
  prefix: /
  service: nginx-primary.buckner
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: nginx-canary
  namespace: buckner
spec:
  prefix: /
  service: nginx-canary.buckner
  weight: 0
```
Now check the route table in the diagnostic page and it will show both at 100% instead of the 0-weight mapping as 0%
**Expected behavior**
I expect it to show the correct percentage. If I modify the weight to anything over 0 it works correctly:
![image](https://github.com/user-attachments/assets/431e63c5-7930-4c8f-a745-da7958939b6b)

**Versions (please complete the following information):**
 - Ambassador: 3.9.1
 - Kubernetes environment: Google Kubernetes Engine
 - Version: 1.30.5

**Additional context**
