### ISSUE TITLE
Connection failed during performance test - values into circuit_breakers ignored

### ISSUE THREAD

**Issue by cfabriziohivemq** [emissary-ingress/emissary#5833]
**Describe the bug**
I'm testing the performance of the emissary-ingress, and while testing I run into  "connection failed" issue.
My scenario is AWS NLB-->HaProxy-->broker
Will share the configuration
```
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: mqtts-port-8883-listener
  namespace: emissary
spec:
  port: 8883
  securityModel: SECURE
  protocolStack:
    - TLS
    - TCP
  hostBinding:
    namespace:
      from: ALL
```

the TcpMapping
```
apiVersion: getambassador.io/v3alpha1
kind: TCPMapping
metadata:
  name: broker01-mqtts-tls-mapping
  namespace: mynamespace
spec:
  port: 8883
  service: myservice.mynamespace:1883
  host: mybroker.example.org
  resolver: endpoint
---
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: broker01-host
  namespace: mynamespace
spec:
  hostname: mybroker.example.org
  tlsSecret:
    name: my-certificate
    namespace: mynamespace
  tlsContext:
    name: broker01-context
---
apiVersion: getambassador.io/v3alpha1
kind:  TLSContext
metadata:
  name:  broker01-context
  namespace: mynamespace
spec:
  hosts:
    - mybroker.example.org
  secret: my-certificate
---
```
and the module
```
apiVersion: getambassador.io/v3alpha1
kind: KubernetesEndpointResolver
metadata:
  name: endpoint
  namespace: emissary
---
apiVersion: getambassador.io/v3alpha1
kind:  Module
metadata:
  name:  ambassador
  namespace: emissary
spec:
  config:
    diagnostics:
      enabled: true
    resolver: endpoint
    circuit_breakers:
    - priority: default
      max_connections: 5000
      max_requests: 5000
      max_retries: 10
```
also the NLB annotations and the resource spec set into the values.yaml
```
resources: 
  limits:
    cpu: 3000m
    memory: 10000Mi
  requests:
    cpu: 3000m
    memory: 8000Mi

service:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtts
      port: 8883
      targetPort: 8883

  externalTrafficPolicy: Local

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false,stickiness.enabled=false,deregistration_delay.connection_termination.enabled=true,proxy_protocol_v2.enabled=false
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: 8877
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/ambassador/v0/check_alive"
```
I have a replica 3 so my max_connections should be 15K, but when checking the dashboard of my client connections I have this scenario

![Image](https://github.com/user-attachments/assets/6c1cb85d-f9fc-4f96-a984-85d6eed15b8c)

Client connected successfully 8K only

**Expected behavior**
With the circuit_breakers I should be able to limit the number of client connections, is there a global limit elsewhere to set?

**Versions (please complete the following information):**
 - Ambassador: [3.12.2](emissary:3.12.2)
 - Kubernetes environment - AWS EKS
 - Version 1.30
